algolia/react-instantsearch

- packages/react-instantsearch/src/connectors/connectRefinementList.js
> Fix typo in ConnectRefinementList

- packages/react-instantsearch/src/connectors/connectToggle.js
**Summary**
I noticed that `connectToggle` provides `currentRefinement` to the wrapped component, but this is not present in the documentation. This PR adds documentation for this prop.
> Add `currentRefinement` doc to `connectToggle`

- docgen/src/guide/Highlighting_results.md
- packages/react-instantsearch/src/components/Highlight.js
- packages/react-instantsearch/src/components/Highlight.test.js
- packages/react-instantsearch/src/components/Highlighter.js
- packages/react-instantsearch/src/components/Highlighter.test.js
- packages/react-instantsearch/src/components/Snippet.js
- packages/react-instantsearch/src/components/Snippet.test.js
- packages/react-instantsearch/src/components/__snapshots__/Highlight.test.js.snap
- packages/react-instantsearch/src/components/__snapshots__/Highlighter.test.js.snap
- packages/react-instantsearch/src/components/__snapshots__/Snippet.test.js.snap
- packages/react-instantsearch/src/widgets/Highlight.js
- packages/react-instantsearch/src/widgets/Snippet.js
- stories/Highlight.stories.js
- stories/Snippet.stories.js
**Summary**
`<em>` isn't actually very suited for highlighting, a `<mark>` tag is way better, because it brings its own accessibility, default style etc. with it. For legacy reasons we can't just change the default tag, since that would break all implementations, but it is something we can do in a future major release.
To allow this, a new prop (`HighlightTagName`) was added to Highlight, Snippet and Highlighter. 
See also https://github.com/algolia/instantsearch.js/pull/2092
Compared to the previous pull request I also added a small paragraph in the [guide](https://github.com/algolia/react-instantsearch/compare/feat/custom-highlight-tag?expand=1#diff-dd7bc35948fc032c33147e1ef644ba4a) on why to change the tagname.
I didn't add a deprecation warning to rendering Highlighter without a …
> feat(Highlighter): allow rendering to custom tag

- stories/3rdPartyIntegrations.stories.js
- stories/ClearAll.stories.js
- stories/Conditional.stories.js
- stories/Configure.stories.js
- stories/CurrentRefinements.stories.js
- stories/HierarchicalMenu.stories.js
- stories/Hits.stories.js
- stories/HitsPerPage.stories.js
- stories/Menu.stories.js
- stories/MultiRange.stories.js
- stories/Pagination.stories.js
- stories/RangeInput.stories.js
- stories/RangeSlider.stories.js
- stories/RefinementList.stories.js
- stories/SearchBox.stories.js
- stories/SortBy.stories.js
- stories/StarRating.stories.js
**Summary**
Not all of the Stories were laid out consistently with regard to `linkedStoryGroup` and `hasPlayground`
**Result**
1. reordered all stories to have playground last
2. add `hasPlayground` wherever relevant
3. add `linkedStoryGroup` to all of them
- a better solution would be to add this somehow to the `storiesOf`, but I didn't find a hook for this kind of behaviour.
4. use `stories.add().add()` instead of `stories.add();stories.add()` everywhere
> chore(Stories): put linkedStoryGroup and hasPlayground consistenly

- package.json
See: facebook/jest#3177
On OSX and watch mode, if a test is failing, the terminal-notifier process stays open.
> chore: remove jest notifications

- packages/react-instantsearch/src/components/SearchBox.js
- packages/react-instantsearch/src/components/__snapshots__/Menu.test.js.snap
- packages/react-instantsearch/src/components/__snapshots__/RefinementList.test.js.snap
- packages/react-instantsearch/src/components/__snapshots__/SearchBox.test.js.snap
**Summary**
Since svg allows a width and height attribute, we can use those to provide a default width and height. This has a lower specificity than css defined width or height, because it's an svg.
**Result**
Especially the situation where people don't use the Algolia theme is improved by this.
The SearchBox without styling looks like this:
before|after
---|---
With styling it still looks the same as before.
> feat(SearchBox): add default width and height to buttons.

- packages/react-instantsearch/src/connectors/connectHierarchicalMenu.js
- packages/react-instantsearch/src/connectors/connectHierarchicalMenu.test.js
- packages/react-instantsearch/src/connectors/connectHits.js
- packages/react-instantsearch/src/connectors/connectHits.test.js
- packages/react-instantsearch/src/connectors/connectInfiniteHits.js
- packages/react-instantsearch/src/connectors/connectInfiniteHits.test.js
- packages/react-instantsearch/src/connectors/connectMenu.js
- packages/react-instantsearch/src/connectors/connectMenu.test.js
- packages/react-instantsearch/src/connectors/connectMultiRange.js
- packages/react-instantsearch/src/connectors/connectMultiRange.test.js
- packages/react-instantsearch/src/connectors/connectPagination.js
- packages/react-instantsearch/src/connectors/connectPagination.test.js
- packages/react-instantsearch/src/connectors/connectRange.js
- packages/react-instantsearch/src/connectors/connectRange.test.js
- packages/react-instantsearch/src/connectors/connectRefinementList.js
- packages/react-instantsearch/src/connectors/connectRefinementList.test.js
- packages/react-instantsearch/src/connectors/connectStats.js
- packages/react-instantsearch/src/connectors/connectStats.test.js
- packages/react-instantsearch/src/core/createInstantSearchManager.js
- packages/react-instantsearch/src/core/createInstantSearchManager.result.test.js
- packages/react-instantsearch/src/core/indexUtils.js
- packages/react-instantsearch/src/core/indexUtils.test.js
If no usage of `<Index>`, then there is no need to nest the results under the index name. This PR rollback this behaviour to be the same as v3 regarding single index search.
> fix(MultiIndex): revert breaking change if no multiple index

- packages/react-instantsearch/src/core/createInstantSearchManager.derived.test.js
- packages/react-instantsearch/src/core/createInstantSearchManager.js
If a refinement was applied specifically for the "main" index, then, it would have been applied to all other indices.
> fix(MultiIndex): derived helper were using main index specifics params

- packages/react-instantsearch/src/core/InstantSearch.js
- packages/react-instantsearch/src/core/InstantSearch.test.js
- packages/react-instantsearch/src/core/createConnector.js
- packages/react-instantsearch/src/core/createConnector.test.js
- packages/react-instantsearch/src/core/createInstantSearchManager.js
- packages/react-instantsearch/src/core/createInstantSearchManager.test.js
See algolia/instantsearch.js#2061
Also fix issue with SPA => you want to move to another URL, but because of the unmount, onSearchStateChange is called and then you go back.
> fix(InstantSearch): dont fire request/onsearchStateChange when unmounting

- package.json
- scripts/test.sh
**Summary**
Run jest with [--runInBand](http://facebook.github.io/jest/docs/cli.html#runinband) in CI. I heard a few times that this makes the tests faster on Travis, so let's give it a try
**Result**
before|after
---|---
±5 min | 3 min 55 sec
4 min 38 sec | 3 min 55 sec
||4 min 7 sec
||3 min 56 sec
> chore(tests): run jest with --runInBand in CI

- packages/react-instantsearch/src/connectors/connectSortBy.js
This sentence had slight readability problems (as evidenced by a recent support ticket), so I rewrote it a bit.
**Summary**
Rewrite the main documentation sentence for `connectSortBy`. 
**Result**
simplified diff: 
```diff
- connectSortBy connector provides the logic to build a widget that will
- displays a list of indexes allowing a user to change the hits are sorting.
+ The connectSortBy connector provides the logic to build a widget that will
+ display a list of indices. This allows a user to change how the hits are being sorted.
```
> docs(connectSortBy): clarify the main sentence

- docgen/src/guide/Conditional_display.md
> docs: typo with displaying content when loading

- packages/react-instantsearch/examples/autocomplete/public/index.html
- packages/react-instantsearch/examples/autocomplete/src/App-Multi-Index.js
- packages/react-instantsearch/examples/autocomplete/src/index.js
- packages/react-instantsearch/src/core/Index.js
- packages/react-instantsearch/src/core/Index.test.js
- packages/react-instantsearch/src/core/createInstantSearchManager.derived.test.js
- packages/react-instantsearch/src/core/createInstantSearchManager.js
- stories/MultiIndex.stories.js
see #15.
Now you can use `connectAutoComplete` like:
```js
<InstantSearch
appId=""
apiKey=""
indexName="ikea"
>
<Configure hitsPerPage={1} />
<Index indexName="bestbuy" />
<Index indexName="airbnb" />
<AutoComplete />
```
> feat(MultiIndex): remove the need for virtual hits when using connectAutoComplete

- packages/react-instantsearch/src/widgets/ClearAll.js
- packages/react-instantsearch/src/widgets/Configure.js
- packages/react-instantsearch/src/widgets/CurrentRefinements.js
- packages/react-instantsearch/src/widgets/HierarchicalMenu.js
- packages/react-instantsearch/src/widgets/Highlight.js
- packages/react-instantsearch/src/widgets/Hits.js
- packages/react-instantsearch/src/widgets/HitsPerPage.js
- packages/react-instantsearch/src/widgets/InfiniteHits.js
- packages/react-instantsearch/src/widgets/Menu.js
- packages/react-instantsearch/src/widgets/MultiRange.js
- packages/react-instantsearch/src/widgets/Pagination.js
- packages/react-instantsearch/src/widgets/Panel.js
- packages/react-instantsearch/src/widgets/PoweredBy.js
- packages/react-instantsearch/src/widgets/RangeInput.js
- packages/react-instantsearch/src/widgets/RefinementList.js
- packages/react-instantsearch/src/widgets/ScrollTo.js
- packages/react-instantsearch/src/widgets/SearchBox.js
- packages/react-instantsearch/src/widgets/Snippet.js
- packages/react-instantsearch/src/widgets/SortBy.js
- packages/react-instantsearch/src/widgets/StarRating.js
- packages/react-instantsearch/src/widgets/Stats.js
- packages/react-instantsearch/src/widgets/Toggle.js
**Summary**
The examples in the widget jsdoc were outdated, and using wrong imports.
**Result**
All examples of the widget now have the correct imported widgets, *and* the correct package imported from.
closes #50
cc @davidfurlong
> docs(Widgets): update example imports

- packages/react-instantsearch/src/connectors/connectHierarchicalMenu.test.js
- packages/react-instantsearch/src/connectors/connectMenu.test.js
- packages/react-instantsearch/src/connectors/connectMultiRange.test.js
- packages/react-instantsearch/src/connectors/connectPagination.test.js
- packages/react-instantsearch/src/connectors/connectRange.test.js
- packages/react-instantsearch/src/connectors/connectRefinementList.test.js
- packages/react-instantsearch/src/connectors/connectStats.test.js
- packages/react-instantsearch/src/core/indexUtils.js
- packages/react-instantsearch/src/core/indexUtils.test.js
This was a regression due to: https://github.com/algolia/react-instantsearch/pull/36
See: https://github.com/algolia/react-instantsearch/issues/55
Allows this syntax: 
```js
<InstantSearch
appId=""
apiKey=""
indexName="index1"
>
<SearchBox />
<CustomHits />
<Index indexName="index2">
<CustomHits />
</Index>
```
> fix(MultIndex): no need to nest hits, if those are from main index.

- packages/react-instantsearch/src/core/InstantSearch.js
- packages/react-instantsearch/src/core/InstantSearch.test.js
**Summary**
ApiKey parameter is not changed in search query when InstantSearch component is updated with new apiKey props.
Algolia client is updated with new values if appId or apiKey is changed (at createInstantSearch.js:39) but helper in InstantSearchManager (created in InstantSearch component) is not updated.
**Result**
I created component that render InstantSearch with apiKey "exampleApiKey1" then i changed component state (with setTimeout for the example) to render InstantSearch again but with a new apiKey props. (exampleApiKey2)
Without my fix, ajax call is always called with exampleApiKey1
http://image.prntscr.com/image/c5a1670088ad4e7b9edfaff72ec9479b.png
With my fix, ajax get is called with exampleApiKey1 then exampleApiKey2 after rendering with the new props (see screens) …
> fix(core/InstantSearch): update algoliaClient when it change

- packages/react-instantsearch/src/connectors/connectAutoComplete.js
- packages/react-instantsearch/src/connectors/connectAutoComplete.test.js
**Summary**
fixes #74
the strategy to get the hits from all indices assumed it needed to loop over the index names, but that’s only true if we’re in a situation with multiple hits. 
You can detect this if there is a `hits` key on the `searchResults`, and in that case we can just return the hits
**Result**
No more iteration over the `searchResults` object if there is a `hits` (which is an array) key on it.
> fix(connectAutoComplete): allow usage with hits from a single index

- packages/react-instantsearch/examples/geo-search/src/App.js
**Summary**
Fix a typo in the geo-search demo
**Result**
appartement -> apartment
> docs(geo-search): fix typo

- .github/ISSUE_TEMPLATE.md
- docgen/layouts/index.pug
- docgen/src/examples/Demos.md
- docgen/src/examples/Recipes.md
- docgen/src/guide/Custom_connectors.md
**Summary**
Discourse links are outdated/not specific enough
fixes #82 
**Result**
update the links from `/c/instantsearch` and `/` to `/tags/react-instantsearch`
> docs(discourse): update links to correct discourse tag

- docgen/src/guide/Conditional_display.md
- docgen/src/guide/Routing.md
To be more easily searcheable via cmd+f or docsearch
> docs(guide): add url in routing title

- packages/react-instantsearch/src/core/indexUtils.js
- packages/react-instantsearch/src/core/indexUtils.test.js
**Summary**
Since the https://github.com/algolia/react-instantsearch/commit/09a4e1dfd98c8989aa292bae4bf792aaf9aa7c48 commit, nested attributes for faceting are no longer working. 
Before, condition if id exists in a state looked like this: [```if (searchState[namespace] && typeof searchState[namespace][id] !== 'undefined') {```](https://github.com/algolia/react-instantsearch/commit/09a4e1dfd98c8989aa292bae4bf792aaf9aa7c48#diff-ff7d5a81ec7fdde10efeed49448d38d5L14). 
Now namespace and id are merged together [```${namespace}.${getId(props)}```](https://github.com/algolia/react-instantsearch/commit/09a4e1dfd98c8989aa292bae4bf792aaf9aa7c48#diff-ff7d5a81ec7fdde10efeed49448d38d5R13) and condition moved to ```indexUtils.getCurrentRefinementValue()``` function and looks like this …
> fix nested attributes for faceting

- packages/react-instantsearch/src/widgets/HitsPerPage.js
**Summary**
The documentation suggests you should provide the `value` property as a `String` but the PropType suggests otherwise.
**Result**
Ammended so the example shows the correct implementation.
> docs(HitsPerPage): fix typo + wrong data type

- packages/react-instantsearch/src/core/createInstantSearchManager.derived.test.js
I did a quick preg for all imports of algoliasearch', and this was the only one that is imported without the /lite. Even though this is mocked, and thus doesn't really have usages in the test, it's still best to use the same dependency everywhere.
> test(manager): use algoliasearch/lite

- docgen/src/guide/Custom_connectors.md
> chore(typo): Fix typo in documentation

- docgen/src/Getting_started.md
The link to the video was using a capitalized `Index.html` which
failed to resolve, resulting in a 404. Using the lowercase version
works better.
> docs(video): Fixing link to video in Getting Started

- docgen/assets/data/community-projects.json
- docgen/layouts/common/meta.pug
The website was loading Cloudinary assets using and http protocol,
resulting in Mixed-Content warning and images not displayed.
I changed it in the OG meta as well, even if I'm not sure it was necessary.
> docs(cloudinary): Use https link for Cloudinary images

- packages/react-instantsearch/src/connectors/connectInfiniteHits.js
- packages/react-instantsearch/src/connectors/connectInfiniteHits.test.js
see: https://jsfiddle.net/spondbob/sm3cad75/ and https://github.com/algolia/react-instantsearch/issues/123
> fix(InfiniteHits): changing hitsPerPage were causing duplicates

- storybook/postcss.config.js
- storybook/webpack.config.js
CSS theme is not vendor prefixed into storybook, which leads to the issue #135.
This PR use `postcss-loader` to process css into `autoprefixer` to resolve it 👍
> fix(storybook): process CSS through autoprefixer

- packages/react-instantsearch/src/core/indexUtils.js
- packages/react-instantsearch/src/core/indexUtils.test.js
Use case: you handle a tab navigation without any router and you're switching between a multiple indices display and several only one indices display. 
At some point, before the rendering of only one indices, the namespace with the index name is not here yet, so without this check it crashed.
> fix(MultiIndex): handle if namespace isn't in search state

- packages/react-instantsearch/src/connectors/connectHierarchicalMenu.test.js
- packages/react-instantsearch/src/connectors/connectHits.test.js
- packages/react-instantsearch/src/connectors/connectInfiniteHits.test.js
- packages/react-instantsearch/src/connectors/connectMenu.test.js
- packages/react-instantsearch/src/connectors/connectMultiRange.test.js
- packages/react-instantsearch/src/connectors/connectPagination.test.js
- packages/react-instantsearch/src/connectors/connectRange.test.js
- packages/react-instantsearch/src/connectors/connectRefinementList.test.js
- packages/react-instantsearch/src/connectors/connectStats.test.js
- packages/react-instantsearch/src/core/indexUtils.js
- packages/react-instantsearch/src/core/indexUtils.test.js
I need to revert this commit because it breaks our SortBy feature. 
As for now we don't have a simple way to handle a switch between the multi and mono indices mode. What it means for the user is that a connector can get hits that were meant for another index before getting the right one. 
There's two ways to handle this issue on user side: 
-> Always be in multi indices mode => It means that when you are on a tab that contains only one index you can still add another `<Index/>` but empty. 
-> Check the shape of the hits and decide to proceed with it or not. (i.e => hit.brand ? ... : null). 
Ultimately we will need to find a way to fix this properly. I can see several options: 
-> SearchResults are always namespaced by the indexName. This is a breaking change because the `createConnector` …
> fix(results): revert commit that ensure hits are returned only if right indices

- packages/react-instantsearch/src/core/createStore.js
- packages/react-instantsearch/src/core/createStore.test.js
This commit introduced: 
- setState warning
- input delay when a high CPU. 
This fix was for:
- avoid infinite loop when conditionally display based on the search results "loading" boolean
- avoid infinite loop when nesting widgets along with a permanent change of their results.
> Revert "fix(store): delay call to listener to prevent infinite loops (#143)"

- docgen/src/Getting_started_React_native.md
**Summary**
Example in https://community.algolia.com/react-instantsearch/Getting_started_React_native.html is missing a `Text` import.
**Result**
Simple docs fix.
> docs(RN): Added missing Text import in React Native docs example

- packages/react-instantsearch/src/core/createInstantSearchManager.js
Previously I was resetting the error when sending a new query. Considering that you can send multiple query at the same time, you can have trouble: 
1. Send a first query => error: null
2. Send a second query => error: null
3. First query return in error => error: 'some error'
4. Second query return successfully => error: 'some error' (not ok).
> fix(error): reset error when receiving results of a query (not when sending it)

- packages/react-instantsearch/src/core/createInstantSearchServer.js
- packages/react-instantsearch/src/core/highlightTags.js
See https://github.com/algolia/react-instantsearch/issues/168
The Server-side html is rendered perfectly but then when rendered on the client using the `resultsState` props, results are containing the server old timestamp and `<Highlight>` the new client one. The `<Highlight/>` component then doesn't see any highlighted values and that's why we can see the little glitch. 
For now, the solution is to remove the `timestamp` when dealing with highlighting tags.
> fix(highlight): wrong parsing between client and server

- renovate.json
**Summary**
Renovate uses `chore(deps)` as default semantic commit prefix however overrides it to `fix(deps)` only for updates to `dependencies`.
This configuration change will "override that override" so that you should receive `chore(deps)` as the prefix for all Renovate commits and Pull Request titles.
> chore(deps): Use chore(deps) for all Renovate updates

- packages/react-instantsearch/src/components/PoweredBy.js
- packages/react-instantsearch/src/components/__snapshots__/PoweredBy.test.js.snap
**Summary**
The Algolia logo in the PoweredBy component didn't have an `aria-label`. This was noticed in #209 by @davidfurlong.
**Result**
The label says "Algolia", since the text before it is "powered by "
fixes #209
> fix(PoweredBy): add a label to the Algolia logo

- packages/react-instantsearch/src/components/RefinementList.js
A small fix to improve the UX of navigating refinements. Right now the numbers appear cluttered:
With this change, the numbers will look cleaner and will also be shown with language-sensitive representations.
> Format the count of items appearing in a refinement

- packages/react-instantsearch/src/widgets/RefinementList.js
The two CSS classes shown for `.RefinementList__itemCount {}` and `.RefinementList__itemCountSelected` on https://community.algolia.com/react-instantsearch/widgets/RefinementList.html are currently missing the `ais-` prefix :)
> Fix CSS classes shown for ais-RefinementList__itemCount

- .travis.yml
- packages/react-instantsearch/src/core/highlightTags.js
We introduce a breaking change when switching from timestamped highlighting tags to the opposite to make it compatible with SSR. 
Who is concerned by the breaking change: people using regex to parse our tags (if Highlight can't handle a use case). 
Indeed, I think we can avoid such a breaking change (and then bumping to version 5) by adding 10 fix numbers to our tags.
> fix(Highlighting): revert breaking change

- stories/SearchBox.stories.js
This seems more natural to me.
Google results for 
1. events logs: About 58,900,000 results  (but all top ones mentioning `event logs` in the title) 
2. event logs: About 11,800,000 results
> docs(storybook): events logs --> event logs

- packages/react-instantsearch/src/components/List.js
**Summary**
I have been using the `<MultiRange />` like this:
```jsx
<MultiRange
attributeName="computed_price"
items={[
{
end: 10,
label: [
<span key={0}>&lt; </span>,
<Price key={1} pence={1000} displayCurrency="GBP" />
]
},
{
start: 10,
end: 100,
label: [
<Price key={0} pence={1000} displayCurrency="GBP" />,
<span key={1}> - </span>,
<Price key={2} pence={10000} displayCurrency="GBP" />
]
},
{
start: 100,
end: 500,
label: [
<Price key={0} pence={10000} displayCurrency="GBP" />,
<span key={1}> - </span>,
<Price key={2} pence={50000} displayCurrency="GBP" />
]
},
{
start: 500,
label: [
<span key={0}> &gt; </span>,
<Price key={1} pence={50000} displayCurrency="GBP" />
]
}
]}
/>
```
According to the propTypes, defined in the MultiRange component, it's meant to accept any renderable element …
> [RFC] Adds support for any type of renderable element in List component

- docgen/src/guide/Virtual_widgets.md
When I initially read the docs about virtual widgets, I did not understand why the virtual menu was being used and it was confusing. I have added a couple of sentences that should make understanding the use of the `VirtualMenu` more clear, which should, in turn, make the understanding of virtual widgets easier to understand.
If anything seems to be unclear or can be better, please let me know!
**Summary**
**Result**
> Attempting to make the virtual widget docs clearer

- packages/react-instantsearch/examples/react-native/yarn.lock
- packages/react-instantsearch/src/core/Index.js
- packages/react-instantsearch/src/core/Index.test.js
- packages/react-instantsearch/src/core/createConnector.js
- packages/react-instantsearch/src/core/createInstantSearchManager.derived.test.js
- packages/react-instantsearch/src/core/createInstantSearchManager.error.test.js
- packages/react-instantsearch/src/core/createInstantSearchManager.js
- packages/react-instantsearch/src/core/createInstantSearchManager.result.test.js
- packages/react-instantsearch/src/core/createInstantSearchServer.js
- packages/react-instantsearch/src/core/createInstantSearchServer.test.js
See https://github.com/algolia/react-instantsearch/issues/310
Basically until now you couldn't have dynamic `<Index>`.
I think I also fix a bug with MultiIndex and SSR (a way to express multi index wasn't taken into account) with this PR. 
What are the big changes here: the widget manager store the whole component instead of explicitly choose at constructor time.
> fix(MultiIndex): Trigger new search when `<Index>` props are updated

- docgen/src/examples/tourism/App.js
See: https://github.com/algolia/react-instantsearch/issues/371
> docs(tourism): fix capacity selector

- docgen/src/guide/Highlighting_results.md
The import was from `InstantSearch`, while it should've been from `react-instantsearch/dom`
> docs(highlight): prettier and fix import

- docgen/layouts/common/meta.pug
Widgets and connectors had an hardcoded description (same global variable name shared between our jsdoc parsing and the meta.pug file)
> docs(website): widgets and connectors have the same desc

- packages/react-instantsearch/examples/react-router-v3/package.json
- renovate.json
- activate automerge 
- use preset for known monorepo
- don't update react-router within react-router-v3 examples
> chore(renovate): tune configuration

- packages/react-instantsearch/src/connectors/connectRange.js
- packages/react-instantsearch/src/connectors/connectRange.test.js
- stories/RangeInput.stories.js
**Summary**
Fix #384 
This PR only fix the problem related to missing boundaries on first call.
**Result**
You can play with the `RangeInput` & `RangeSlider` widget on Storybook.
* set boundaries on the widget
* the results should normally be filter with the provided boundaries
**Before**:
**After**:
> Fix connectRange ignores boundaries on first call

- packages/react-instantsearch-theme-algolia/styles/_InfiniteHits.scss
Add a `disabled` style to the LoadMore button on Algolia theme.
fixes https://github.com/algolia/react-instantsearch/issues/119
> fix(InfiniteHits): add disabled style to the LoadMore button

- packages/react-instantsearch/src/components/Panel.js
- packages/react-instantsearch/src/components/RangeInput.js
- packages/react-instantsearch/src/components/RangeInput.test.js
**Summary**
Since we upgraded to `react@16` the `RangeInput` with a `Panel` has stopped working. The problem is that: for an strange reason when we call `setState` for update the current value inside the inputs, the lifecycle hook `componentWillReceiveProps` is called. Since we don't check that the previous values have **really** changed the state is always override with the original values from set on the `searchState`.
This is only a workaround the real problem is that the hook is called and it should not be called. I tried to dig a little and actually for `react` the `context` really changed before & after the setState that's why the hook is called. But I don't figure out why it changed... I tried to always return the same object from the `Panel::getChildContext`, it actually works but …
> Fix RangeInput react@16

- .travis.yml
A while ago, travis updated the ubuntu distribution they were using for builds. It was failing due to some uglify.js issues. 
Seems that those issues are gone now, so there's no need to stay on the `precise` distrubition.
> chore(travis): uses latest distribution

- packages/react-instantsearch/src/widgets/Toggle.js
From `connectToggle`:
```js
propTypes: {
label: PropTypes.string,
filter: PropTypes.func,
attributeName: PropTypes.string,
value: PropTypes.any,
...
```
Additionally this is really confusing if it is supposed to be a string, how do you toggle on a boolean value?
Also I asked this here: https://discourse.algolia.com/t/how-to-create-a-toggle-for-the-absence-of-a-string-attribute/2460
but without response.
> Update Toggle.js type

- package.json
- stories/Breadcrumb.stories.js
- stories/ClearAll.stories.js
- stories/Conditional.stories.js
- stories/Configure.stories.js
- stories/CurrentRefinements.stories.js
- stories/HierarchicalMenu.stories.js
- stories/Highlight.stories.js
- stories/Hits.stories.js
- stories/HitsPerPage.stories.js
- stories/InfiniteHits.stories.js
- stories/Menu.stories.js
- stories/MenuSelect.stories.js
- stories/MultiIndex.stories.js
- stories/MultiRange.stories.js
- stories/Pagination.stories.js
- stories/PoweredBy.stories.js
- stories/RangeInput.stories.js
- stories/RangeSlider.stories.js
- stories/RefinementList.stories.js
- stories/ScrollTo.stories.js
- stories/SearchBox.stories.js
- stories/Snippet.stories.js
- stories/SortBy.stories.js
- stories/StarRating.stories.js
- stories/Stats.stories.js
- stories/Toggle.stories.js
- storybook/addons.js
- yarn.lock
**Summary**
Add a new Storybook addon to monitor our components for being accessible.
See #221.
**Result**
There is a new "Accessibility" tab displayed on the right sidebar that shows both the a11y "violations" and the "passes".
> docs(storybook): add a11y addon

- .eslintignore
**Summary**
When the recipes are built ESLint will try to lint them too.
- `build`
- `.next`
- `.expo`
> chore: ignore build/.expo/.next folder from ESLint

- packages/react-instantsearch/examples/react-native/App.js
- packages/react-instantsearch/examples/react-native/app.json
- packages/react-instantsearch/examples/react-native/package.json
- packages/react-instantsearch/examples/react-native/shim-react-native.js
- packages/react-instantsearch/examples/react-native/tests/__snapshots__/App.test.js.snap
- packages/react-instantsearch/examples/react-native/yarn.lock
- shim.js
**Summary**
Update the `react-native` example dependency:
- `react-native-scripts@1.7.0`
- `expo@22.0.3`
- `react-native@0.49.3` - *expo doesn't support upper versions yet*
- `react-native-router-flux@4.0.0-beta.23`
**Result**
The example is running on expo & the tests pass.
> Chore: React Native example update

- packages/react-instantsearch/examples/react-router/src/App.js
**Summary**
This example properly updates the browser history on changes, but if you navigate using the browser back and next buttons, the search query doesn't change to match. This addition of a `componentWillReceiveProps` lifecycle method fixes that issue.
**Result**
Clone the example, run `yarn`, then `yarn start`.  Verify that searching and filtering still work correctly, and that browser navigation and full reload both maintain the search state correctly.
> [Bugfix] Properly update search query when using browser navigation

- stories/util.js
**Summary**
This PR aims at allowing us to use our custom component `WrapWithHits` with another index than the Ikea one usually used in the stories.
**Result**
The `WrapWithHits` component can still be used like it was previously:
```
stories.addWithJSX(
'default',
() => (
<WrapWithHits>
<Hits />
</WrapWithHits>
),
{
displayName,
filterProps,
}
);
```
However if you need to use a different index, then you would simply need to specify your credentials via the 'appId', 'apiKey' and 'indexName' props. If you don't specify anything, the Ikea dataset will be used by default.
```
stories.addWithJSX(
'default',
() => (
<WrapWithHits
appId="newAppId"
apiKey="newSearchOnlyApiKey"
indexName="newIndexName"
>
<Stats />
</WrapWithHits>
),
{
displayName,
filterProps,
}
);
```
> docs(storybook): allow WrapWithHits usage with a different index

- packages/react-instantsearch/src/components/Hits.js
Small refactoring around the `Hits` component:
- remove useless ESLint comment
- rename defaultProps parameter it can be confusing to see `hit` instead of `props`
- use functional component instead of class
> Refactor Hits component

- packages/react-instantsearch/src/components/MenuSelect.js
- packages/react-instantsearch/src/widgets/MenuSelect.js
- stories/MenuSelect.stories.js
**Summary**
MenuSelect prop-types only allow for type `number` for `item.count`. This makes it impossible to `transformItems` in the widget so that the count is localized, because `.toLocaleString()` returns a string which causes prop validation to fail.
**Result**
[packages/react-instantsearch/src/components/MenuSelect.js](https://github.com/devwax/react-instantsearch/commit/57cae7f0efc9a8c71b74bcce9b23be16205f6260#diff-1da44248085324fe2f25d7ada1bfe6e6)
Changed MenuSelect `items` > `item.count` prop-type to accept string as well as number using `PropTypes.oneOfType([...])`.
Require-chaining w/ `oneOfType` keeps the prop mandatory regardless of type. See [prop-types docs](https://www.npmjs.com/package/prop-types).
[stories/MenuSelect.stories.js](https://github.com/devwax/react-instantsearc …
> fix(localizecount): allow localized string for count in MenuSelect

- packages/react-instantsearch/src/core/createInstantSearchManager.derived.test.js
- packages/react-instantsearch/src/core/createInstantSearchManager.js
- stories/MultiIndex.stories.js
**Summary**
Fix #636 
We already track the index for the `shared` parameters, but not for the `main` parameters. This PR aims to fix this issue by tracking all the indices.
**Result**
You can play with the example on [Storybook](https://deploy-preview-660--react-instantsearch.netlify.com/react-instantsearch/storybook/?selectedKind=%3CIndex%3E&selectedStory=with%20SortBy%20nested%20in%20same%20Index%20as%20Root&full=0&down=1&left=1&panelRight=1&downPanel=storybooks%2Fstorybook-addon-knobs).
> fix: track all index in the manager

- packages/react-instantsearch/src/core/indexUtils.js
- packages/react-instantsearch/src/core/indexUtils.test.js
- stories/MultiIndex.stories.js
**Summary**
Fix #637 
With the multi indices we always reset the page when a shared widget is updated even when `resetPage` property is not passed. This PR aims to fix this, now we reset the page only the property is provided.
**Result**
We can play the example on [Storybook](https://deploy-preview-665--react-instantsearch.netlify.com/react-instantsearch/storybook/?selectedKind=%3CIndex%3E&selectedStory=with%20Hits%20%26%20Configure&full=0&down=1&left=1&panelRight=1&downPanel=kadira%2Fjsx%2Fpanel).
> fix: reset page with multi index

- packages/react-instantsearch/examples/react-native/package.json
- packages/react-instantsearch/examples/react-native/yarn.lock
**Summary**
Remove useless `native-base` dependency from the `react-native` example.
> chore(ReactNativeExample): remove useless native-base dependency

- package.json
**Summary**
The size of `Dom.js` has been reached on the PR #544.
> chore: increase Dom bundle max size

- packages/react-instantsearch/src/components/SearchBox.js
- packages/react-instantsearch/src/components/__snapshots__/Menu.test.js.snap
- packages/react-instantsearch/src/components/__snapshots__/RefinementList.test.js.snap
- packages/react-instantsearch/src/components/__snapshots__/SearchBox.test.js.snap
This way the browser is better able to report the state of the component for accessibility.
> fix(SearchBox): use hidden over style to hide loader

- docgen/src/guide/Handling_cache.md
- docgen/src/guide/Refreshing_cache.md
- stories/RefreshCache.stories.js
**Summary**
In the wake of the refresh cache feature (#619), this is a guide on how to refresh the cache with the description of the use case and an explanation of the two different approaches that can be used.
> docs(refreshcache): add guide

- packages/react-instantsearch/examples/geo-search/src/__snapshots__/App.test.js.snap
- packages/react-instantsearch/examples/multi-index/src/__snapshots__/App.test.js.snap
- packages/react-instantsearch/examples/next-app/tests/__snapshots__/index.test.js.snap
- packages/react-instantsearch/examples/react-router-v3/src/__snapshots__/App.test.js.snap
- packages/react-instantsearch/examples/react-router/src/__snapshots__/App.test.js.snap
- packages/react-instantsearch/examples/server-side-rendering/src/app/__snapshots__/index.test.js.snap
- packages/react-instantsearch/src/core/__snapshots__/createInstantSearch.test.js.snap
- packages/react-instantsearch/src/core/createInstantSearch.test.js
**Summary**
With `jest@22` the mock function are now print with the snapshot. 
So when we call `createInstantSearch` from the test, we provide a mock client with the current version of the lib. We already test that the instance is called with the correct client (see below). So we don't need to print the client mock in the snapshot. It will avoid that every time we release a new version we have to fix the snapshot, just because the version bump.
> https://github.com/algolia/react-instantsearch/pull/749/files#diff-89fda296b36d39c13ca0e69ebdb33163R34
> fix(createInstantSearch): remove the client from the Snapshot

- packages/react-instantsearch/src/core/InstantSearch.js
- packages/react-instantsearch/src/core/createInstantSearch.js
- packages/react-instantsearch/src/core/createInstantSearch.test.js
- stories/InstantSearch.stories.js
**Summary**
Fix #285 
Enable the possibility to pass custom `root` props to InstantSearch. Don't introduce any breaking change, since we use the root of `createInstantSearch` as `defaultProps`.
**Result**
The following example is with React Native, when we don't pass `flex: 1` to InstantSearch the list is crop before the end.
**Before**
**After**
> feat: InstantSearch root props

- docgen/src/guide/Refreshing_cache.md
- stories/RefreshCache.stories.js
**Summary**
Clear the interval on component `willUnmount`.
> fix: refresh cache memory leak example

- stories/InstantSearch.stories.js
- stories/MultiIndex.stories.js
**Summary**
Use an other style attribute for the custom root prop, because the background with the `linear-gradient` breaks Argos almost every time.
> fix(stories): avoid to use linear-background it breaks Argos every time

- packages/react-instantsearch/src/components/SearchBox.js
- packages/react-instantsearch/src/components/SearchBox.test.js
- stories/SearchBox.stories.js
**Summary**
Fix #799 
When the button `reset` is clicked the query should be clear. But it's only works when the `searchAsYouType` is `true` since we are using the same function for the `reset` & `change` event. Now we don't use the same function for both events. 
In a future refactoring we can probably avoid to handle the state of the query with two different cases (control & uncontrol). We could move for a full control input with a copy of the current refinement in the local state. It will avoid to have two sources of truth in the component.
**Before**
**After**
You can also play with the example on [Storybook](https://deploy-preview-802--react-instantsearch.netlify.com/react-instantsearch/storybook/?knob-showLoadingIndicator=true&selectedKind=SearchBox&selectedStory=without%20search%20a …
> fix: Clear SearchBox without search as you type

- packages/react-instantsearch/src/components/Highlight.js
- packages/react-instantsearch/src/widgets/Highlight.js
**Summary**
Amending the Highlight.js widget documentation to correct prop name for `separator`. The rationale for changing documentation rather than change to actual prop is because the single word `separator` is more in keeping with the other props.  Issue from  https://github.com/algolia/react-instantsearch/issues/803
> Update prop name

- packages/react-instantsearch/src/connectors/connectRange.js
- packages/react-instantsearch/src/connectors/connectRange.test.js
**Summary**
Fix #630 
In the `connectRange` we need to access the stats & the values of the given facet in order to compute the range. But it may happen that the facet is not yet present on the results so we need to check that the facet is present on results before accessing it.
> fix(connectRange): check if facet exist before access

- CHANGELOG.md
It seems the changelog generation tool you've used doesn't take
into account that HTML-looking code is good to be escaped when
converted to Markdown. This is something which could be looked into separately.
Also, I'd prefer to go with fixed-width inline code elements for things like that: `InstantSearch` and `<InstantSearch>`.
**Summary**
**Result**
> Escape HTML in changelog

- packages/react-instantsearch/src/connectors/connectRange.js
- packages/react-instantsearch/src/widgets/RangeInput.js
- stories/RangeInput.stories.js
**Summary**
Fix #518 
Set the precision of `connectRange` to 0 by default instead of 2. It means that you don't have floating numbers by default in the `RangeInput` & `RangeSlider` (custom).
> refactor(connectRange): update default precision to 0

- packages/react-instantsearch/src/components/Breadcrumb.js
- packages/react-instantsearch/src/components/SearchBox.js
- packages/react-instantsearch/src/components/SearchBox.test.js
- packages/react-instantsearch/src/components/__snapshots__/Breadcrumb.test.js.snap
- packages/react-instantsearch/src/connectors/connectBreadcrumb.js
- packages/react-instantsearch/src/widgets/Breadcrumb.js
- packages/react-instantsearch/src/widgets/Highlight.js
- packages/react-instantsearch/src/widgets/SearchBox.js
- packages/react-instantsearch/src/widgets/Snippet.js
- stories/Breadcrumb.stories.js
- stories/SearchBox.stories.js
**Summary**
This PR rename some props from `xxxComponent` to `xxx` because they don't really accept a component. They just accept anything that can be render by React (aka: [`node`](https://reactjs.org/docs/typechecking-with-proptypes.html#proptypes)). Only `Hits` & `InifiniteHits` accept a real component. The principal changes are on the `SearchBox`, otherwise it's mainly docs changes.
I also moved the props related to the rendering from `connectBreadcrumb` to the `Breadcrumb` component since they are unused in the connector.
**SearchBox**:
- `submitComponent` -> `submit`
- `resetComponent` -> `reset`
- `loadingIndicatorComponent` -> `loadingIndicator`
> refactor: rename xxxComponent props

- docgen/src/Getting_started.md
- docgen/src/guide/Styling_widgets.md
- packages/react-instantsearch-theme-algolia/package.json
- packages/react-instantsearch/examples/next-app/components/head.js
We recommended unpkg at the begining, it was the only one serving other
files than JS from npm.
Now jsDelivr supports it by default since a long time, and we can inform
jsDelivr whats the default file to serve (to avoid style.min.css).
This will only work on the new release of the lib.
Also I updated the versions of the theme in the docs, might be worth
automating it or you'll have to do it next time too.
> chore(theme): use jsDelivr by default and set alias

- packages/react-instantsearch/connectors.js
- packages/react-instantsearch/dom.js
- packages/react-instantsearch/src/components/ToggleRefinement.js
- packages/react-instantsearch/src/components/ToggleRefinement.test.js
- packages/react-instantsearch/src/components/__snapshots__/ToggleRefinement.test.js.snap
- packages/react-instantsearch/src/components/index.js
- packages/react-instantsearch/src/connectors/connectToggleRefinement.js
- packages/react-instantsearch/src/connectors/connectToggleRefinement.test.js
- packages/react-instantsearch/src/widgets/ToggleRefinement.js
- stories/CurrentRefinements.stories.js
- stories/ToggleRefinement.stories.js
**Summary**
Finally close #519 
This PR rename the widget Toggle for ToggleRefinement. 
IS.css doesn't have migrate the widget yet but it's tracked.
> refactor: rename Toggle to ToggleRefinement

- packages/react-instantsearch/src/core/createConnector.js
Necessary for IE 11 compatibility and avoids having to use a polyfill. Fixes #869
> Use substr instead of startsWith

- docgen/src/guide/Custom_connectors.md
- packages/react-instantsearch/src/connectors/connectMenu.js
- packages/react-instantsearch/src/connectors/connectMenu.test.js
- packages/react-instantsearch/src/connectors/connectRefinementList.js
- packages/react-instantsearch/src/connectors/connectRefinementList.test.js
- packages/react-instantsearch/src/core/createConnector.js
- packages/react-instantsearch/src/core/createInstantSearchManager.js
- packages/react-instantsearch/src/core/createInstantSearchManager.result.test.js
**Summary**
Fix #707 
Inside the `RefinementList` & `Menu` we can search through the list of items. On the first render the `maxValuesPerFacet` is correctly set on the `SearchParameters`. But when you trigger a search from the `SearchBox` the limit provided to the widget is ignored and only the default one is applied (which is `10`). It can produce unexpected results like the one linked inside the issue. The `limitMax` is set to `30` but when you search for some facets since the latter is ignored you only have 10 results which is equal to the `limitMin` and so the button is disabled.
In the following example I search for `<space>` so all the results are retrieve until the limit (`15`).
**Before:**
**After:**
> fix: pass maxFacetHits to SFFV

- packages/react-instantsearch/src/connectors/connectToggle.js
- packages/react-instantsearch/src/connectors/connectToggle.test.js
**Summary**
Close partially #891
> fix(connectToggle): use currentRefinement in metadata instead of the label

- docgen/src/guide/Migration_guide_v5.md
- packages/react-instantsearch/src/connectors/connectMenu.js
- packages/react-instantsearch/src/connectors/connectMenu.test.js
- packages/react-instantsearch/src/connectors/connectRefinementList.js
- packages/react-instantsearch/src/connectors/connectRefinementList.test.js
- packages/react-instantsearch/src/core/InstantSearch.js
- packages/react-instantsearch/src/core/InstantSearch.test.js
- packages/react-instantsearch/src/core/__snapshots__/createInstantSearch.test.js.snap
- packages/react-instantsearch/src/core/createConnector.js
- packages/react-instantsearch/src/core/createConnector.test.js
- packages/react-instantsearch/src/core/createInstantSearch.js
- packages/react-instantsearch/src/core/createInstantSearchManager.js
**Summary**
In 3.3.1 we introduce a warning about the usage of `searchForFacetValues` in favour of `searchForItems` + `withSearchBox` (now renamed `searchable`). Since it's almost a year this PR remove those warnings. Also remove the `searchParameters` on `<InstantSearch>` in favour of `<Configure />`.
> chore: remove deprecation

- docgen/src/guide/Migration_guide_v5.md
- package.json
- packages/react-instantsearch/src/components/CurrentRefinements.js
- packages/react-instantsearch/src/components/CurrentRefinements.test.js
- packages/react-instantsearch/src/components/__snapshots__/CurrentRefinements.test.js.snap
- packages/react-instantsearch/src/widgets/CurrentRefinements.js
- yarn.lock
**Summary**
This PR restore the previous behaviour of `CurrentRefinements`. The component also move for a SFC since we didn't use state & hooks.
**Result**
You can play with the widget on [Storybook](https://deploy-preview-906--react-instantsearch.netlify.com/react-instantsearch/storybook/?selectedKind=CurrentRefinements&selectedStory=with%20RefinementList&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs).
> refactor(CurrentRefinements): revert behaviour changes

- docgen/layouts/common/header.pug
- docgen/src/stylesheets/components/_deprecation-banner.sass
- docgen/src/stylesheets/index.sass
**Summary**
Add a deprecation banner for the current documentation with a link on the next version documentation website.
**Result**
> docs: add deprecation warning

- docgen/src/Getting_started.md
- docgen/src/examples/default-theme/App.js
- docgen/src/examples/e-commerce-infinite/App.js
- docgen/src/examples/e-commerce/App.js
- docgen/src/examples/media/App.js
- docgen/src/guide/Migration_guide_v5.md
- docgen/src/guide/Styling_widgets.md
- packages/react-instantsearch/examples/geo-search/src/index.js
- packages/react-instantsearch/examples/multi-index/src/index.js
- packages/react-instantsearch/examples/next-app/components/head.js
- packages/react-instantsearch/examples/react-router-v3/src/index.js
- packages/react-instantsearch/examples/react-router/src/index.js
- stories/util.js
**Summary**
Remove the import of the `reset` from the documentation & examples, because it's already loaded with the `algolia` theme.
> fix: update CSS import

- packages/react-instantsearch/src/connectors/connectStateResults.js
- packages/react-instantsearch/src/connectors/connectStateResults.test.js
**Summary**
This PR expose the flag `isSearchStalled` through the `connectStateResults` connector.  It could be interesting to have this information for an Autocomplete experience for example. In order to avoid to inject this props everywhere we can compose the connectors.
```js
const AutoCompleteConnected = connectAutoComplete(connectStateResults(AutoComplete));
```
> feat(connectStateResults): expose isSearchStalled

- packages/react-instantsearch/src/connectors/connectRange.js
- packages/react-instantsearch/src/connectors/connectRange.test.js
**Summary**
Close #920 
We provide two different values for the `currentRefinement` in `getProvidedProps` & `getMetadata`. In the first case we "normalize" the value with the range, in the latter we pass the raw values. It can lead to some issues when the user use the `currentRefinement` from the `connectCurrentRefinement` since the values aren't aligned.
**Edit:** At some point we should avoid to "normalize" the `currentRefinement` with the range from the connector. Passing the raw values to the view and let it decide which value to render is more flexible. It's a bit more work to do in the view but the connector will be more reusable (ex: We can implement a "correct" behaviour for `RatingMenu`).
> fix(connectRange): use the same behaviour for currentRefinement in getMetadata

- packages/react-instantsearch/src/components/StarRating.js
- packages/react-instantsearch/src/components/StarRating.test.js
- packages/react-instantsearch/src/components/__snapshots__/StarRating.test.js.snap
- stories/StarRating.stories.js
**Summary**
Fix #674 
In the current implementation we can have sparse rows when the results only return one facet value or if some numeric filters (ex: rating > 3) are applied. Now all the rows under the highest value are filled. Since the v5 is in `beta` I didn't update the tests for avoid to much conflict at the merge. But we should get rid of the `react-test-renderer` for `enzyme`. Same for the component we could move to a SFC after the merge.
**Before:**
**After:**
You can play with the widget on [Storybook](https://deploy-preview-929--react-instantsearch.netlify.com/react-instantsearch/storybook/?selectedKind=StarRating&selectedStory=default&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs).
> fix(StarRatings): always show the stars below

- packages/react-instantsearch/src/components/StarRating.js
- packages/react-instantsearch/src/components/StarRating.test.js
- packages/react-instantsearch/src/components/__snapshots__/StarRating.test.js.snap
**Summary**
With the update of the `StarRating` widget I move for a zero based approach. But the most common approach is to have a 1 based menu. It could have some weird effect when you only set the `max` value on the first load.
**Before**
**After**
> fix(StarRating): move to 1 based instead of 0

- docgen/src/guide/Server-side_rendering.md
- packages/react-instantsearch/examples/next-app/pages/index.js
- packages/react-instantsearch/examples/next-app/tests/index.test.js
- packages/react-instantsearch/src/core/findResultsState.js
**Summary**
I spent all day trying to get SSR working. I finally realized the `this.state` conditional was preventing the SSR search query from being passed to `<InstantSearch>` on the server. 
This PR improves the example to make it more clear what is happening (everything I had to learn the hard way 😄 
It also adds more details to the SSR documentation.
**Result**
I manually verified SSR is working with this code both in my project and in the example project. All tests are passing.
> docs(react): fix react-instantsearch SSR example and improve SSR docs

- packages/react-instantsearch/src/components/SearchBox.js
- packages/react-instantsearch/src/components/SearchBox.test.js
- packages/react-instantsearch/src/components/__snapshots__/Menu.test.js.snap
- packages/react-instantsearch/src/components/__snapshots__/RefinementList.test.js.snap
- packages/react-instantsearch/src/components/__snapshots__/SearchBox.test.js.snap
**Summary**
Fix #926 
In the current implementation we bind the form with a `onReset` handler. But the reset button is also bound with the same callback `onClick`. So when the form is clear by clicking on the button two events are triggered (and so two queries). The first is trigger by the form & the second one by the button. 
We don't need to bind the second handler on the reset button. Because the click will trigger the `reset` event on the form.
**Before**:
**After**:
> fix(SearchBox): avoid to bind click on reset button

- packages/react-instantsearch/src/connectors/connectRange.js
- stories/RangeInput.stories.js
**Summary**
Fix #564 
With the current implementation when we provide a `defaultRefinement` to `connectRange` we must pass an object with both `min` & `max`. There are some cases when we want to pass only a min, max or even an empty object. In the latter case it allow the widget to be "controlled" by the `defaultRefinement`. See #892.
> fix(connectRange): update default refinement propTypes

- packages/react-instantsearch/examples/geo-search/src/App.js
**Summary**
Avoid to render the map when there is no results, otherwise the map doesn't update. Add the `<Pagination>` to illustrate the usage of `Configure` for control the position & reset the page.
On the first example when we click on the map the page is not reset, on the second example the page is reset.
**Before**
**After**
> refactor: GeoSearch example

- packages/react-instantsearch/src/core/indexUtils.js
- packages/react-instantsearch/src/core/indexUtils.test.js
**Summary**
Fix #986 
In a multi index context when a widget is unmount without having be refine it throws an error. The `searchState` is not always in sync with the widgets. On the first render the `searchState` will be an empty object. So when the widget is unmount the lib will try to cleanup the `indices` attribute. Since this attribute is missing the lib throws an error.
In order to avoid the error, before the cleanup we need to ensure that the we are in a multi index context but also that the `indices` attribute exist.
**Before**
**After**
> fix(IndexUtils): avoid throw an error when cleanUp multi index

- packages/react-instantsearch/src/connectors/connectInfiniteHits.js
- packages/react-instantsearch/src/connectors/connectInfiniteHits.test.js
**Summary**
In some cases it might happen that on the first render the `results` is not empty. It will happen if the component has been already mount previously for example. In that the case the widget will return an `undefined` value for this hits because all the condition are `false`. So we need to ensure that on every render the `hits` will be an array.
> fix(connectInfiniteHits): always provide an array for hits

- .travis.yml
**Summary**
By removing this option and disabling the build on push on the Travis UI we are able to run the build only once on **every** PR. Even on PR that don't target `master`. Previously the build wasn't trigger on a PR that didn't target `master`.
> chore(travis): trigger build on every PR

- .travis.yml
**Summary**
By default Travis run the install command for the current package manager (Yarn in our case). Since we do a `yarn boot` after we run the install command twice. This PR replace the default `install` behaviour with `yarn boot`.
**Before**
**After**
> chore(travis): run yarn install only once

- packages/react-instantsearch/src/components/RatingMenu.js
- packages/react-instantsearch/src/core/createConnector.js
- packages/react-instantsearch/src/core/createInstantSearchManager.js
> fix: use lodash version of unsupported Array.{fill, find}

- packages/react-instantsearch/package.json
- yarn.lock
**Summary**
In the move to workspaces I accidentally move React as dependencies. It means that when you install React InstantSearch you also install React, React DOM & React Native. This PR revert this change, in a next version we should add those dependencies as peer.
> fix: revert dependencies to devDependencies

- packages/react-instantsearch/src/connectors/connectRange.js
- packages/react-instantsearch/src/widgets/RangeInput.js
- packages/react-instantsearch/src/widgets/RatingMenu.js
**Summary**
Inside the documentation every widgets that is related to the `connectRange` connector has a section "requirements" about the fact that the value must be a number. But we don't precise that the value must be also declared as `attributeForFaceting`. This PR adds those requirements in:
- `connectRange`
- `RangeInput`
- `RatingMenu`
> docs: add requirements on faceting for range

- packages/react-instantsearch/src/widgets/SearchBox.js
**Summary**
Fixes a typo on the SearchBox page, `form` to `from`
**Result**
N/A
> Docs(SearchBox): fix a small typo

- packages/react-instantsearch/src/connectors/connectRange.js
- packages/react-instantsearch/src/connectors/connectRange.test.js
**Summary**
When calling `refine` through the `connectRange` connector using a max value below 1, the query is made properly and the expected results are returned, but immediate subsequent refinement queries are then called (not through this connector's refine method) that coerce the max and min values into integers, irregardless of the specified precision attribute, and thus return inaccurate results. This is problematic whenever precision is used, but discovered in my use case wherein the desired data contains an attribute with values between 0.1 and 0.9 (this queries for values between 0 and 0, which will result in nothing for my dataset). A slider component using `connectRange` was returning these erroneous results.
This PR resolves the issue by modifying the `connectRange` code to …
> Resolved bug where connectRange connector fails to return results for queries with a max < 1

- packages/react-instantsearch/package.json
- packages/react-instantsearch/src/core/createInstantSearchManager.derived.test.js
- packages/react-instantsearch/src/core/createInstantSearchManager.error.test.js
- packages/react-instantsearch/src/core/createInstantSearchManager.result.test.js
- packages/react-instantsearch/src/core/createInstantSearchManager.test.js
- yarn.lock
This PR upgrades to `algoliasearch@3.27.1` and `algoliasearch-helper@2.26.0`, using the promisified version of `client.search()`. It is necessary for adding `searchClient` support to React InstantSearch.
I had to update the tests with a not-so-great hack because of the way we internally handle search with promises now:
```javascript
Promise.resolve()
.then(() => {})
.then(() => {
// test...
});
```
> feat: Upgrade Client and Helper

- packages/react-instantsearch/src/core/indexUtils.js
- packages/react-instantsearch/src/core/indexUtils.test.js
**Summary**
The PR solve an issue when we try to clean up a index that is not in the searchState. It might happen with a multi indices configuration. You can take look at [this example](https://xp4wll1rlq.codesandbox.io/?doctype=wiki) for more context (switch on the Wikis tabs). 
Now, we make sure that the index exists on the `searchState` before trying to remove the value. You can take a look at [this commit](https://github.com/algolia/react-instantsearch/commit/8770cbd8539ae7552820f28924f753b45d6faba1) for the fix.
I also rewrite a bit the function that handle the clean up. Instead of relying on one function we now have two function dedicated to the single / multi index. I found a bit hard to follow the code with the extended ternaries. I replaced them with early returns.
> fix(indexUtils): avoid throw an error on cleanUp multi indices

- docgen/src/examples/material-ui/App.js
**Summary**
The `onTouchTap` seems to not be supported anymore. I looked at some code and examples I only find samples with `onClick`. 
**Before**
**After**
> fix(material): use onClick instead of onTouchTap

- docgen/layouts/widget.pug
**Summary**
For the `GeoSearch` widget we don't use the generated documentation because the structure of the API is very different (component based). This PR enable the `widget` layout to render content without using the JSDoc data with the help of `external`.
**Result**
Here is how to use the layout with an external documentation file.
```markdown
---
mainTitle: Widgets
title: GeoSearch
layout: widget.pug
category: widget
showInNav: true
external: true
---
Regular Markdown content.
```
> chore(widget): allow external documentation for widgets

- packages/react-instantsearch/package.json
- yarn.lock
**Summary**
It brings back typeahead to Jest!
**Results**
> chore: setup Jest Watch Typeahead

- docgen/src/guide/Styling_widgets.md
Some of the language on the CSS theming page docs was ambiguous and incorrect. 
So these are small grammar changes to aid readability and remove some confusion. 
No code changes to review.
> Upgraded grammar around including reset.css

- scripts/release.sh
**Summary**
The `lerna.json` contains the version of the packages. It should be added during the release process.
> chore(release): add lerna.json to commit

- package.json
**Summary**
We forgot to update the top level package with the release. This PR only fix the version for running the pending PRs on Travis. I will push a fix for the release script just after.
> chore: update react-instantsearch-dom version on top level package

- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-dom/package.json
- packages/react-instantsearch-native/package.json
- packages/react-instantsearch/package.json
**Summary**
When we don't provide an explicit version to `yarn publish` the CLI will prompt the user to select the next version to publish. In our case we already knew which version we want to use. We can use the `--new-version` flag to provide the argument.
> chore(release): explicitly pass a version on Yarn publish

- scripts/release.sh
**Summary**
The release script don't update the dependencies of `react-instantsearch-dom`. This dependencies is required by the stories. This PR update the version of the top level package along with the examples.
> chore(release): update the top level package dependency with the published version

- packages/react-instantsearch-dom/package.json
**Summary**
We forgot to publish the `server` file along with the `dist` folder. This file is required for the SSR when we do the following import:
```js
import { createInstantSearch } from 'react-instantsearch/server'
import { createInstantSearch } from 'react-instantsearch-dom/server' 
```
This PR adds the file to the list of files to publish.
> fix(dom): publish server file

- examples/next/.babelrc
- examples/next/package.json
- examples/next/yarn.lock
**Summary**
With the current configuration the Next application will load the `.babelrc` file that is located at the top level of the project. But Next require a specific configuration to work the extends `next/babel`. You can find more information [in the documentation](https://nextjs.org/docs#customizing-babel-config).
**Before**
**After**
> chore(next): use correct babel configuration

- docgen/src/guide/Custom_connectors.md
> docs(Custom_connectors): use correct shape for `searchResults`

- packages/react-instantsearch-dom/src/index.js
- packages/react-instantsearch-native/src/index.js
**Summary**
In some cases you may want to have a very specific highlighting behaviour. For those use cases you will need to have access to the `highlighTag` set by React InstantSearch (see [Yarn website](https://github.com/yarnpkg/website/blob/2b0f1c8351cd6e338b450d2bb7b87acef0fa9179/js/src/lib/util.js#L107-L111)). You can still override the tags but it can be handy to use the one by default. Previously it was only exported by the `core` package. Now you can access this value directly from DOM & Native.
**Before:**
```jsx
// Only available through `core`
import { HIGHLIGHT_TAGS } from "react-instantsearch-core";
```
**After:**
```jsx
// Now available through `dom`
import { HIGHLIGHT_TAGS } from "react-instantsearch-dom";
// and `native`
import { HIGHLIGHT_TAGS } from …
```
> feat: export highlight tags from DOM / native

- package.json
- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-dom/package.json
- packages/react-instantsearch/package.json
**Summary**
The `bundlesize` report is broken on master because we run the command multiple times (one for each package). The CLI doesn't support this project structure. On the first run it built the report. The others commands might fail but they are not in the report. We also run the commands in parallel so the order is non deterministic. The package that is reported might change between different builds (see below).
This PR solve this issue by managing the `bundlesize` configuration on the root package. 
**Before**
**After**
> chore: fix bundlesize report

- docgen/src/stylesheets/components/_documentation.sass
- docgen/src/widgets/GeoSearch.md
- packages/react-instantsearch-dom-geo/package.json
**Summary**
This is the last part (\o/) of the GeoSearch, the documentation. You can't see the live version yet because the branch is not up to date with `master`. Once it will be the preview will be available. But even without the preview the content remains the same.
- HTML tables rather the markdown because I didn't find a way to have a table without headings. But anyway the style won't be correct if we use the markdown.
- the usage of specific markup for the sub title is intended. It avoid to have a huge space between the sub section of a same component.
[Live preview](https://deploy-preview-1289--react-instantsearch.netlify.com/react-instantsearch/widgets/geosearch)
> feat(geo): add docs [PART-10]

- docgen/src/stylesheets/components/_documentation.sass
- docgen/src/widgets/GeoSearch.md
- packages/react-instantsearch-dom-geo/package.json
- stories/GeoSearch.stories.js
- stories/util.js
- storybook/public/util.css
**Summary**
This is PR adds two stories:
- how to implement communication between the hits & the map
- how to implement an `InfoWindow` with markers
This PR also introduce an option to render a custom Hits component with `<WrapWithHits />`. It's a bit hard to extend the wrapper component with the current implementation. In the upcoming months, it might worth it to have a more coherent showcase cross InstantSearch flavors.
**Result**
You can use them in [Storybook](https://deploy-preview-1236--react-instantsearch.netlify.com/react-instantsearch/storybook/?selectedKind=GeoSearch&selectedStory=with%20InfoWindow&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs).
> feat(geo): add stories [PART-9]

- docgen/src/stylesheets/components/_documentation.sass
- docgen/src/widgets/GeoSearch.md
- packages/react-instantsearch-dom-geo/package.json
- packages/react-instantsearch-dom-geo/src/CustomMarker.js
- packages/react-instantsearch-dom-geo/src/GeoSearch.js
- packages/react-instantsearch-dom-geo/src/Marker.js
- packages/react-instantsearch-dom-geo/src/__tests__/CustomMarker.js
- packages/react-instantsearch-dom-geo/src/__tests__/GeoSearch.js
- packages/react-instantsearch-dom-geo/src/__tests__/Marker.js
- packages/react-instantsearch-dom-geo/src/__tests__/__snapshots__/CustomMarker.js.snap
- packages/react-instantsearch-dom-geo/src/__tests__/utils.js
- packages/react-instantsearch-dom-geo/src/elements/__tests__/createHTMLMarker.js
- packages/react-instantsearch-dom-geo/src/elements/createHTMLMarker.js
- packages/react-instantsearch-dom-geo/src/propTypes.js
- packages/react-instantsearch-dom-geo/src/utils.js
- packages/react-instantsearch-dom-geo/test/mockGoogleMaps.js
- stories/GeoSearch.stories.js
- stories/util.js
- storybook/public/util.css
**Summary**
This is the eighth part of the GeoSearch widget. The PR introduces the ability to attach event handlers on both markers (`<Marker>` & `<HTMLMarker>`). We also moved the options to be top level for `<GeoSearch>`, `<Marker>`, `<HTMLMarker>`. There is no more the `mapOptions` & `options` props. You can pass the option directly to the component.
This PR includes:
- **`utils`**: create some utility functions to register the listeners, filter props, etc...
- **`createHTMLMarker`**: update the `addListener` signature to match the one from Google Maps. It means that we can register & remove events in the same way for both implementations. 
- **`<GeoSearch>`**: remove the `mapOptions` prop, now you can pass the options directly to the component. They will be forward to `<GoogleMaps>`. …
> feat(geo): add Marker & HTMLMarker interactions [PART-8]

- scripts/test.sh
**Summary**
Recently we dropped the condition for Jest on the CI. But now the tests on the CI are incredibly slow. On the [Jest documentation](https://facebook.github.io/jest/docs/en/troubleshooting.html#tests-are-extremely-slow-on-docker-and-or-continuous-integration-ci-server) there is informations about how to address this issue. I picked the second one since we are running on Travis.
- before: https://travis-ci.org/algolia/react-instantsearch/builds/394883907#L545-L634
- after: https://travis-ci.org/algolia/react-instantsearch/builds/394887493#L448-L538
> chore: limit worker on CI for Jest

- test/regressions/tests.js
**Summary**
This PR removes the `GeoSearch` tests in the E2E, because they are too flaky:
- Google Maps is loaded aync
- Tiles of the map are also loaded async
> test(e2e): remove GeoSearch it is too brittle

- packages/react-instantsearch-core/src/core/translatable.js
**Summary**
The `translatable` HoC create a new function for the `translate` prop on each render. This PR create an instance property to avoid to create a new function each time.
> fix(translatable): avoid create a new function on every render

- packages/react-instantsearch-dom-geo/src/GeoSearch.js
- packages/react-instantsearch-dom-geo/src/GoogleMaps.js
- packages/react-instantsearch-dom-geo/src/Provider.js
- packages/react-instantsearch-dom-geo/src/__tests__/GeoSearch.js
- packages/react-instantsearch-dom-geo/src/__tests__/GoogleMaps.js
- packages/react-instantsearch-dom-geo/src/__tests__/Provider.js
- packages/react-instantsearch-dom-geo/src/__tests__/__snapshots__/GeoSearch.js.snap
- packages/react-instantsearch-dom-geo/src/__tests__/__snapshots__/GoogleMaps.js.snap
- stories/GeoSearch.stories.js
**Summary**
This PR allows to use the `GeoSearch` component without the refine functionality. We introduce a new prop `enableRefine` on the `GeoSearch` component. When `false` the map is always controlled by the rest of the search. Each time the results change the map fit the bounding box of the hits.
**Usage**
```jsx
import { GeoSearch, Marker } from "react-instantsearch-dom-maps";
const App = ({ google }) => (
<GeoSearch google={google} enableRefine={false}>
{({ hits }) => (
<Fragment>
{hits.map(hit => <Marker key={hit.objectID} hit={hit} />)}
</Fragment>
)}
</GeoSearch>
);
```
You can also use it on [Storybook](http://deploy-preview-1378--react-instantsearch.netlify.com/react-instantsearch/storybook/?selectedKind=GeoSearch&selectedStory=with%20refine%20disabled&full=0&addons=1&stories=1 …
> feat(geo): enable static map

- packages/react-instantsearch-core/src/connectors/__tests__/connectGeoSearch.js
- packages/react-instantsearch-core/src/connectors/connectGeoSearch.js
- packages/react-instantsearch-core/src/core/__tests__/createConnector.js
- packages/react-instantsearch-core/src/core/createConnector.js
**Summary**
This PR rename the function `shouldUpdate` added for `connectGeoSearch`:
- `shouldUpdate` → `shouldComponentUpdate`
We rename the function because we might introduce a new function called `shouldWidgetUpdate` in a near future. It will avoid confusion about the purpose of each hooks. The latter might solve the issue related to `willReceiveProps` (see #1042).
This change don't have any impact because the only connector that use this functionality is `connectGeoSearch`. The feature is on `master` but not yet released.
> refactor: rename shouldUpdate to shouldComponentUpdate

- .eslintrc.js
- docgen/src/widgets/GeoSearch.md
- packages/react-instantsearch-dom-geo/src/Connector.js
- packages/react-instantsearch-dom-geo/src/Control.js
- packages/react-instantsearch-dom-geo/src/GeoSearch.js
- packages/react-instantsearch-dom-geo/src/Redo.js
- packages/react-instantsearch-dom-geo/src/__tests__/Connector.js
- packages/react-instantsearch-dom-geo/src/__tests__/Control.js
- packages/react-instantsearch-dom-geo/src/__tests__/GeoSearch.js
- packages/react-instantsearch-dom-geo/src/__tests__/Redo.js
- packages/react-instantsearch-dom-geo/src/__tests__/__snapshots__/GeoSearch.js.snap
- stories/GeoSearch.stories.js
**Summary**
With the current implementation of `Redo` & `Control` components we perform a synchronous call to `setState` on `componentDidMount`. It leads to a wasteful re-render right after the components are mount. All the state is managed by the `Connector` component. When a user uses the `Redo` component it implicitly disable the refine on map move. To do so we call a setState callback from the `Redo.componentDidMount`. It trigger the wasteful re-render for the full tree of the `GeoSearch` component.
This PR solves this issue by removing the implicitness when a user uses the `Redo` component. Now we can disable the refinement on map move with a prop on the `GeoSearch` component. Since the value is directly control by the user we don't need to update the state when the components are …
> fix(maps): avoid cascade update

- packages/react-instantsearch-core/src/connectors/__tests__/connectGeoSearch.js
- packages/react-instantsearch-core/src/connectors/connectGeoSearch.js
- stories/places/connector.js
**Summary**
With the current implementation of React InstantSearch the `defaultRefinement` is used when the value **is not present** on the `searchState`. Right now in the places example when we update the location we completely remove the value from the state. On the next render the geo connector pick the `defaultRefinement` since the `boundingBox` is not present on the `searchState`. It means that the map won't move to the new location since we have an active refinement (the default one).
This PR fix this issue by allowing the `boundingBox` to be reset with an empty object rather than removing the value from the `searchState`. All the other connectors behaves like that.
> fix(connectGeoSearch): use empty object as default value

- packages/react-instantsearch-core/src/connectors/__tests__/connectGeoSearch.js
- packages/react-instantsearch-core/src/connectors/connectGeoSearch.js
- packages/react-instantsearch-dom-geo/src/GeoSearch.js
- packages/react-instantsearch-dom-geo/src/__tests__/GeoSearch.js
- packages/react-instantsearch-dom-geo/src/__tests__/__snapshots__/GeoSearch.js.snap
- stories/GeoSearch.stories.js
**Summary**
The `GeoSearch` widget differs from the others because it is not directly wrapped by the connector. It means that we need to pass down the `defaultRefinement` prop to the connector. 
In the connector we have to be careful because we use the `searchState` to retrieve two values `currentRefinement` and `position`. But the latter should not be impacted by the `defaultRefinement`. It means that we need to filter out the `defaultRefinement` prop when retrieve the `position` value.
> fix(maps): add support for default refinement in GeoSearch

- packages/react-instantsearch-dom/src/components/List.js
There is more context in AlgoliaPartners#ps-digital8 channel.
The bug happens when a product is in a level 1 category and a level 2 category.
> HeirachialMenu empty array parent--item

- docgen/src/guide/Server-side_rendering.md
Small typo in the file name for the `App.js` module.
> docs: typo in the file name

- docgen/src/Getting_started_React_native.md
**Summary**
Components are imported from `react-instantsearch-native` throughout the "Getting Started with React Native" documentation. Is there a reason to install `react-instantsearch` (depends on `react-instantsearch-dom`, which I assume is not needed in RN) vs. `react-instantsearch-native`?
**Result**
The installation instructions in the "Getting Started with React Native" documentation have been updated to replace the references to `react-instantsearch` with `react-instantsearch-native`.
> docs(ReactNative): install react-instantsearch-native

- packages/react-instantsearch-dom/src/components/List.js
- packages/react-instantsearch-dom/src/components/__tests__/List.js
- packages/react-instantsearch-dom/src/components/__tests__/__snapshots__/List.js.snap
**Summary**
This PR is a followup of https://github.com/algolia/react-instantsearch/pull/1459. It adds tests to the `List` component (only for the changes not the all component). Now we render the children list only when the `item` contains an non empty array of `items`. The same condition is applied on the class `item--parent`.
**Before**
**After**
Note: The arrow is not present on the latter since we removed the class.
> fix(List): render children list only when required

- examples/autocomplete/package.json
- examples/autocomplete/yarn.lock
- examples/react-native-query-suggestions/package.json
- examples/react-native-query-suggestions/yarn.lock
- examples/react-native/package.json
- examples/react-native/yarn.lock
- examples/react-router-v3/package.json
- examples/react-router-v3/yarn.lock
- examples/react-router/package.json
- examples/react-router/yarn.lock
**Summary**
This PR fix the vulnerabilities in the dependencies for our examples with an update of the Lodash version.
> fix: dependencies vulnerabilities for Lodash in examples

- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-dom-maps/package.json
- packages/react-instantsearch-dom/package.json
- packages/react-instantsearch-native/package.json
- packages/react-instantsearch/package.json
**Summary**
Yarn can now publish without the interactive prompt even without providing the version.
> chore(release): avoid interactive release

- packages/react-instantsearch-dom-maps/src/GoogleMapsLoader.js
- packages/react-instantsearch-dom-maps/src/__tests__/GoogleMapsLoader.jsdom.js
- stories/GeoSearch.stories.js
**Summary**
Recently Google Maps has updated [his release scheme](https://developers.google.com/maps/documentation/javascript/versions). This PR pick the `quarterly` version for the `GoogleMapsLoader` and the `weekly` version for our live example in Storybook.
> fix: pick google maps version

- docgen/src/Getting_started_React_native.md
Fixes an inconsistency between the [React guide](https://community.algolia.com/react-instantsearch/Getting_started.html#install-react-instantsearch), where the "react-instantsearch" is highlighted and the [React-Native guide](https://community.algolia.com/react-instantsearch/Getting_started_React_native.html#install-react-instantsearch-native) where it is not.
>  docs(guide): Highlighted package

- docgen/src/Getting_started.md
In the [Guides Migration Guide - Package import](https://community.algolia.com/react-instantsearch/guide/Migration_guide_package_import.html) it is stated that "The package react-instantsearch is deprecated in favor of react-instantsearch-dom and react-instantsearch-native." while the [guide](https://community.algolia.com/react-instantsearch/Getting_started.html#install-react-instantsearch) still instructs you to install the "react-instantsearch" package and not the "-dom" one.
I also changed the "Note:" part for it to be consistent with the [React-Native](https://community.algolia.com/react-instantsearch/Getting_started_React_native.html) guide.
> docs(guide): Deprecated react-instansearch

- packages/react-instantsearch-dom/src/widgets/ToggleRefinement.js
**Summary**
The PR removes the non-present `count` class name from the documentation.
> docs(Toggle): remove count className

- docgen/assets/js/editThisPage.js
**Summary**
This PR fix the "Edit this page" button for the GeoSearch widget. It's the only one (for now) that doesn't have the doc written with the JSDoc. It's written with a plain Markdown file. I've added a special case for this widget. It's far from the best implem but the doc will move so it's fine for the moment.
> chore(docgen): add special case for edit this page on GeoSearch

- package.json
- packages/react-instantsearch-core/src/connectors/__tests__/connectToggleRefinement.js
- packages/react-instantsearch-core/src/connectors/connectToggleRefinement.js
- packages/react-instantsearch-dom/src/components/ToggleRefinement.js
- packages/react-instantsearch-dom/src/components/__tests__/ToggleRefinement.js
- packages/react-instantsearch-dom/src/components/__tests__/__snapshots__/ToggleRefinement.js.snap
**Summary**
This PR adds `canRefine` & `count` on the provided props of the `connectToggleRefinement` connector. I didn't implement the count on the widget because it will be a breaking change only in the connector. 
The count object has the following shape (see below). When the `currentRefinement` is `false` (unchecked) the user can pick the `unchecked` attribute. It displays the number of results that match the value provided to the Toggle widget. Once it's checked the count displays the total number of results (compute from the facet values).
```ts
type Count = {
checked: number | null;
unchecked: number | null;
};
```
**Changes**:
- the computation of the `SearchParameters` (conjunctiveFacet -> disjunctiveFacet)
- the computation of the `providedProps` (adds `canRefine` & `count`)
- …
> feat(connectToggleRefinement): implement canRefine & count

- packages/react-instantsearch-core/src/connectors/__tests__/connectToggleRefinement.js
- packages/react-instantsearch-core/src/connectors/connectToggleRefinement.js
**Summary**
The connector fix the `canRefine` computation. Previously the computation was only on the facet value count whether the value is refined or not. But when the value is refined we should compute `canRefine` with all the facet values. e.g. The checkbox is selected  and the search returns no results. We still want to be able to unchecked the checkbox if without the filter there are results.
>  fix(toggle): compute canRefine differently when it is refined

- packages/react-instantsearch-core/src/connectors/__tests__/connectToggleRefinement.js
- packages/react-instantsearch-core/src/connectors/connectToggleRefinement.js
**Summary**
This PR fixes an issue when we tried to access the facet values on a `SearchResults` that don't have the expected facet. We can ensure this with `getFacetByName` - this method is deprecated on the helper but we don't have a proper alternative yet.
**Before**
**After**
> fix(toggle): ensure facet is present

- packages/react-instantsearch-core/src/connectors/__tests__/connectCurrentRefinements.js
- packages/react-instantsearch-core/src/connectors/__tests__/connectHierarchicalMenu.js
- packages/react-instantsearch-core/src/connectors/__tests__/connectMenu.js
- packages/react-instantsearch-core/src/connectors/__tests__/connectNumericMenu.js
- packages/react-instantsearch-core/src/connectors/__tests__/connectRefinementList.js
- packages/react-instantsearch-core/src/connectors/connectCurrentRefinements.js
- packages/react-instantsearch-core/src/connectors/connectHierarchicalMenu.js
- packages/react-instantsearch-core/src/connectors/connectMenu.js
- packages/react-instantsearch-core/src/connectors/connectNumericMenu.js
- packages/react-instantsearch-core/src/connectors/connectRefinementList.js
Resolves #1524
**Summary**
There was previously a bug where `canRefine` props were calculated based on untransformed item lists. This caused unintended behaviors such as a ClearRefinements button remaining active when a refinement being ignored via a filter in `transformItems` was present.
**Result**
This PR calculates `canRefine` on the transformed list of items, correcting this behavior.
> Fix: Compute canRefine on the transformed items

- docgen/src/guide/Refreshing_cache.md
- stories/RefreshCache.stories.js
**Summary**
The previous implementation of the examples was relying on the `onSearchStateChange` callback to reset the `refresh` value. But the callback is not triggered when the cache is refreshed. It means that the value remains `true` until the search **actually** change. 
This PR reset the value immediately with the help of the `setState` callback.
> docs(refresh): use setState callback

- .circleci/config.yml
Recently the E2E tests stop working without any changes on the packages dependencies. The test did pass locally but they only failed on CircleCI. It's because Docker image tags are **mutable**. They can change at any time - it appears that one of the image update breaks one of the tools that we use for the E2E tests. To fix this issue we now pin the Docker images with their digest hash. 
Renovate should take care of the update in a dedicated PR.
> https://renovatebot.com/blog/docker-mutable-tags
> chore: pin Docker images

- renovate.json
Renovate change *a lot* since we did this configuration. The default presets cover almost all the configuration that we previously have. I did not use the Algolia one because I don't want to have the scheduler on the repo.
> chore: update Renovate

- package.json
- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.result.js
- packages/react-instantsearch-core/src/core/createInstantSearchManager.js
**Summary**
With the current implementation the value used for [`maxFacetHits`](https://www.algolia.com/doc/api-reference/api-parameters/maxFacetHits) is the default limit of the widget or the user provided value. It's fine for most cases, but it happens that the value provided by the user is higher than 100. This leads to an issue because the Algolia engine only accepts values between 1 - 100. When the value is not in that range the API throws an error.
I chose to fix the issue inside InstantSearch rather than in the helper because it feels odd (to me) to change the value on behalf of the user. The helper can be directly manipulate by users so it makes sense to throw an error if the value is invalid. With InstantSearch it's a bit different we use the helper, they don't have any knowledge …
> fix(sffv): clamp maxFacetHits to the allowed range

- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.derived.js
The previous tests were relying on the internal implementation of the helper (like the `_dispatch` method). We don't have a direct access to it at the moment (it's created by the manager itself). We can mock the import etc... But for the moment I rewrote the test with a mocked client. I don't have to update the implementation only the test.
A possible improvement for the future is to provide the helper as an argument to allow a mocked version easily. It could simplify the tests since the mock part would be closer to the implementation with less indirections.
I've create one PR for each of the manager test file:
- results: https://github.com/algolia/react-instantsearch/pull/1823
- error: https://github.com/algolia/react-instantsearch/pull/1826
- raw: …
> test(createManagerDerived): drop non relevant test + avoid to rely on helper internal

- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.result.js
The previous tests were relying on the internal implementation of the helper (like the `_dispatch` method). We don't have a direct access to it at the moment (it's created by the manager itself). We can mock the import etc... But for the moment I rewrote the test with a mocked client. I don't have to update the implementation only the test.
A possible improvement for the future is to provide the helper as an argument to allow a mocked version easily. It could simplify the tests since the mock part would be closer to the implementation with less indirections.
I've create one PR for each of the manager test file:
- derived: https://github.com/algolia/react-instantsearch/pull/1824
- error: https://github.com/algolia/react-instantsearch/pull/1826
- raw: …
> test(createManagerResults): avoid to rely on helper internal

- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.error.js
- packages/react-instantsearch-core/src/core/createInstantSearchManager.js
The previous tests were relying on the internal implementation of the helper (like the `_dispatch` method). We don't have a direct access to it at the moment (it's created by the manager itself). We can mock the import etc... But for the moment I rewrote the test with a mocked client. I don't have to update the implementation only the test.
A possible improvement for the future is to provide the helper as an argument to allow a mocked version easily. It could simplify the tests since the mock part would be closer to the implementation with less indirections.
I've create one PR for each of the manager test file:
- results: https://github.com/algolia/react-instantsearch/pull/1823
- derived: https://github.com/algolia/react-instantsearch/pull/1824
- raw: …
> test(createManagerError): avoid to rely on helper internal

- packages/react-instantsearch-dom/src/core/__tests__/createInstantSearchServer.js
**Summary**
The PR modernize the tests for `createInstantSearchServer`. The tests follow the convention adopted inside the other PRs for `createInstantSearchManager` (see: #1823, #1824, #1826, #1827 i.e. async / await).
I also updated the implementation of the fake widget. Previously the implem was relying on the `index` attribute of the `searchState`. But this attribute doesn't exist on the "real" state. I've updated it to have tests that are closer to a real use case.
> test(createServer): modernize + fix widget state

- packages/react-instantsearch-core/src/connectors/connectConfigure.js
- packages/react-instantsearch-core/src/connectors/connectGeoSearch.js
- packages/react-instantsearch-core/src/connectors/connectHierarchicalMenu.js
- packages/react-instantsearch-core/src/connectors/connectMenu.js
- packages/react-instantsearch-core/src/connectors/connectNumericMenu.js
- packages/react-instantsearch-core/src/connectors/connectRange.js
- packages/react-instantsearch-core/src/connectors/connectRefinementList.js
- packages/react-instantsearch-core/src/connectors/connectScrollTo.js
- packages/react-instantsearch-core/src/connectors/connectSearchBox.js
- packages/react-instantsearch-core/src/connectors/connectToggleRefinement.js
- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.js
- packages/react-instantsearch-core/src/core/createInstantSearchManager.js
- packages/react-instantsearch-core/src/core/indexUtils.js
- packages/react-instantsearch-dom/src/core/__tests__/createInstantSearchServer.js
- packages/react-instantsearch-dom/src/core/createInstantSearchServer.js
**Summary**
This PR does not introduce new feature, it's a refactor of `createInstantSearchManager`. The logic to detect shared, main and derived parameters was hard to follow. We tried to put name on this logic to help the reader to follow what happens. Now all search parameters are computed inside the same function, previously it was spread across `getSearchParameters` and `search`.
**Changes**
- **`createInstantSearchManager`**: exposes the `getSearchParameters` function to be able to test it. We don't use this function elsewhere inside the codebase but since the logic is "sensitive" it's a viable trade off IMO.
- **`createInstantSearchManager`**: the derived search parameters are now computed directly inside `getSearchParameters`. The main impact is that the shared parameters don't …
> feat(indexId): refactor createInstantSearchManager [PART-3]

- .eslintrc.js
- packages/react-instantsearch-core/src/components/Index.js
- packages/react-instantsearch-core/src/components/InstantSearch.js
- packages/react-instantsearch-core/src/components/__tests__/Index.js
- packages/react-instantsearch-core/src/connectors/connectConfigure.js
- packages/react-instantsearch-core/src/connectors/connectGeoSearch.js
- packages/react-instantsearch-core/src/connectors/connectHierarchicalMenu.js
- packages/react-instantsearch-core/src/connectors/connectMenu.js
- packages/react-instantsearch-core/src/connectors/connectNumericMenu.js
- packages/react-instantsearch-core/src/connectors/connectRange.js
- packages/react-instantsearch-core/src/connectors/connectRefinementList.js
- packages/react-instantsearch-core/src/connectors/connectScrollTo.js
- packages/react-instantsearch-core/src/connectors/connectSearchBox.js
- packages/react-instantsearch-core/src/connectors/connectToggleRefinement.js
- packages/react-instantsearch-core/src/core/__tests__/__snapshots__/createIndex.js.snap
- packages/react-instantsearch-core/src/core/__tests__/createIndex.js
- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.derived.js
- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.js
- packages/react-instantsearch-core/src/core/createIndex.js
- packages/react-instantsearch-core/src/core/createInstantSearchManager.js
- packages/react-instantsearch-core/src/core/indexUtils.js
- packages/react-instantsearch-dom/src/core/__tests__/createInstantSearchServer.js
- packages/react-instantsearch-dom/src/core/createInstantSearchServer.js
- packages/react-instantsearch-dom/src/core/findResultsState.js
- stories/MultiIndex.stories.js
**Summary**
This is the second part of the work to support multi-index search on the same index. The PR introduce a new prop on the `Index` component called `indexId`. This prop is a unique identifier for the index. It has to be unique inside the App to let the manager linked an index, a request and the results. With different identifiers we are able to target the same index with different parameters:
```jsx
<InstantSearch indexName="instant_search" searchClient={searchClient}>
<SearchBox />
<Index indexId="instant_search_default" indexName="instant_search">
<Configure hitsPerPage={3} />
<Hits />
</Index>
<Index indexId="instant_search_apple" indexName="instant_search">
<Configure hitsPerPage={3} filters="brand:Apple" />
<Hits />
</Index>
<Index indexId="instant_search_samsung" …
```
> feat(indexId): rely on indexId rather than indexName [PART-2]

- .eslintrc.js
- packages/react-instantsearch-core/src/components/Index.js
- packages/react-instantsearch-core/src/components/InstantSearch.js
- packages/react-instantsearch-core/src/components/__tests__/Index.js
- packages/react-instantsearch-core/src/connectors/connectConfigure.js
- packages/react-instantsearch-core/src/connectors/connectGeoSearch.js
- packages/react-instantsearch-core/src/connectors/connectHierarchicalMenu.js
- packages/react-instantsearch-core/src/connectors/connectMenu.js
- packages/react-instantsearch-core/src/connectors/connectNumericMenu.js
- packages/react-instantsearch-core/src/connectors/connectRange.js
- packages/react-instantsearch-core/src/connectors/connectRefinementList.js
- packages/react-instantsearch-core/src/connectors/connectScrollTo.js
- packages/react-instantsearch-core/src/connectors/connectSearchBox.js
- packages/react-instantsearch-core/src/connectors/connectToggleRefinement.js
- packages/react-instantsearch-core/src/core/__tests__/__snapshots__/createIndex.js.snap
- packages/react-instantsearch-core/src/core/__tests__/createIndex.js
- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.derived.js
- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.js
- packages/react-instantsearch-core/src/core/createIndex.js
- packages/react-instantsearch-core/src/core/createInstantSearchManager.js
- packages/react-instantsearch-core/src/core/indexUtils.js
- packages/react-instantsearch-dom/src/core/__tests__/createInstantSearchServer.js
- packages/react-instantsearch-dom/src/core/createInstantSearchServer.js
- packages/react-instantsearch-dom/src/core/findResultsState.js
- stories/MultiIndex.stories.js
**Summary**
This is the first part of the work to support multi-index search on the same index. The PR doesn't add any feature to the lib, it's only an internal refactor to allow the support of the same index search. The previous implementation rely on an object like the one below to keep track of which results match which index:
```
{
<indexNameSearchParameters>: <indexNameReactInstantSearchContext>
}
```
Then inside the success handler of the helper we rely on `content.index` to find which index match which content:
https://github.com/algolia/react-instantsearch/blob/07ad0390e1ca21024289b7f38ce7a7d129a00441/packages/react-instantsearch-core/src/core/createInstantSearchManager.js#L174
This solution doesn't work with a multi-index search on the same index because the value of …
> feat(indexId): avoid to rely on the results.index  [PART-1]

- packages/react-instantsearch-core/src/connectors/__tests__/connectPoweredBy.jsdom.js
- packages/react-instantsearch-core/src/connectors/__tests__/connectPoweredBy.node.js
- packages/react-instantsearch-core/src/connectors/connectPoweredBy.js
- packages/react-instantsearch-core/src/core/__tests__/createConnector.js
- packages/react-instantsearch-core/src/core/createConnector.js
- packages/react-instantsearch-dom/src/core/__tests__/createInstantSearchServer.js
**Summary**
The PR changes the way we subscribe to the `store` and `widgetManager`. Until now the subscriptions was done inside the constructor. It leads to some issues with our implementation. 
The first issue occurs with SSR. We have a callback (`onSearchParameters`) to collect and compute search parameters on the server. The callback is called inside `componentWillMount` only when it's provided. The issue is that the constructor is also executed on the server. It means that we trigger at least two requests on the server: one scheduled by the SSR (this is expected) and the others by the manager (this is **not** expected). The latter is not expected because we have no way to "wait" for it and use its results to re-render the App. Only the request schedules by the SSR is required.
The …
> refactor(createConnector): update subscriptions mechanism

- packages/react-instantsearch-core/src/core/__tests__/createConnector.js
- packages/react-instantsearch-core/src/core/createConnector.js
**Summary**
This PR does not introduce any features, it's a rewrite of the tests and small cosmetic changes inside the `createConnector` HOC (like re-order of the methods). We've added some tests to cover the widget API `getSearchParameters`, `getMetadata` and `transitionState`. The last significant change is that we dropped the method `cleanUp`. This method wasn't used since its creation.
> test(createConnector): use consistent test strategies

- packages/react-instantsearch-core/rollup.config.js
- packages/react-instantsearch-core/src/connectors/connectHierarchicalMenu.js
- packages/react-instantsearch-dom-maps/rollup.config.js
- packages/react-instantsearch-dom/rollup.config.js
- packages/react-instantsearch-dom/src/core/createInstantSearchServer.js
- packages/react-instantsearch/rollup.config.js
**Summary**
Rollup is not able to find the named exports from a `cjs` module, because it's actually not "real" named exports. There is an option inside `rollup-plugin-commonjs` to fill the exports but it does fail in some occasions. The PR removes named imports for traditional default imports inside the code built with Rollup (it works for Jest).
> chore: avoid to use fake named import

- babel.config.js
- package.json
- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-core/rollup.config.js
- packages/react-instantsearch-dom-maps/package.json
- packages/react-instantsearch-dom-maps/rollup.config.js
- packages/react-instantsearch-dom/package.json
- packages/react-instantsearch-dom/rollup.config.js
- packages/react-instantsearch-native/package.json
- packages/react-instantsearch/package.json
- packages/react-instantsearch/rollup.config.js
- yarn.lock
**Summary**
This PR leverages the plugin [`@babel/plugin-transform-runtime`](https://babeljs.io/docs/en/babel-plugin-transform-runtime) and [`@babel/runtime`](https://babeljs.io/docs/en/babel-runtime) to avoid to inline the Babel helpers for each files. It rather rely on dependency to re-use them as much as possible.
> chore(babel): setup @babel/runtime [PART-2]

- renovate.json
**Summary**
This PR (should) closes #1925. 
We use `:config:js-lib` preset that overrides the default options with [`:pinOnlyDevDependencies`](https://renovatebot.com/docs/presets-default/#pinonlydevdependencies). For `@types/xxx` dependencies it's easier to have range. It avoids issue with duplicate identifier.
> chore: disable pinned dependencies for types

- examples/autocomplete/package.json
- examples/autocomplete/src/App-Mentions.js
- examples/autocomplete/src/App-Multi-Index.js
- examples/autocomplete/yarn.lock
- examples/geo-search/package.json
- examples/geo-search/yarn.lock
- examples/multi-index/package.json
- examples/multi-index/src/App.js
- examples/multi-index/yarn.lock
- examples/next/components/app.js
- examples/next/components/instantsearch.js
- examples/next/package.json
- examples/next/yarn.lock
- examples/react-router-v3/package.json
- examples/react-router-v3/src/App.js
- examples/react-router-v3/yarn.lock
- examples/react-router/package.json
- examples/react-router/src/App.js
- examples/react-router/yarn.lock
- examples/server-side-rendering/package.json
- examples/server-side-rendering/src/app/index.js
- examples/server-side-rendering/yarn.lock
- scripts/release.sh
- scripts/update-examples.js
**Summary**
This PR move the example on the DOM package. The React Native one haven't been updated yet 
because they does not run anymore. I'll update them separately to a newer version of Expo. 
Now that the packages used in the examples differ we have to update them independently at release time. I've create a basic script to support that. Note that once the example are on the workspaces the script can be removed ~~because Renovate will be in charge of the update~~ because Lerna will take of them.
> chore: move examples to DOM package

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- examples/autocomplete/README.md
- examples/geo-search/README.md
- examples/multi-index/README.md
- examples/next/README.md
- examples/react-native-query-suggestions/Readme.md
- examples/react-native-query-suggestions/app.json
- examples/react-native/README.md
- examples/react-native/app.json
- examples/react-router-v3/README.md
- examples/react-router/README.md
- examples/server-side-rendering/README.md
- packages/react-instantsearch-core/README.md
- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-core/rollup.config.js
- packages/react-instantsearch-core/src/core/createConnector.js
- packages/react-instantsearch-dom-maps/README.md
- packages/react-instantsearch-dom-maps/package.json
- packages/react-instantsearch-dom-maps/rollup.config.js
- packages/react-instantsearch-dom/README.md
- packages/react-instantsearch-dom/package.json
- packages/react-instantsearch-dom/rollup.config.js
- packages/react-instantsearch-dom/src/widgets/RangeSlider.js
- packages/react-instantsearch-native/README.md
- packages/react-instantsearch-native/package.json
- packages/react-instantsearch/README.md
- packages/react-instantsearch/package.json
- packages/react-instantsearch/rollup.config.js
**Summary**
This PR replaces the link to `community.algolia.com` to `algolia.com/doc`. The documentation source code is not updated because it will be removed and inaccessible soon.
> docs: update link community -> algolia/doc

- packages/react-instantsearch-dom-maps/src/GoogleMaps.js
- packages/react-instantsearch-dom-maps/src/__tests__/GoogleMaps.js
**Summary**
This PR drop the usage of the token `GOOGLE_MAPS_CONTEXT`. Now its benefit is very limited because it's only use in two places in the source code. Plus with TypeScript its usage is useless since we have the type checking + autocompletion.
> feat(DOMMaps): expose withGoogleMaps [PART-6]

- packages/react-instantsearch-dom-maps/src/Control.js
- packages/react-instantsearch-dom-maps/src/GoogleMaps.js
- packages/react-instantsearch-dom-maps/src/Marker.js
- packages/react-instantsearch-dom-maps/src/Redo.js
- packages/react-instantsearch-dom-maps/src/__tests__/Control.js
- packages/react-instantsearch-dom-maps/src/__tests__/GoogleMaps.js
- packages/react-instantsearch-dom-maps/src/__tests__/Marker.js
- packages/react-instantsearch-dom-maps/src/__tests__/Redo.js
**Summary**
This PR updates the `Marker` implementation to leverage `withGoogleMaps` HOC.
> feat(DOMMaps): use withGoogleMaps for Marker [PART-3]

- package.json
- packages/react-instantsearch-dom-maps/src/Control.js
- packages/react-instantsearch-dom-maps/src/CustomMarker.js
- packages/react-instantsearch-dom-maps/src/GoogleMaps.js
- packages/react-instantsearch-dom-maps/src/Marker.js
- packages/react-instantsearch-dom-maps/src/Redo.js
- packages/react-instantsearch-dom-maps/src/__tests__/Control.js
- packages/react-instantsearch-dom-maps/src/__tests__/CustomMarker.js
- packages/react-instantsearch-dom-maps/src/__tests__/GoogleMaps.js
- packages/react-instantsearch-dom-maps/src/__tests__/Marker.js
- packages/react-instantsearch-dom-maps/src/__tests__/Redo.js
- packages/react-instantsearch-dom-maps/src/__tests__/__snapshots__/CustomMarker.js.snap
- packages/react-instantsearch-dom-maps/src/__tests__/withGoogleMaps.tsx
- packages/react-instantsearch-dom-maps/src/index.js
- packages/react-instantsearch-dom-maps/src/withGoogleMaps.tsx
- yarn.lock
**Summary**
This PR introduces a new HOC for the maps package. It's now part of the public API because we export this component. The HOC gives access to the `google` object and the `googleMapsInstance` which is the instance of the map. 
Users might want to leverage this to create their own layer on top of our geo search widget. It was already the case with the [heatmap](https://github.com/algolia/react-instantsearch/pull/1721) PR. Now it's possible to build it in user-land.
We choose the HOC over a render prop because it's easier to build a component with lifecycle hooks out of an HOC. With a render prop you have to create a layer to extract the value and provide it to the component that will use it. We can built an HOC out of render prop so if someone ask for it we can refactor the API …
> feat(DOMMaps): expose withGoogleMaps HOC [PART-1]

- packages/react-instantsearch-core/src/core/__tests__/createInstantSearch.js
- packages/react-instantsearch-core/src/core/createInstantSearch.js
- packages/react-instantsearch-dom/src/core/__tests__/createInstantSearchServer.js
- packages/react-instantsearch-dom/src/core/createInstantSearchServer.js
**Summary**
Update the user agent from `react-instantsearch ${version}` to `react (${React.version}); react-instantsearch (${version})`
**Result**
react (16.8.4);react-instantsearch (5.4.0);
PRD here: https://docs.google.com/document/d/18YaTUx6hUuR4_ppVijH3zDyKpUVCASAfZKbKjvWFXjE/edit#heading=h.w2yjrvr134ce
> fix(ua): change the User-Agent to use the new specs lib (version)

- package.json
- packages/react-instantsearch-core/src/connectors/__tests__/connectHitInsights.ts
- packages/react-instantsearch-core/src/connectors/__tests__/connectHits.js
- packages/react-instantsearch-core/src/connectors/__tests__/connectInfiniteHits.js
- packages/react-instantsearch-core/src/connectors/connectHitInsights.ts
- packages/react-instantsearch-core/src/connectors/connectHits.js
- packages/react-instantsearch-core/src/connectors/connectInfiniteHits.js
- packages/react-instantsearch-core/src/index.js
- packages/react-instantsearch-dom/src/index.js
- packages/react-instantsearch-native/src/index.js
- packages/react-instantsearch/connectors.js
- stories/Hits.stories.js
- stories/InfiniteHits.stories.js
**Summary**
This PR adds what's need to add **absolute position** and **queryID** to every hit of connectHits
**Result**
Not much to demonstrate yet but from now on every hit will look like this
```js
{
objectID: "theObjectID",
__position: 42,
__queryID: "theQueryID"
}
```
**Global Outline**
> feat(insights): compute insights data in connectHits [PART-1] 

- package.json
- packages/react-instantsearch-core/src/index.js
- packages/react-instantsearch-core/src/widgets/QueryRuleContext.ts
- packages/react-instantsearch-dom/src/index.js
- packages/react-instantsearch-native/src/index.js
- stories/QueryRuleContext.stories.tsx
- storybook/public/default.css
This **headless** widget sets the rule contexts (called [`ruleContexts`](https://www.algolia.com/doc/api-reference/api-parameters/ruleContexts/)) of the search parameters based on the search state.
```jsx
<QueryRuleContext
trackedFilters={{
genre: () => ['Drama', 'Thriller'],
}}
transformRuleContexts={ruleContexts => {
if (ruleContexts.length === 0) {
return ['ais-genre-Drama'];
}
return ruleContexts;
}}
/>
```
- [Default](https://deploy-preview-2259--react-instantsearch.netlify.com/storybook/?selectedKind=QueryRuleContext&selectedStory=default&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs)
- Widget in InstantSearch.js: algolia/instantsearch.js#3602
>  feat(queryRules): add QueryRuleContext widget [part 4]

- package.json
- packages/react-instantsearch-core/src/connectors/__tests__/connectQueryRules.ts
- packages/react-instantsearch-core/src/connectors/connectQueryRules.ts
- packages/react-instantsearch-core/src/index.js
- packages/react-instantsearch-core/src/widgets/QueryRuleContext.ts
- packages/react-instantsearch-dom/src/index.js
- packages/react-instantsearch-native/src/index.js
- stories/QueryRuleContext.stories.tsx
- storybook/public/default.css
- tslint.json
This adds context-related features to the `connectQueryRules` connector. This allows to set rule contexts (called `ruleContexts`) of the search parameters based on active filters.
Query rules are by default _generic_ when not provided any context. If you provide a context, they become _contextual_ and are only triggered when the context is matched.
The implementation is similar to algolia/instantsearch.js#3617 except that React InstantSearch relies on the search state, not on the helper search parameters. The search state drives the search parameters.
This brings two main limitations:
- **`Configure` doesn't update the search state.** This was made by design. It is therefore not possible to set initial `ruleContexts` based on `Configure`. An alternative is to add an initial `ruleContexts` …
> feat(queryRules): add context features to connector [part 3]

- package.json
- packages/react-instantsearch-core/src/connectors/__tests__/connectQueryRules.ts
- packages/react-instantsearch-core/src/connectors/connectQueryRules.ts
- packages/react-instantsearch-core/src/index.js
- packages/react-instantsearch-core/src/widgets/QueryRuleContext.ts
- packages/react-instantsearch-dom/src/components/QueryRuleCustomData.tsx
- packages/react-instantsearch-dom/src/components/__tests__/QueryRuleCustomData.tsx
- packages/react-instantsearch-dom/src/components/__tests__/__snapshots__/QueryRuleCustomData.tsx.snap
- packages/react-instantsearch-dom/src/index.js
- packages/react-instantsearch-dom/src/widgets/QueryRuleCustomData.tsx
- packages/react-instantsearch-native/src/index.js
- stories/QueryRuleContext.stories.tsx
- stories/QueryRuleCustomData.stories.tsx
- storybook/public/default.css
- storybook/webpack.config.js
- tslint.json
_This is the 2nd PR in the series "Merchandized Query Rules"._
This creates the `QueryRuleCustomData` widget, responsible for showing custom data (`userData`) coming from Query Rules.
[Read RFC →](https://github.com/algolia/instantsearch-rfcs/blob/master/accepted/merchandized-query-rules.md)
```jsx
<QueryRuleCustomData>
{({ items }) =>
items.map(({ banner, title, link }) => {
if (!banner) {
return null;
}
return (
<section key={title}>
<h2>{title}</h2>
<a href={link}>
</a>
</section>
);
})
}
</QueryRuleCustomData>
```
```jsx
<QueryRuleCustomData
transformItems={items => {
if (items.length > 0) {
return items;
}
return [
{
title: 'Kill Bill',
banner: 'http://static.bobatv.net/IMovie/mv_2352/poster_2352.jpg',
link: 'https://www.netflix.com/title/60031236',
},
];
}}
>
{({ items }) => …
```
> feat(queryRules): add QueryRuleCustomData widget [part 2]

- package.json
- packages/react-instantsearch-core/src/connectors/__tests__/connectQueryRules.ts
- packages/react-instantsearch-core/src/connectors/connectQueryRules.ts
- packages/react-instantsearch-core/src/index.js
- packages/react-instantsearch-core/src/widgets/QueryRuleContext.ts
- packages/react-instantsearch-dom/src/components/QueryRuleCustomData.tsx
- packages/react-instantsearch-dom/src/components/__tests__/QueryRuleCustomData.tsx
- packages/react-instantsearch-dom/src/components/__tests__/__snapshots__/QueryRuleCustomData.tsx.snap
- packages/react-instantsearch-dom/src/index.js
- packages/react-instantsearch-dom/src/widgets/QueryRuleCustomData.tsx
- packages/react-instantsearch-native/src/index.js
- stories/QueryRuleContext.stories.tsx
- stories/QueryRuleCustomData.stories.tsx
- storybook/public/default.css
- storybook/webpack.config.js
- tslint.json
_This is the 1st PR in the series "Merchandized Query Rules"._
This creates the `connectQueryRules` connector, responsible for handling Algolia Query Rules features.
[Read RFC →](https://github.com/algolia/instantsearch-rfcs/blob/master/accepted/merchandized-query-rules.md)
The connector passes `userData` array to the widget via a prop named `items`.
For this React implementation, I decided not to keep the name `userData` because at second thought, it makes more sense to apply `transformItems` to something called `items`. I will rename this data in the InstantSearch.js implementation.
Two widgets will be based on this connector:
- `QueryRuleCustomData`
- `QueryRuleContext`
- InstantSearch.js
- [`connectQueryRules`](https://github.com/algolia/instantsearch.js/pull/3597)
- …
> feat(queryRules): add connectQueryRules connector [part 1]

- package.json
- packages/react-instantsearch-core/src/connectors/__tests__/connectQueryRules.ts
- packages/react-instantsearch-core/src/connectors/connectQueryRules.ts
- packages/react-instantsearch-core/src/index.js
- packages/react-instantsearch-core/src/widgets/QueryRuleContext.ts
- packages/react-instantsearch-dom/src/components/QueryRuleCustomData.tsx
- packages/react-instantsearch-dom/src/components/__tests__/QueryRuleCustomData.tsx
- packages/react-instantsearch-dom/src/components/__tests__/__snapshots__/QueryRuleCustomData.tsx.snap
- packages/react-instantsearch-dom/src/index.js
- packages/react-instantsearch-dom/src/widgets/QueryRuleCustomData.tsx
- packages/react-instantsearch-native/src/index.js
- stories/QueryRuleContext.stories.tsx
- stories/QueryRuleCustomData.stories.tsx
- storybook/public/default.css
- storybook/webpack.config.js
- tslint.json
This is the result of all the PRs regarding _Merchandized Query Rules_, that have already been approved. This branch is ready to be merged into `master`.
* feat(queryRules): add connectQueryRules connector [part 1] (#2210)
* feat(queryRules): add QueryRuleCustomData widget [part 2] (#2212)
* feat(queryRules): add context features to connector [part 3] (#2258)
* feat(queryRules): add QueryRuleContext widget [part 4] (#2259)
> feat(queryRules): add Query Rules features

- packages/react-instantsearch-core/src/connectors/connectAutoComplete.js
- packages/react-instantsearch-core/src/connectors/connectHits.js
- packages/react-instantsearch/index.umd.js
These are misc fixes in spelling that didn't exactly fit in a different PR.
> docs(connectors): fix spelling and wording [STEP 8]

- babel.config.js
- package.json
- storybook/webpack.config.js
**Summary**
The propTypes were still present in the production build, making the UMD bundles a bit heavier than needed.
This change adds the [babel-plugin-transform-react-remove-prop-types](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types) plugin to the Babel configuration to remove the propTypes at build time.
With this change we gain a few KB on the final bundles.
**Result**
No visible changes.
> chore(build): remove React propTypes from build

- packages/react-instantsearch-dom/src/components/Panel.js
- packages/react-instantsearch-dom/src/components/PanelCallbackHandler.js
- packages/react-instantsearch-dom/src/components/__tests__/Panel.js
- packages/react-instantsearch-dom/src/components/__tests__/PanelCallbackHandler.js
- packages/react-instantsearch-dom/src/components/__tests__/__snapshots__/Panel.js.snap
- packages/react-instantsearch-dom/src/components/__tests__/__snapshots__/PanelCallbackHandler.js.snap
This migration is fairly straightforward, and has no impact on how the PanelCallbackHandler is used, although it adds a new component in that tree so it can read the context
IFW-485
**Summary**
migrate Panel and PanelCallbackHandler to the new react createContext
**Result**
Nothing visual
**Test plan**
- none of the DOM tests change, except Panel & PanelCallbackHandler
- Storybook still has "noRefinement" class on relevant stories
> chore(context): migrate Panel

- packages/react-instantsearch-dom/src/components/SearchBox.js
This migrates away from deprecated React lifecycles the `SearchBox` component.
I converted the `componentWillReceiveProps` to `componentDidMount`. This resolves in another render (from one to two) when hitting <kbd>Enter</kbd> in `{ searchAsYouType: false }` mode. As discussed IRL, this is a tradeoff that we're ready to accept until it's proven to be an issue.
[Try the stories →](https://deploy-preview-2288--react-instantsearch.netlify.com/storybook/?selectedKind=SearchBox&selectedStory=default)
> fix(compat): upgrade SearchBox lifecycle

- packages/react-instantsearch-dom/src/widgets/RangeSlider.js
- stories/3rdPartyIntegrations.stories.js
This migrates away from deprecated React lifecycles the `RangeSlider` component and its 3rd party integrations.
[See stories →](https://deploy-preview-2290--react-instantsearch.netlify.com/storybook/?selectedKind=Integration%20With%20Other%20Libraries&selectedStory=Airbnb%20Rheostat)
> fix(compat): upgrade RangeSlider lifecycle

- packages/react-instantsearch-dom/src/components/RangeInput.js
- packages/react-instantsearch-dom/src/components/__tests__/RangeInput.js
This migrates away from deprecated React lifecycles the `RangeInput` component.
> fix(compat): upgrade RangeInput lifecycle

- website/examples/tourism/App.js
This migrates away the Tourism example from deprecated React lifecycles.
[See Tourism example →](https://deploy-preview-2305--react-instantsearch.netlify.com/examples/tourism)
> fix(compat): upgrade Tourism example lifecycles

- examples/react-router/src/App.js
- examples/react-router/yarn.lock
This migrates away the React Router example from deprecated React lifecycles.
> fix(compat): upgrade React Router example lifecycles

- examples/react-router-v3/package.json
- examples/react-router-v3/src/App.js
- examples/react-router-v3/yarn.lock
This migrates away the React Router v3 example from deprecated React lifecycles.
> fix(compat): upgrade React Router v3 example lifecycles

- packages/react-instantsearch-core/src/connectors/__tests__/connectQueryRules.ts
- packages/react-instantsearch-core/src/connectors/connectQueryRules.ts
**Summary**
This PR aims to fix an error thrown by the `connectQueryRules` connector. Once we have a value `undefined` inside the `searchState` the connector throws an error. The `searchState` usually does not contains those values but since the URLSync is managed by the user it might happen. The fix ensures that the value is defined.
Note that the implementation could be more "strict". Inside the function `getWidgetRefinements` we have a switch that represents the list of widgets supported by the connector (`refinementList`, `menu`, `range`, ...). We could leverage this information inside the filter function. Right now we check every widget even the non-supported e.g. `query`. The original issue happened because the `query` was `undefined`. We can tackle this into another PR though. The …
> fix(connectQueryRules): avoid to throw an error with undefined values

- packages/react-instantsearch-core/src/core/__tests__/createConnector.js
- packages/react-instantsearch-core/src/core/createConnector.tsx
IFW-671
**Summary**
- move willMount -> constructor
- move willReceiveProps -> didUpdate
This didn't have an impact on more requests, but did cause one more render if you update a prop
**Result**
there's no more old life cycles!
> fix(createConnector): new life cycles

- package.json
- packages/react-instantsearch/index.umd.js
- packages/react-instantsearch/rollup.config.js
**Summary**
Rollup released the support of the [`sideEffects`](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) attribute. Without the support of this option Rollup was not able to effectively tree-shake the module `index.js`. That's why we've introduced a specific module for the UMD build. Now it's not the case anymore! We can drop this dedicated module. I've also adjust the threshold for the bundle size.
> chore(rollup): leverage support of sideEffects

- packages/react-instantsearch-dom/src/components/RatingMenu.js
I replaced this by the `range` utility merged earlier, since it's basically what was needed here.
IFW-741
> refactor(lodash): remove fill

- packages/react-instantsearch-core/src/connectors/connectConfigure.js
Both are arrays & always defined, so it's really enough to find all props in this._props (prevProps), but not in `props`
> refactor(lodash): remove difference

- packages/react-instantsearch-dom/src/core/createInstantSearchServer.js
> refactor(lodash): remove zipWith

- packages/react-instantsearch-core/src/connectors/connectRange.js
lodash.isFinite is just `typeof value == 'number' && nativeIsFinite(value);`, so that's what I implemented
IFW-745
> refactor(lodash): replace isFinite

- packages/react-instantsearch-core/src/core/__tests__/utils.js
- packages/react-instantsearch-core/src/core/utils.ts
The values this function was used for seemed like they can only be arrays or objects to me.
We will only want to empty out "breadth-first", so empty objects will stay in the output if they became empty because of the function itself.
isEmpty here is removed in #2442, and still works the same (but will need a rebase)
The newly added tests also pass with the previous implementation
The function is only used in `onSearchStateChange` as a response to a `cleanUp` (caused by unmount) on a widget
IFW-743
> refactor(lodash): isPlainObject

- packages/react-instantsearch-core/src/core/__tests__/translatable.js
- packages/react-instantsearch-core/src/core/translatable.js
- packages/react-instantsearch-dom/src/components/LinkList.js
- packages/react-instantsearch-dom/src/components/Select.js
replace mostly by item[key] === undefined or hasOwnProperty where rendering `undefined`  could be an option
remaining usages of `has` are removed in #2350
> refactor(lodash): has

- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-core/src/core/createConnector.tsx
- packages/react-instantsearch-dom-maps/src/Connector.js
1. specified function for maps
2. `fast-deep-equal` for createConnector, because it is generic enough for our use case & in a hot path
IFW-735
>  refactor(lodash): replace isEqual

- package.json
- packages/react-instantsearch-core/src/core/__tests__/utils.js
- packages/react-instantsearch-core/src/core/highlight.js
- packages/react-instantsearch-core/src/core/utils.ts
IFW-742
Now accepts (just like lodash.get): 
- `a.b.c`
- `a[5].c`
- `a.5.c` (even if it would be invalid JS, we just won't document this)
does _not_ accept (lodash.get does)
- `a['b.c']`
> refactor(lodash): get

- examples/react-native/src/Rating.js
- package.json
- packages/react-instantsearch-core/src/connectors/connectGeoSearch.js
- packages/react-instantsearch-core/src/connectors/connectNumericMenu.js
- packages/react-instantsearch-core/src/core/utils.ts
- packages/react-instantsearch-dom/src/core/createInstantSearchServer.js
reusing objectHasKeys strategy from the helper
IFW-736
> refactor(lodash): isEmpty

- scripts/release.sh
The release script uses [Lerna](https://github.com/lerna/lerna) to bump the version of the different packages. It's handy because it bumps the package version but also the dependencies between the packages.
The issue is that the `version` command doesn't support filtering like `run` does.  Earlier this year we've introduced private packages into the workspaces (for the website). Because we can't filter them their versions are also incremented when the command is run. It left the project in a dirty state with changes uncommit.
Lerna is able to ignore private package, only when the version is omitted. But Yarn workspaces don't support [a package without a version](https://github.com/yarnpkg/yarn/issues/5936). The package is completely ignored and the dependencies aren't installed.
The …
> build(release): align website version

- packages/react-instantsearch-dom/src/components/VoiceSearch.tsx
- packages/react-instantsearch-dom/src/lib/voiceSearchHelper/__tests__/index.ts
- packages/react-instantsearch-dom/src/lib/voiceSearchHelper/index.ts
**Summary**
At `stop()` of voiceSearchHelper, it calls `dispose()` and `resetState()`.
Because `dispose()` removes event listeners, `end` listener is not called.
So we're setting the `status` as `finished` here.
If we don't do it, it will be still `waiting` or `recognizing`.
Related: https://github.com/algolia/instantsearch.js/commit/84cc9f9cf01b6c550dace5091c8ca770a1d7afb1 from https://github.com/algolia/instantsearch.js/pull/3845
> fix(voiceSearch): fix incorrect status on stop

- packages/react-instantsearch-core/src/core/createInstantSearchManager.js
**Summary**
When updating the `indexName` prop on the `InstantSearch` component, a new search was retriggered by `createInstantSearchManager.updateIndex()` to get the new results. But at the same time the widgets (that are children of `InstantSearch`) where updated and the `onWidgetsUpdate` listener was also retriggering the search.
**Result**
This change removes the `search()` call from `createInstantSearchManager.updateIndex()`, we now only rely on the widgets to retrigger the search if needed.
No new tests were added since `createInstantSearchManager` is mocked in `InstantSearch` test suite and testing that `createInstantSearchManager.updateIndex()` does not trigger a search is testing implementation details. IMHO this should be tested by an integration test. WDYT?
> fix(createInstantSearchManager): do not trigger search on index update

- package.json
- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.derived.js
- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.js
- packages/react-instantsearch-core/src/core/createInstantSearchManager.js
- packages/react-instantsearch-core/src/widgets/Index.tsx
**Summary**
The multi-index support was broken since the migration to the new React context (https://github.com/algolia/react-instantsearch/pull/2178).
This issue is due to multiple small changes:
* The context is now passed though the widget props but some functions in `createInstantSearchManager.js` were still trying to read it from `widget.context`.
* The `indexName` prop is no longer mapped to `indexId` in the `Index` widget if `indexId` is not defined, so the `Index` widget detection was not working correctly anymore.
* The widgets are now registered during the `componentDidMount` (before the change they were registered in the `constructor`), so the registration order is different. And since we're using a `reduce` on the widget list to calculate the `SearchParameters` the end result …
>  fix(createInstantSearchManager): fix multi-index search 

- website/examples/e-commerce/App.css
- website/examples/e-commerce/App.js
- website/examples/e-commerce/App.mobile.css
- website/examples/e-commerce/widgets/NoResults.js
- website/examples/e-commerce/widgets/index.js
This adds the empty state when no hits are returned by the engine. It doesn't change the SFFV no results design.
If no filter are applied, the empty message asks the user to change the query. If there are filters applied, the empty message shows a different message and offers the user to clear the filters.
I added `removeWordsIfNoResults` to `allOptional` so that results are returned most of the time.
- [Preview with only query leading to empty results](https://deploy-preview-2601--react-instantsearch.netlify.com/examples/e-commerce/?query=hellll)
- [Preview with filters leading to empty results](https://deploy-preview-2601--react-instantsearch.netlify.com/examples/e-commerce/?query=helll&page=1&configure%5BattributesToSnippet%5D%5B0%5D=description%3A10&configure%5BsnippetEllipsisText%5D=% …
> chore(examples): add empty results design to e-commerce demo

- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-dom-maps/package.json
- packages/react-instantsearch-dom/package.json
- packages/react-instantsearch-native/package.json
We are now relying on React 16.3 features like `static getDerivedStateFromProps` & `createContext` in the library, which thus won't work with lower versions.
The lowest version of React Native which requires React 16.3 (albeit an alpha) is 0.54.0 (released 5th of March 2018).
> fix(peerDependencies): update React

- package.json
- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-core/src/connectors/__tests__/connectConfigure.js
- packages/react-instantsearch-core/src/connectors/__tests__/connectToggleRefinement.js
- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.derived.js
- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.js
- packages/react-instantsearch-core/src/core/createInstantSearchManager.js
- packages/react-instantsearch-dom/package.json
- yarn.lock
**Summary**
A new `algoliasearch-helper` major version will be released with a few breaking changes ([Migration guide](https://gist.github.com/Haroenv/87b32d4c6dca5deb940ba030bd7a38d8)).
This PR updates `algoliasearch-helper` dependency to use the new major version (released as canary for now) and fix `react-instantsearch` (and its tests) to handle the changes:
* `getQueryParameter` removal (https://github.com/algolia/algoliasearch-helper-js/pull/713)
* Default values removal (https://github.com/algolia/algoliasearch-helper-js/pull/670)
* Emit object instead of an argument list (https://github.com/algolia/algoliasearch-helper-js/pull/699, https://github.com/algolia/algoliasearch-helper-js/pull/700)
> refactor(helper): replace Helper usage

- package.json
- packages/react-instantsearch-dom-maps/package.json
- packages/react-instantsearch-dom-maps/src/Connector.js
This is no longer necessary, since we now require React 16.3 as a peer dependency (#2626)
Result: smaller bundle size :)
> fix(geo): remove lifecycle compat

- stories/InstantSearch.stories.js
- stories/MultiIndex.stories.js
This has been removed in #2339, so no longer works (nor necessary)
Result can be seen in the InstantSearch & MultiIndex stories now being two stories smaller
> docs(stories): remove stories which highlight a custom root

- packages/react-instantsearch-dom-maps/src/Connector.js
issue introduced in #2467
IFW-851
Before the refine function would crash the first time, because isEqualCurrentRefinement was called with undefined as the  first (previous)  refinement. We tried to get the `northWest` from that which throws an error
story: https://deploy-preview-2643--react-instantsearch.netlify.com/storybook/?path=/story/geosearch--default
> fix(geo): check for undefined in isEqual

- packages/react-instantsearch-dom/src/components/Highlighter.js
- packages/react-instantsearch-dom/src/components/__tests__/__snapshots__/Highlighter.js.snap
the reason is that the full value could be duplicate, so we added the index; but the index can't be duplicate within the list.
fixes #2688 for v6
> fix(highlight): switch to index as key

- packages/react-instantsearch-core/src/connectors/__tests__/connectAutoComplete.js
- packages/react-instantsearch-core/src/connectors/connectAutoComplete.js
This was accidentally forgotten when we added the queryID to hits & infinite hits.
The PR is made to `next`, because I was already on that branch, can also make a PR to develop if that's what we want.
IFW-902
**Summary**
you need to be able to retrieve the query ID & absolute position if you are implementing insights. However, you need to nest a StateResults inside connectAutoComplete if you'd want to do this now because the results object isn't exposed.
Absolute position is less important in autocomplete, because you're usually on page 0, but you never know!
**Result**
queryID is injected like in Hits & InfiniteHits
> feat(autocomplete): add queryID & position to provided hits

- packages/react-instantsearch-core/src/core/__tests__/indexUtils.js
- packages/react-instantsearch-core/src/core/indexUtils.js
If someone calls `Object.create(null)` and then adds the expected properties, `hasOwnProperty` will not be available on the object itself. 
fixes #2568 
TODO:
> fix(core): searchState can be non-Object object

- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.derived.js
- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.js
- packages/react-instantsearch-core/src/core/createInstantSearchManager.js
- packages/react-instantsearch-core/src/widgets/InstantSearch.tsx
- packages/react-instantsearch-dom/src/core/__tests__/createInstantSearchServer.js
- packages/react-instantsearch-dom/src/core/createInstantSearchServer.js
- yarn.lock
Response of `findResultsState` (and `resultsState` prop) before:
```js
const resultsState = {
content: SearchResults(state: searchParameters, results: rawResults),
state: searchParameters,
_originalResponse: {
results: rawResults
},
};
```
Note that `SearchResults` has the properties `_rawResults` & `_state`. This means that when we serialize, we are retrieving the original response and state twice.
Then on further searching, I also find that we don't need to serialize the `SearchResults` object at all, since only the raw response and state is used.
I modified this to be more consistent and no longer have duplication:
```js
const resultsState = {
state: searchParameters,
rawResults,
};
```
The `SearchParameters` object gets serialized without issue, as before.
This change in shape has of …
> fix(ssr): avoid duplicate serializing

- packages/react-instantsearch-core/src/widgets/Index.tsx
This loosens the PropType requirement on `IndexWrapper` to allow it to work as it seems to be intended (inferring the `indexId` from the `indexName` during the transition phase).
This fixes #2832.
> chore(index): don't require `indexId` on `IndexWrapper`

- packages/react-instantsearch-dom/src/core/__tests__/createInstantSearchServer.js
- packages/react-instantsearch-dom/src/core/createInstantSearchServer.js
This came up when writing the docs for SSR in v6, index name is required because it isn't set in SearchParameters by InstantSearch
> fix(ssr): add error when no indexName is passed

- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.js
- packages/react-instantsearch-core/src/widgets/InstantSearch.tsx
- packages/react-instantsearch-core/src/widgets/__tests__/InstantSearch.js
**Summary**
This PR fixes an issue where an infinite loop occurs with the controlled mode. The update of the `searchState` was done too late. With V5 the update was done inside `cWRP` but with V6 we move the update inside `cDU`. This change has an impact on when the `searchState` is updated. With `cWRP` it was executed before the `render` of the children, it's not the case anymore with `cDU`. It's done after.
Those children can read the `searchState` provided by the manager. When it's not up to date they alter the previous version of the state. With an `onSearchStateChange` function that relies on the value of `searchState` to add remove parameters, it can lead to infinite loop because the props are changes/reverted at each render.
The fix uses `getDerivedStateFromProps` to keep the …
> fix(InstantSearch): update the searchState on props update

- examples/geo-search/src/App.js
**Summary**
This PR removes the usage of `aroundLatLng` inside the geo-search example. The logic to apply the parameter was present, but the App doesn't expose a way to use it. We don't have to support it since it uses either the IP of the user of the bounding box of the map.
> refactor(example): remove usage of aroundLatLng

- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.js
- packages/react-instantsearch-core/src/core/createInstantSearchManager.js
**Summary**
It appears the search client cache uses string for values `{ [key: string]: string }`.
When hydrating it for preventing a new request on the client, we need to
serialize the value into a JSON string.
fixes: #2828
**Result**
N/A
> fix: serialize cache value on hydrate

- renovate.json
**Summary**
This PR disables `rebaseStalePrs` configuration of renovate.
It's rebasing too many PRs and we cannot fix all the broken tests there.
Let's deal with each PR when we want to merge them.
> chore(renovate): disable rebaseStalePRs

- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-dom/package.json
- yarn.lock
**Summary**
We released while still relying on a canary version of the helper, this means that people would not get patch updates to the helper if we ever did so
Note that also we were relying on two different canary releases, so people likely had two separate versions of the helper in a react-instantsearch-dom bundle.
**Result**
By relying on the real released v3 now, we are sure people will get the latest bug fixes and no longer having duplicate versions of the helper
> fix(helper): rely on stable version of algoliasearch-helper

- package.json
- packages/react-instantsearch-core/src/connectors/__tests__/connectVoiceSearch.js
- packages/react-instantsearch-core/src/connectors/connectVoiceSearch.js
- packages/react-instantsearch-core/src/index.ts
- packages/react-instantsearch-dom/src/components/VoiceSearch.tsx
- packages/react-instantsearch-dom/src/lib/voiceSearchHelper/index.ts
- packages/react-instantsearch-dom/src/widgets/VoiceSearch.ts
- stories/VoiceSearch.stories.tsx
Two new props:
- `additionalQueryParameters: () => Partial<SearchParameters>` (only applied when voice search is mounted)
- `language: string` (iso 639-1), the parameter sent to Algolia will be always the short version
New connector: `connectVoiceSearch`
known limitation: additional query parameters will stay applied as long as the Voice Search widget is mounted, meaning they can cause stale values if you switch input method without unmounting (limitation of the architecture of React InstantSearch)
<small>The connector is written in JS instead of TS, because it's mostly copy-pasted from searchBox, and that would be needless extra work otherwise #hackathon</small>
fixes #2874
> feat(voice): add additionalQueryParameters

- package.json
- packages/react-instantsearch-core/src/connectors/__tests__/connectHitInsights.ts
- packages/react-instantsearch-core/src/connectors/connectHitInsights.ts
**Summary**
Similar to its InstantSearch.js counterpart https://github.com/algolia/instantsearch.js/pull/4231 
When clickAnalytics: true is missing, we fire an error inviting the user to add `clickAnalytics: true`
**Result**
N/A
> feat(insights): show an error when 'clickAnalytics: true' is missing.

- packages/react-instantsearch-core/src/connectors/__tests__/connectNumericMenu.js
- packages/react-instantsearch-core/src/connectors/connectNumericMenu.js
- stories/NumericMenu.stories.js
**Summary**
This PR adds in connectNumericMenu support for numericRefinement `0`. 
There has been complaints about the following not producing a refinement
```jsx
import { NumericMenu } from 'react-instantsearch-dom';
<NumericMenu
attribute="price"
items={[
{ label: '<= 0', start: 0 },
/* ... */
]}
/>
```
**Result**
fixes https://github.com/algolia/react-instantsearch/issues/867
> fix(connectNumericMenu): support numeric refinement 0

- .eslintrc.js
- package.json
- packages/react-instantsearch-core/src/connectors/__tests__/connectConfigureRelatedItems.ts
- packages/react-instantsearch-core/src/connectors/connectConfigureRelatedItems.ts
- packages/react-instantsearch-core/src/core/__tests__/utils.js
- packages/react-instantsearch-core/src/core/utils.ts
- packages/react-instantsearch-core/src/index.ts
- packages/react-instantsearch-core/src/widgets/ConfigureRelatedItems.tsx
- packages/react-instantsearch-dom/src/index.js
- packages/react-instantsearch-native/src/index.ts
- packages/react-instantsearch/connectors.js
- packages/react-instantsearch/dom.js
- packages/react-instantsearch/native.js
- stories/ConfigureRelatedItems.stories.tsx
- storybook/public/util.css
This PR introduces a new set of experimental widgets:
- `EXPERIMENTAL_ConfigureRelatedItems`
- `EXPERIMENTAL_connectConfigureRelatedItems`
Combined with the `Hits` component, these widgets allow to create related items experiences as seen in e-commerce and media use cases:
<details>
<summary>See more examples</summary>
</details>
- [Usage](https://github.com/algolia/react-instantsearch/blob/4ab5da03bc35e2739f9dd0ce6974d55ebb8e1840/stories/ConfigureRelatedItems.stories.tsx)
- [Story](https://deploy-preview-2880--react-instantsearch.netlify.com/storybook/?path=/story/configurerelateditems--default)
- Widgets in InstantSearch.js: algolia/instantsearch.js#4233
- In the story I used `React.memo` for the component not to rerender when the `objectID` doesn't change between renders. Our PropTypes …
> feat(widgets): introduce `ConfigureRelatedItems` as experimental

- package.json
- packages/react-instantsearch-dom/src/core/__tests__/getInsightsAnonymousUserToken.ts
- packages/react-instantsearch-dom/src/core/getInsightsAnonymousUserToken.ts
- packages/react-instantsearch-dom/src/index.js
- packages/react-instantsearch/dom.js
**Summary**
This PR adds getInsightsAnonymousUserToken to `react-instantsearch-dom`.
Related RFC: https://github.com/algolia/instantsearch-rfcs/pull/27
```js
// usage
import { Configure, getInsightsAnonymousUserToken } from 'react-instantsearch-dom';
<Configure
enablePersonalization={true}
userToken={getInsightsAnonymousUserToken()}
/>
```
> feat(insights): add getInsightsAnonymousUserToken helper

- packages/react-instantsearch-core/src/index.ts
- packages/react-instantsearch-dom/src/index.js
- packages/react-instantsearch-native/src/index.ts
- packages/react-instantsearch/dom.js
- packages/react-instantsearch/native.js
The Vue InstantSearch widget is named `ExperimentalConfigureRelatedItems` so this uses the same name for React InstantSearch. The connector name remains `EXPERIMENTAL_connectConfigureRelatedItems`.
> fix(widgets): rename `ExperimentalConfigureRelatedItems` component

- package.json
- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-core/src/connectors/connectInfiniteHits.js
- packages/react-instantsearch-core/src/core/createConnector.tsx
- packages/react-instantsearch-core/src/widgets/InstantSearch.tsx
- yarn.lock
Since React InstantSearch 6, there's an issue with props equality with circular dependencies because of the dep `fast-deep-equal` that was introduced.
Errors like "too much recursion" appeared in browsers (mostly Firefox). More and more users [face this issue](https://discourse.algolia.com/t/instantsearch-conditional-display-too-much-recursion/9555), and I also faced this issue in some apps I built.
I tried upgrading the `fast-deep-equal` dependency to [`^3.1.0`](https://github.com/epoberezkin/fast-deep-equal/releases) which supposedly fixes this, but the build seems broken since I get an error about no default exports exist in this package.
I tried [`react-fast-compare`](https://github.com/FormidableLabs/react-fast-compare) and although it's a bit bigger, it fixes the issue. I tried in …
> fix(deps): fix "too much recursion" error with circular deps

- packages/react-instantsearch-core/src/connectors/__tests__/connectQueryRules.ts
- packages/react-instantsearch-core/src/connectors/connectQueryRules.ts
**Summary**
Fixes #2902 
`searchState.indices` is `undefined` if the widget is initialized with an empty `searchState`, triggering an error during the initial call to `getSearchParameters`.
This PR fix it by adding a check on `searchState.indices` presence before trying to use it.
> fix(connectQueryRules): fix crash when using connectQueryRules in multiple indexes

- examples/e-commerce/widgets/PriceSlider.js
[Hooks cannot be used conditionally](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level). This errored in the newer versions of React.
Closes #2904.
> docs(examples): fix hooks order in e-commerce demo

- packages/react-instantsearch-dom/src/components/SearchBox.js
- packages/react-instantsearch-dom/src/components/__tests__/SearchBox.js
**Summary**
This makes it clear that `inputRef` is part of the api, so it can be used to get a React ref to the search input.  Closes #2910
**Result**
```jsx
<SearchBox
inputRef={input => {this.input = input;}}
/>
focusSearch() {
if(this.input) this.input.focus();
}
```
> feat(SearchBox): provide input element ref

- .codesandbox/ci.json
**Summary**
This PR configures [CodeSandbox CI app](https://github.com/apps/codesandbox). 
When a PR is created, the app prepares a sandbox with the build from the branch.
The comment gets updated with the new url as the PR is updated.
This app doesn't give us a way to install the temporary build on other environments whereas Pika CI does.
In my opinion, we heavily use CodeSandbox and might not need to `yarn install` out of CodeSandbox.
What do you think? If you want to see Pika CI in action, I can open another PR to demonstrate it. Or, if you all are satisfied with CodeSandbox CI, then we can merge this PR 🙂
> chore: add codesandbox ci

- examples/server-side-rendering/src/createApp.js
- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.js
- packages/react-instantsearch-core/src/core/createInstantSearchManager.js
Fixes #2912 
This pull request addresses a bug that is impacting all the customers using React Instantsearch v6.4 with Algoliasearch v4, and having high traffic in their applications.
**Problem**: Internally, on the function `hydrateSearchClient`, the `search` method on the client was being overridden in every request by the previous version of it, eventually causing maximum call stack size exceeded.
**Solution**: This pull request adds a flag to the given client so his search doesn't get override more than once. As the cache as already hydrated before.
**Feedback about this**: The cache hydration system only works when customers are using ` responsesCache: createInMemoryCache(),`. Not sure if that is clear on the docs or for us.
Going to test this pull request a little bit in my side …
> fix(core): fix maximum call stack size exceeded

- packages/react-instantsearch-dom/src/core/__tests__/createInstantSearchServer.js
- packages/react-instantsearch-dom/src/core/createInstantSearchServer.js
**Summary**
We use the `params` of the response given by the Algolia query to craft a cache key for the query done by server-side rendering. However, when the engine has e.g. a query rule which edits the query, this `params` won't be the same as the one actually queried. It will have `query=original...&query=edited`, which means that we should remove the second instance of the query to make the cache not miss
**Result**
When rendering a query which is edited by a query rule, no query gets done frontend. This can be tested by the query `edit_me` on the `instant_search` index.
closes #2941
fixes #2940
> fix(ssr): remove second instance of "query" in the response "params" for SSR

- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.derived.js
- packages/react-instantsearch-core/src/core/createInstantSearchManager.js
Fix https://github.com/algolia/react-instantsearch/issues/2875
So basically,
The index search results are from the `store` and because the new search result added by mutating the results object.
At the `createConnector.tsx`
https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-core/src/core/createConnector.tsx#L342
The `providedProps.allSearchResults` spread into the `Composed` component but since the object `providedProps. allSearchResults` reference did not change. React did not trigger re-render the `Composed` Component.
> fix(core): appending successful index search results by returning new object reference

- packages/react-instantsearch-dom/src/core/__tests__/createInstantSearchServer.js
- packages/react-instantsearch-dom/src/core/createInstantSearchServer.js
**Summary**
A custom client could _not_  return `params`. In this case we can keep `params` as-is instead of trying to `replace`.
**Result**
If `params`  is falsy, it doesn't get transformed. This will also add a  small boost for empty query, although a replace on empty string already probably was very fast.
fix #2958
> fix(ssr): allow "params" to be optional in custom clients

- packages/react-instantsearch-core/src/connectors/__tests__/connectConfigureRelatedItems.ts
- packages/react-instantsearch-core/src/connectors/connectConfigureRelatedItems.ts
This brings support for nested attributes in the [`configureRelatedItems`](https://www.algolia.com/doc/api-reference/widgets/configure-related-items/js/) widget.
Previously, an attribute like `hierarchicalCategories.lvl0` was considered as non-existant because we were accessing it as `hit[hierarchicalCategories.lvl0]`. We now access it with our `getPropertyByPath` util which correctly picks up the attribute.
- [Slack message](https://algolia.slack.com/archives/C2XP6HBKQ/p1597715211006100)
- Fix in InstantSearch.js: algolia/instantsearch.js#4480
> fix(ConfigureRelatedItems): support nested attributes

- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-dom/package.json
**Summary**
Added `react-fast-compare` as a dependency to `react-instantsearch-dom` because it's using it without declaring it and `algoliasearch` as a peer dependency to `react-instantsearch-core` because it inherits it from `algoliasearch-helper` so it needs to be declared
**Result**
Building using Yarn 2's PnP mode succeeds.
Been declared like this for months in https://github.com/yarnpkg/berry/blob/9e5ea238cf4363dd95c43111494db8bfbdb06ccd/.yarnrc.yml#L60-L66
> fix: add missing dependencies

- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.js
- packages/react-instantsearch-core/src/core/createInstantSearchManager.js
- packages/react-instantsearch-dom/src/core/__tests__/createInstantSearchServer.js
- packages/react-instantsearch-dom/src/core/createInstantSearchServer.js
- packages/react-instantsearch-dom/src/widgets/__tests__/InstantSearch.tsx
**Summary**
storing metadata in the first result is confusing, so we change the shape to always be an object; be it multi-index or single index
stacked PR on top of #2973
**Result**
result of findResultsState is now an object with the keys `{ metadata, results }` instead of `results` and metadata being in the first element
> fix(ssr): cleaner result for multi-index

- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-dom-maps/package.json
- packages/react-instantsearch-dom/package.json
- packages/react-instantsearch-native/package.json
[React 17](https://reactjs.org/blog/2020/10/20/react-v17.html) was released a month ago and is compatible with React InstantSearch.
> chore(deps): support React 17 peer dependency

- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-dom-maps/package.json
- packages/react-instantsearch-dom/package.json
**Summary**
We ran into an issue using `react-instantsearch-dom@latest` during local development with regard to the `prop-types@15.5.10` package, which seems to cause the following runtime error:
> Uncaught TypeError: prop_types__WEBPACK_IMPORTED_MODULE_10___default.a.exact is not a function
It looks like the `exact` function was not added until `prop-types@15.6.0` according to the [CHANGELOG](https://github.com/facebook/prop-types/blob/master/CHANGELOG.md#1560), but the [`SearchBox` component of `react-instantsearch-dom` makes use of `PropTypes.exact`](https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-dom/src/components/SearchBox.js#L87) while remaining on `prop-types@15.5.10`.
This manifests as a runtime error during local development when using …
> fix: upgrade prop-types dependency to 15.6+

- packages/react-instantsearch-dom/src/components/VoiceSearch.tsx
- packages/react-instantsearch-dom/src/lib/voiceSearchHelper/__tests__/index.ts
- packages/react-instantsearch-dom/src/lib/voiceSearchHelper/index.ts
**Summary**
Since the module `typescript` has been upgraded to `3.8.3` from #2996, it started to throw new errors regarding SpeechRecognition.
However the correct types are not released yet (https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/924), so this PR copies and pastes the related type and adds some `@ts-ignore` comments to pass the `yarn type-check`.
> fix(types): fix type errors regarding SpeechRecognition

- packages/react-instantsearch-core/src/connectors/__tests__/connectInfiniteHits.js
- packages/react-instantsearch-core/src/connectors/connectInfiniteHits.js
**Summary**
This PR fixes the bug where InfiniteHits stored the cached hits, so clearing cache didn't make any effect.
* related
* https://github.com/algolia/react-instantsearch/issues/2742
* https://github.com/algolia/instantsearch.js/pull/4534
**Result**
InfiniteHits reads cache object everytime and do not store it inside the connector itself.
> fix(infiniteHits): do not cache the cached hits

- package.json
- packages/react-instantsearch-dom/src/components/SmartSort.tsx
- packages/react-instantsearch-dom/src/components/__tests__/SmartSort.tsx
**Summary**
To match the `InstantSearch.js` implementation (https://github.com/algolia/instantsearch.js/pull/4648), we made the `textComponent` and `buttonTextComponent` props optional and provided a default `ButtonTextComponent`
> fix(SmartSort): make `textComponent` and `buttonTextComponent` optional

- ship.config.js
**Summary**
This PR removes `afterPublish` lifecycle hook in the release process because it's not working at the moment. I will create another PR later with working version.
With this script failiing, shipjs also failed to push git tags to the remote (except for that, everything else worked, though).
> chore(release): remove afterPublish script

- packages/react-instantsearch-core/src/connectors/__tests__/connectNumericMenu.js
- packages/react-instantsearch-core/src/connectors/connectNumericMenu.js
**Summary**
I was trying to figure out why our numeric menu with statically defined percentages could not filter on <= 0.5%, which it couldn't.
**Result**
Valid searches not showing up after filtering -> nowhere in the docs is it specified that numeric menu is INTEGER only. 
Simple fix: parseInt -> parseFloat. I'm not missing the radix argument, I doubt others will have different numeric bases than 10.
> feat(connectNumericMenu): add support for floating point values

- packages/react-instantsearch-dom/src/components/List.js
- packages/react-instantsearch-dom/src/components/__tests__/RefinementList.js
**Summary**
Prevent the `RefinementList` component to refine when no items are in the list.
**Reproduction**
- Go to https://react-instantsearch.netlify.app/storybook/iframe.html?id=refinementlist--with-search-inside-items
- Search for anything that renders the `noResults` component
- Press <kbd>enter</kbd>
The component tries to refine even though the list is empty (`Cannot read property 'value' of undefined`), forcing the user to type again to make the facets reappear.
**Result**
Pressing <kbd>enter</kbd> when the list is empty won't do anything.
**Test**
_Following [this comment](https://github.com/algolia/react-instantsearch/pull/3045#issuecomment-855806807), it seems that our storybook don't pick local changes, so you need to change the import in the story._
`yarn storybook`
> fix(RefinementList): prevent searchable component to refine on empty list

- packages/react-instantsearch-dom-maps/src/GoogleMaps.js
- packages/react-instantsearch-dom-maps/src/__tests__/GoogleMaps.js
- packages/react-instantsearch-dom-maps/test/mockGoogleMaps.js
Fix map-zoom after browser-zoom
**Summary**
We encountered an issue with a map and connected list of hits. When browser zoom is set to 125% (or any other value really) and we tried to zoom in the map (with a "+" button), map did zoom in, but immediately zoomed out again. This issue happened on almost (but not every) press of the "+" button in map controls. And it happens in Chrome 90.0.4430.93 on Mac OS X, but was also reported by colleagues on Windows with the same Chrome version.
**Result**
After debugging I figured out that fitBounds() is being called multiple times after "+" button is pressed. Some of these calls were setting bounds to the same value that was already set. By adding a condition around fitBounds() to not execute it unless bounds are different from the current bounds, …
> fix(maps): leave zoom in place if the bounds did not change

- packages/react-instantsearch-dom/src/components/SearchBox.js
- packages/react-instantsearch-dom/src/components/__tests__/SearchBox.js
- packages/react-instantsearch-dom/src/widgets/SearchBox.js
**Summary**
This PR adds an `inputId` prop to the `SearchBox` component, in order to associate the element with a `label`
This PR is a continuation of the work from #3068 
**Result**
1. Ran `npm link` in `packages/react-instantsearch-dom` and root directory to sync package update
2. Added an `inputId` to the default `SearchBox` Storybook story
3. Confirmed the `inputId` prop appears in DOM as an `id` attribute on `input`
> fix(SearchBox): Adds `inputId` prop to `SearchBox`

- packages/react-instantsearch-dom/src/components/Select.js
- packages/react-instantsearch-dom/src/components/SortBy.js
- packages/react-instantsearch-dom/src/components/__tests__/SortBy.js
- packages/react-instantsearch-dom/src/widgets/SortBy.js
- stories/SortBy.stories.js
**Summary**
This PR adds an `id` prop to the `SortBy` component, in order to associate the element with a `label`. To accomplish this, the PR also adds an `id` prop to the `Select` component
**Result**
1. Ran `npm link` in `packages/react-instantsearch-dom` and root directory to sync package update
- Is there a better way to do this? `yarn watch` wasn't updating the component from the package
2. Added an `id` to the default `SortBy` Storybook story
3. Confirmed the `id` prop appears in DOM
**Questions**
- Where do we update the documentation for `SortBy` on the Algolia website to include the new `id` prop?
> fix(SortBy): Adds `id` prop to `SortBy`, `Select` components

- packages/react-instantsearch-dom/src/components/HitsPerPage.js
- packages/react-instantsearch-dom/src/components/Select.js
- packages/react-instantsearch-dom/src/components/__tests__/HitsPerPage.js
- packages/react-instantsearch-dom/src/widgets/HitsPerPage.js
**Summary**
This PR adds an `id` prop to the `HitsPerPage` component, in order to associate the element with a `label`. To accomplish this, the PR also adds an `id` prop to the `Select` component
This PR is a continuation of the work from #3068 
**Result**
1. Ran `npm link` in `packages/react-instantsearch-dom` and root directory to sync package update
2. Added an `id` to the default `HitsPerPage` Storybook story
3. Confirmed the `id` prop appears in DOM
> fix(HitsPerPage): Adds `id` prop to `HitsPerPage`, `Select` components

- packages/react-instantsearch-dom/src/components/MenuSelect.js
- packages/react-instantsearch-dom/src/components/__tests__/MenuSelect.js
- packages/react-instantsearch-dom/src/widgets/MenuSelect.js
**Summary**
This PR adds an `id` prop to the `MenuSelect` component, in order to associate the element with a `label`
This PR is a continuation of the work from #3068 
**Result**
1. Ran `npm link` in `packages/react-instantsearch-dom` and root directory to sync package update
2. Added an `id` to the default `MenuSelect` Storybook story
3. Confirmed the `id` prop appears in DOM
> fix(MenuSelect): Adds `id` prop to `MenuSelect`

- packages/react-instantsearch-core/src/connectors/__tests__/connectHierarchicalMenu.js
- packages/react-instantsearch-core/src/connectors/__tests__/connectMenu.js
- packages/react-instantsearch-core/src/connectors/__tests__/connectRefinementList.js
- packages/react-instantsearch-core/src/connectors/connectHierarchicalMenu.js
- packages/react-instantsearch-core/src/connectors/connectMenu.js
- packages/react-instantsearch-core/src/connectors/connectRefinementList.js
- packages/react-instantsearch-core/src/core/indexUtils.js
If `facetOrdering` is enabled (the default behaviour), before the default sortBy is used, the result from renderingContent.facetOrdering.values is first checked. If that's present, it will be used to sort the items.
You can still change that ordering afterwards with the existing transformItems, so if you are sorting in transformItems, you actually override the sorting done by facet ordering, and won't see the effect. To use facetOrdering, you thus need to remove any sorting done in transformItems.
If there is a facetOrdering present in the index, but you don't want to use it for a certain widget, you need to explicitly pass `facetOrdering: false` to the widget or connector
References:
- [RFC 45](https://github.com/algolia/instantsearch-rfcs/blob/master/accepted/flexible-facet-values.md)
- …
> feat(facets): add a new option "facetOrdering" to Menu, RefinementList & HierarchicalMenu

- packages/react-instantsearch-core/src/widgets/DynamicWidgets.tsx
- packages/react-instantsearch-core/src/widgets/__tests__/DynamicWidgets.test.tsx
This was brought up by @Shipow as a possible use case: you want to have dynamic widgets, but don't know what the facets could be in advance.
The fallbackWidget prop caters for this use case, allowing you to special-case some widgets (like hierarchical for example), but use the same widget for the rest.
```jsx
const Defaults = () => (
<ExperimentalDynamicWidgets fallbackComponent={RefinementList}>
<HierarchicalMenu attributes={['hierarchy', 'subHierarchy']} />
</ExperimentalDynamicWidgets>
);
const Custom = () => (
<ExperimentalDynamicWidgets
fallback fallbackComponent={({ attribute }) => <CustomWidget facet={attribute} />}
>
<HierarchicalMenu attributes={['hierarchy', 'subHierarchy']} />
</ExperimentalDynamicWidgets>
);
```
1. fallback
2. fallbackWidget
2. fallbackComponent
3. function as …
> feat(DynamicWidgets): add fallbackComponent

- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.js
- packages/react-instantsearch-core/src/core/createInstantSearchManager.js
This is required, as transitionState gets called with the return of value in a createURL. 
Without this fix, an error happens if there is:
-  dynamic configure
- currentRefinements + createURL
- something is refined
- SSR
- first client render
The error is `TypeError: Cannot read properties of undefined (reading 'configure')` as the transitionState argument is given the result of createURL/currentRefinements, but that's undefined instead of an object. The state isn't actually transitioned, so an empty object works as a solution.
Here's a sandbox showing the existing state: https://codesandbox.io/s/charming-williamson-bifbf?file=/components/app.js:1158-1167
And that same sandbox fixed in this PR: https://codesandbox.io/s/bold-brook-gdyri
> fix(server side rendering): return a value from mock currentRefinement/metadata

- packages/react-instantsearch-core/src/connectors/__tests__/connectPoweredBy.jsdom.js
- packages/react-instantsearch-core/src/connectors/connectPoweredBy.js
**Summary**
Creating a Powered By component in my React Native app results in an error due to the attempt to access window.location.hostname
**Result**
```
yarn jest packages/react-instantsearch-core/src/connectors/__tests__/connectPoweredBy.jsdom.js
yarn run v1.18.0
$ /Users/foush/Code/al/node_modules/.bin/jest packages/react-instantsearch-core/src/connectors/__tests__/connectPoweredBy.jsdom.js
PASS  packages/react-instantsearch-core/src/connectors/__tests__/connectPoweredBy.jsdom.js
connectPoweredBy
✓ provides the correct props to the component (1 ms)
✓ handles react native environment in window without location object (1 ms)
Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        0.877 s
Ran all test suites matching …
```
> Address native environment having a Window object but no location object

- lerna.json
The [`useWorkspaces`](https://github.com/lerna/lerna/tree/main/commands/bootstrap#--use-workspaces) option enables better integration with Yarn Workspaces.
It is [required for Renovate](https://github.com/renovatebot/renovate/issues/7438#issuecomment-739755253) to use the `yarn` command instead of `lerna`.
- algolia/docsearch#1158
- algolia/autocomplete#807
> chore(lerna): add `useWorkspaces` option

- lerna.json
With the `useWorkspaces` option, Lerna relies on Yarn Workspaces defined in the root `package.json`.
> chore(lerna): rely on Yarn Workspaces

- examples/hooks/App.css
- examples/hooks/App.tsx
- examples/hooks/components/SortBy.tsx
- examples/hooks/components/index.ts
- packages/react-instantsearch-hooks/src/__tests__/useSortBy.test.tsx
- packages/react-instantsearch-hooks/src/index.ts
- packages/react-instantsearch-hooks/src/useSortBy.ts
This adds `useSortBy` to our Hooks collection.
This hook is a bridge to `connectSortBy`.
```jsx
function SortBy(props) {
const { currentRefinement, options, refine } = useSortBy(props);
return <div>{/* ... */</div>;
}
return (
{/* ... */}
<SortBy items={[
{ label: 'Relevance', value: '...' },
// ...
]} />
);
}
```
> feat(hooks): introduce `useSortBy`

- packages/react-instantsearch-hooks/README.md
**Summary**
Adds an API documentation for `useSortBy` in the README file for react-instantsearch-hooks.
> docs(hooks): add doc for useSortBy hook

- examples/hooks/components/RefinementList.tsx
- examples/hooks/components/SearchBox.tsx
The components from our Hooks example always triggered a query change on mount. This triggered additional renders, network requests, and created some routing issues by resetting the query.
> docs(hooks): update query on change only

- .circleci/config.yml
- examples/hooks/App.tsx
- examples/hooks/components/QueryRuleContext.tsx
- examples/hooks/components/QueryRuleCustomData.tsx
- examples/hooks/components/index.ts
- package.json
- packages/react-instantsearch-hooks/README.md
- packages/react-instantsearch-hooks/src/__tests__/useQueryRules.test.tsx
- packages/react-instantsearch-hooks/src/index.ts
- packages/react-instantsearch-hooks/src/useQueryRules.ts
- test/mock/createAPIResponse.ts
- yarn.lock
This adds `useQueryRules` to our Hooks collection. Similarily to the current API, the example immplements
- `QueryRuleContext`: which applies ruleContexts based on filters to trigger context dependent Rules.
- `QueryRuleCustomData`:  which displays custom data from Rules.
This hook is a bridge to `connectQueryRules`.
Example of a simple banner
```js
export function Banner(props) {
const { items } = useQueryRules({
trackedFilters: {
genre: () => ['Comedy', 'Thriller'],
}
});
return <>
{ items.map(item => <a href={item.link}>{item.title}</a>) }
</>
}
return (
<Banner />
{/* ... */}
);
}
```
> feat(hooks): introduce `useQueryRules`

- packages/react-instantsearch-hooks/src/utils/__tests__/invariant.test.ts
- packages/react-instantsearch-hooks/src/utils/invariant.ts
Our `invariant` util used to throw with a specified error message in development only, and keep the flow going without throwing in production. This is a dangerous behavior to have different flows in development and in production.
This diff now also throws in production, but with a tiny generic error message to keep the bundle size lite. In the future, we'll be able to implement our error strategy with error redirects (similar to React or Next.js) in this invariant.
For reference, [`tiny-invariant`](https://github.com/alexreardon/tiny-invariant) and other projects throw in both environments, only the error messages differ.
I added the production path in the test so that we're able to test that `invariant` acts as expected in production. `__DEV__` is `true` by default when running the test, …
> fix(hooks): throw invariant violations in production

- packages/react-instantsearch-hooks/README.md
**Summary**
The documentation had a case of bad copy/paste, it's now cured.
> docs(react-instantsearch-hooks): fix typo

- examples/hooks/App.css
- examples/hooks/App.tsx
- examples/hooks/components/CurrentRefinements.tsx
- examples/hooks/components/index.ts
- package.json
- packages/react-instantsearch-hooks/src/__tests__/useCurrentRefinements.test.tsx
- packages/react-instantsearch-hooks/src/index.ts
- packages/react-instantsearch-hooks/src/useCurrentRefinements.ts
This introduces the `useCurrentRefinements` hook.
For the example, I've used the [specs](https://github.com/algolia/instantsearch-specs) and the existing [`CurrentRefinements`](https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-dom/src/components/CurrentRefinements.js) widget for inspiration. However I've used one list item per refinement, which looked clearer to me UI-wise.
We can do a pass on responsiveness and refine the global UI at the end.
Documentation PR is open [here](https://github.com/algolia/doc/pull/6488).
> feat(hooks): introduce useCurrentRefinements

- .eslintrc.js
- examples/hooks-ssr/.babelrc
- examples/hooks-ssr/.gitignore
- examples/hooks-ssr/README.md
- examples/hooks-ssr/package.json
- examples/hooks-ssr/src/App.js
- examples/hooks-ssr/src/browser.js
- examples/hooks-ssr/src/components/Configure.js
- examples/hooks-ssr/src/components/ControlledSearchBox.js
- examples/hooks-ssr/src/components/Highlight.js
- examples/hooks-ssr/src/components/Hits.js
- examples/hooks-ssr/src/components/Pagination.js
- examples/hooks-ssr/src/components/RefinementList.js
- examples/hooks-ssr/src/components/SearchBox.js
- examples/hooks-ssr/src/components/index.js
- examples/hooks-ssr/src/cx.js
- examples/hooks-ssr/src/searchClient.js
- examples/hooks-ssr/src/server.js
- examples/hooks-ssr/webpack.config.js
- examples/hooks/package.json
- package.json
- packages/react-instantsearch-hooks-server/README.md
- scripts/test-examples.js
- yarn.lock
This adds a SSR example to the SSR Hooks API introduced in #3221.
Note that the `components` folder is taken from https://github.com/algolia/react-instantsearch/tree/11027596c29e9958eba5cc590d6636b1634d0a0d/examples/hooks/components so you can safely ignore it during review.
- algolia/instantsearch-rfcs#58
- #3221
> docs(hooks): add SSR example

- CHANGELOG.md
- ship.config.js
This removes the examples update after release in an attempt at making the release script work. It's been broken for months and messes up our tags and releases.
I want to release the next version without this step to make sure that this is the culprit. Then, we should be able to rely on the monorepo feature instead of manually updating the examples.
> chore(release): remove examples update after release

- examples/hooks-ssr/package.json
This updates the SSR Hooks example package name to follow the same pattern as the Hooks example name.
> docs(hooks): update SSR example package name

- package.json
These dependencies were mistakenly introduced in c772401bd5373264967ee053276b22f1f54f096b by our script to update example dependencies.
> chore(deps): remove lib dependencies from root package

- .eslintrc.js
- packages/react-instantsearch-hooks-server/src/__tests__/getServerState.test.tsx
- packages/react-instantsearch-hooks-server/src/getServerState.tsx
- ship.config.js
This uses the same Ship.js and ESLint config in Hooks Server as in the Hooks package.
> chore(hooks-server): use same Ship.js and ESLint config as Hooks

- ship.config.js
Similar to #3173.
We update the Hooks and Hooks Server package dependencies in the SSR example because Lerna doesn't and releasing fails because the Hooks Server package has not yet been released on npm.
> chore(release): update Hooks Server example dependencies on release

- examples/hooks/App.tsx
- examples/hooks/components/NumericMenu.tsx
- examples/hooks/components/index.ts
- package.json
- packages/react-instantsearch-hooks/src/__tests__/useNumericMenu.test.tsx
- packages/react-instantsearch-hooks/src/index.ts
- packages/react-instantsearch-hooks/src/useNumericMenu.ts
This adds `useNumericMenu` to our Hooks collection.
This hook is a bridge to `connectNumericMenu`.
```jsx
function NumericMenu(props) {
const { items, refine } = useNumericMenu(props);
return /* ... */;
}
return (
<NumericMenu
attribute="price"
items={[
{ label: 'All' },
{ label: 'Less than 500$', end: 500 },
{ label: 'Between 500$ - 1000$', start: 500, end: 1000 },
{ label: 'More than 1000$', start: 1000 },
]}
/>
{/* ... */}
);
}
```
> feat(hooks): introduce `useNumericMenu`

- .eslintrc.js
- packages/react-instantsearch-core/src/core/translatable.js
- packages/react-instantsearch-hooks-server/src/getServerState.tsx
**Summary**
async/await adds the really big regenerator polyfill, that we don't really need. It also adds an eslint rule to make sure we don't use it again in the future, along with some other (not used so far) syntax
**Result**
no async/await outside inside the real source code (tests/examples are allowed)
> refactor(hooks-server): no longer use async/await

- examples/hooks/App.tsx
**Summary**
In the `hooks` example, you can't clear the current refinement for the `HierarchicalMenu` widget.
> fix(hooks): clear current refinement for hierarchical menu not working

- package.json
- packages/react-instantsearch-core/src/connectors/__tests__/connectDynamicWidgets.js
- packages/react-instantsearch-core/src/connectors/connectDynamicWidgets.ts
- stories/DynamicWidgets.stories.js
FX-622
**Summary**
The default additional search parameters of `{ facets: ['*'], maxValuesPerFacet: 20 }` prevents an extra network request when widgets mount/unmount, as both queries will be identical, and thus cached.
If a refinement is set, this still results in two network requests, as the refinements can't be applied before it's known if the widget should be mounted.
**Result**
When dynamic widgets is used without an explicit configure widget with `facets: ['*']` and `maxValuesPerFacet: highestLimit` an extra network request happens on load, which has a negative impact on performance. With the new additional parameters default value, widgets mounting or unmounting no longer require a separate network request
Two new parameters are added to `connectDynamicWidgets` and …
> feat(dynamicWidgets): send facets * and maxValuesPerFacet by default

- examples/hooks/components/CurrentRefinements.tsx
- examples/hooks/components/HierarchicalMenu.tsx
- examples/hooks/components/Menu.tsx
- examples/hooks/components/Pagination.tsx
- examples/hooks/isModifierClick.ts
This adds support for the `href` HTML attribute on the `<Pagination>` links.
Prior to this PR, there was an accessibility issue because the `href` property wasn't computed, and it wasn't possible to open the page in a new link when <kbd>⌘</kbd> + Click.
> docs(hooks): support `href` prop in `<Pagination>`

- package.json
- packages/react-instantsearch-hooks-server/package.json
- packages/react-instantsearch-hooks/package.json
- scripts/prepare-cjs.sh
- test/module/packages-are-cjs-modules.cjs
**Summary**
opposite of making sure esm is fully esm, the cjs also needs to be fully cjs.
**Result**
> fix(hooks): allow importing via require

- examples/hooks-ssr/src/App.js
- examples/hooks-ssr/src/components/Configure.js
- examples/hooks/App.tsx
- examples/hooks/components/index.ts
- packages/react-instantsearch-hooks/src/components/Configure.tsx
- packages/react-instantsearch-hooks/src/components/__tests__/Configure.test.tsx
- packages/react-instantsearch-hooks/src/components/__tests__/Index.test.tsx
- packages/react-instantsearch-hooks/src/index.ts
This adds the renderless `<Configure>` to our components collection.
This component is based on `useConfigure()`.
```jsx
import { InstantSearch, Configure } from 'react-instantsearch-hooks';
return (
<Configure hitsPerPage={40} />
{/* ... */}
);
}
```
> feat(hooks): introduce `<Configure>`

- packages/react-instantsearch-hooks/src/__tests__/compat.test.tsx
- packages/react-instantsearch-hooks/src/components/__tests__/Index.test.tsx
- packages/react-instantsearch-hooks/src/lib/invariant.ts
- packages/react-instantsearch-hooks/src/lib/useIndexContext.ts
- packages/react-instantsearch-hooks/src/lib/useInstantSearchContext.ts
This saves a couple of bytes on the production bundle by throwing via invariants when Context conditions are not met.
> refactor(hooks): use invariant in context Hooks

- examples/hooks-next/components/SearchBox.tsx
- examples/hooks-ssr/src/components/SearchBox.js
- examples/hooks/components/SearchBox.tsx
This removes the `useEffect()` in the `<SearchBox>`  responsible for synchronizing the InstantSearch.js internal query to the `<SearchBox>` React state because it overrides the DOM value concurrently when typing fast.
This is temporary before releasing the library and documentation, until we find an alternative.
> docs(examples): remove query state sync in `<SearchBox>`

- packages/react-instantsearch-core/src/core/__tests__/createConnector.js
- packages/react-instantsearch-core/src/core/createConnector.tsx
- packages/react-instantsearch-core/src/widgets/Index.tsx
- packages/react-instantsearch-core/src/widgets/InstantSearch.tsx
- packages/react-instantsearch-dom/src/core/__tests__/createInstantSearchServer.js
- packages/react-instantsearch-dom/src/core/createInstantSearchServer.js
**Summary**
Same as #3259, but for React InstantSearch core, not hooks.
We render twice in the case that dynamic widgets are discovered
**Result**
- no search request when there's a refinement applied using server side rendering
- no flash of non-filtered content
- https://codesandbox.io/s/keen-moon-wdxou fixed by this PR (select a refinement and reload)
> feat(server): load data twice in the case of dynamic widget usage

- package.json
- ship.config.js
- yarn.lock
This fixes our release process by updating all our lib dependencies (including the ones in our examples) on release. The fix is to rely on Lerna to update the deps, and not Ship.js.
You can see #3273 that shows the output of this PR.
> chore(release): bump all lib deps on release

- examples/hooks-ssr/src/components/SearchBox.js
- examples/hooks/components/SearchBox.tsx
This updates the Hooks `<SearchBox>` examples to synchronize the InstantSearch internal query with the component's React state.
The difference from #3264 is that before synchronizing the state, we check if the `<input>` is the active element. This avoids concurrency issues when typing fast, while still supporting scenarios like "Back button". ([Reference to similar code in InstantSearch.js](https://github.com/algolia/instantsearch.js/blob/7dcec376a36b42400f2b83bed9807c763303c058/src/components/SearchBox/SearchBox.tsx#L100)).
> docs(examples): sync InstantSearch query with React state

- packages/react-instantsearch-hooks/src/lib/warn.ts
This slightly improves the DX by updating our `warning()` util to throw an error and catch it immediately as a convenience so that you can find the source of the warning that appears in the console by enabling "Pause on exceptions" in the JavaScript debugger.
A similar strategy is used in:
- [React](https://github.com/facebook/fbjs/blob/865675200037a867727c7361ff06be772effe169/packages/fbjs/src/__forks__/warning.js#L28-L33)
- [React Router](https://github.com/remix-run/react-router/blob/f16c5490dfa75f15dcfb86d2a981a7c58a9d1a33/packages/react-router/index.tsx#L27-L35)
- [Automatically pause on any exception](https://developers.google.com/web/updates/2015/05/automatically-pause-on-any-exception)
> fix(hooks): enable pause on exceptions on warning

- packages/react-instantsearch-hooks/src/components/Configure.tsx
- packages/react-instantsearch-hooks/src/components/DynamicWidgets.tsx
- packages/react-instantsearch-hooks/src/connectors/useBreadcrumb.ts
- packages/react-instantsearch-hooks/src/connectors/useClearRefinements.ts
- packages/react-instantsearch-hooks/src/connectors/useConfigure.ts
- packages/react-instantsearch-hooks/src/connectors/useCurrentRefinements.ts
- packages/react-instantsearch-hooks/src/connectors/useDynamicWidgets.ts
- packages/react-instantsearch-hooks/src/connectors/useHierarchicalMenu.ts
- packages/react-instantsearch-hooks/src/connectors/useHits.ts
- packages/react-instantsearch-hooks/src/connectors/useHitsPerPage.ts
- packages/react-instantsearch-hooks/src/connectors/useInfiniteHits.ts
- packages/react-instantsearch-hooks/src/connectors/useMenu.ts
- packages/react-instantsearch-hooks/src/connectors/useNumericMenu.ts
- packages/react-instantsearch-hooks/src/connectors/usePagination.ts
- packages/react-instantsearch-hooks/src/connectors/useQueryRules.ts
- packages/react-instantsearch-hooks/src/connectors/useRange.ts
- packages/react-instantsearch-hooks/src/connectors/useRefinementList.ts
- packages/react-instantsearch-hooks/src/connectors/useSearchBox.ts
- packages/react-instantsearch-hooks/src/connectors/useSortBy.ts
- packages/react-instantsearch-hooks/src/connectors/useToggleRefinement.ts
- packages/react-instantsearch-hooks/src/hooks/__tests__/useConnector.test.tsx
- packages/react-instantsearch-hooks/src/hooks/useConnector.ts
**Summary**
widgetType (one of the additional properties) gets used to distinguish between builtin components and user-defined components, which either have no widgetType or a user-defined one.
This also allows a user to override a specific life cycle of a widget, if that would be needed
**Result**
- useConnector accepts "additional properties" that get set on widget instance
- all hooks accept "additional properties" optionally
- builtin components (configure, dynamic widgets) set the default widgetType, but don't allow further "additional properties" (can be added later without breaking change)
> feat(hooks): allow additional widget properties to be passed from hooks

- examples/hooks/App.tsx
- examples/hooks/components/index.ts
- packages/react-instantsearch-hooks-dom/src/ui/Pagination.tsx
- packages/react-instantsearch-hooks-dom/src/ui/__tests__/Pagination.test.tsx
- packages/react-instantsearch-hooks-dom/src/widgets/Pagination.tsx
- packages/react-instantsearch-hooks-dom/src/widgets/__tests__/Pagination.test.tsx
- packages/react-instantsearch-hooks-dom/src/widgets/__tests__/index.test.tsx
- packages/react-instantsearch-hooks-dom/src/widgets/index.ts
This introduces the `Pagination` DOM widget.
The implementation slightly differs from the spec, which doesn't add a `ais-Pagination-item--page` class on numeric pagination items if they're also selected. This behavior is inconsistently implemented in every flavor, but InstantSearch.js does allow the class on every numeric pagination item, which makes sense. The spec is updated [here](https://github.com/algolia/instantsearch-specs/pull/119).
Ticket: [FX-1158](https://algolia.atlassian.net/browse/FX-1158)
- New `Pagination` widget
- DOM tests for both UI component and widget
- New `isModifierClick` utility (tested in #3368)
- Replaced `Pagination` with the widget in example
> feat(hooks): implement Pagination component

- examples/hooks/App.tsx
- examples/hooks/components/index.ts
- packages/react-instantsearch-hooks-dom/src/types/PartialKeys.ts
- packages/react-instantsearch-hooks-dom/src/types/index.ts
- packages/react-instantsearch-hooks-dom/src/ui/SortBy.tsx
- packages/react-instantsearch-hooks-dom/src/ui/__tests__/SortBy.test.tsx
- packages/react-instantsearch-hooks-dom/src/ui/index.ts
- packages/react-instantsearch-hooks-dom/src/widgets/SortBy.tsx
- packages/react-instantsearch-hooks-dom/src/widgets/__tests__/SortBy.test.tsx
- packages/react-instantsearch-hooks-dom/src/widgets/__tests__/index.test.tsx
- packages/react-instantsearch-hooks-dom/src/widgets/index.ts
This introduces the `SortBy` DOM widget.
Ticket: [FX-1164](https://algolia.atlassian.net/browse/FX-1164)
- New `SortBy` widget
- DOM tests for both UI component and widget
- Replaced `SortBy` with the widget in example
> feat(hooks): implement SortBy component

- examples/hooks-react-native/package.json
- examples/hooks/package.json
- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-dom/package.json
- packages/react-instantsearch-hooks-dom/package.json
- packages/react-instantsearch-hooks-server/package.json
- packages/react-instantsearch-hooks/package.json
- packages/react-instantsearch-hooks/src/hooks/__tests__/useConnector.test.tsx
- packages/react-instantsearch-hooks/src/lib/createSearchResults.ts
- test/mock/createAPIResponse.ts
- yarn.lock
**Summary**
The initial results used for rendering the "initial state" (before init or render happens) is now marked as artificial, so that it can be hidden in eg. pagination, stats. 
Note that in server-side rendering, the initial results come from an actual network request, and thus aren't artificial.
**Result**
Initial results are artificial.
> feat(hooks): mark initial results as "artificial"

- packages/react-instantsearch-hooks-dom/src/types/index.ts
- packages/react-instantsearch-hooks-dom/src/ui/Highlight.tsx
- packages/react-instantsearch-hooks-dom/src/ui/__tests__/Highlight.test.tsx
- packages/react-instantsearch-hooks-dom/src/ui/lib/cx.ts
- packages/react-instantsearch-hooks-dom/src/widgets/Highlight.tsx
- packages/react-instantsearch-hooks-dom/src/widgets/Snippet.tsx
- packages/react-instantsearch-hooks-dom/src/widgets/__tests__/Highlight.test.tsx
- packages/react-instantsearch-hooks-dom/src/widgets/__tests__/Snippet.test.tsx
**Summary**
This allows us to reuse the same ui component for multiple widgets
**Result**
- ui component accepts an array of classes for every "key", and is required
- widget accepts a string for every "key", and isn't required, these are only additional
> feat(ui): introduce "classNames" prop for highlight

- packages/react-instantsearch-hooks/src/connectors/__tests__/useClearRefinements.test.tsx
- packages/react-instantsearch-hooks/src/connectors/__tests__/useCurrentRefinements.test.tsx
- packages/react-instantsearch-hooks/src/hooks/__tests__/useConnector.test.tsx
- packages/react-instantsearch-hooks/src/hooks/useConnector.ts
This changes how we compute the initial Helper state that we give to `widget.getWidgetRenderState()` to retrieve the initial widget React state.
The problem originally surfaced when server-side rendering the `<Menu>` component:
> Error: Cannot refine the undeclared facet categories; it should be added to the helper options facets, disjunctiveFacets or hierarchicalFacets
This happens because the `helper.state` and `state` used to call `widget.getWidgetRenderState()` mismatched. In algolia/instantsearch.js#4960, we tried to fix this problem by always relying on `state`. But this constraint is hard to respect, and hard to implement in practice because of stale closures (in `refine()` and `createURL()`).
I explain in that PR why we had to do it this way, essentially because the helper state …
> fix(hooks): compute initial search parameters from widget

- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-dom-maps/package.json
- packages/react-instantsearch-dom/package.json
This adds support for React 18 as peer dependency in React InstantSearch Core and DOM (Hooks package were already marked as compatible). React Native is not yet compatible with React 18.
> fix: support React 18 as peer dependency

- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-core/src/connectors/__tests__/connectBreadcrumb.js
- packages/react-instantsearch-core/src/connectors/__tests__/connectHierarchicalMenu.js
- packages/react-instantsearch-core/src/connectors/__tests__/connectMenu.js
- packages/react-instantsearch-core/src/connectors/__tests__/connectRefinementList.js
- packages/react-instantsearch-core/src/connectors/connectBreadcrumb.js
- packages/react-instantsearch-core/src/connectors/connectHierarchicalMenu.js
- packages/react-instantsearch-core/src/connectors/connectMenu.js
- packages/react-instantsearch-core/src/connectors/connectRefinementList.js
- packages/react-instantsearch-dom/package.json
- packages/react-instantsearch-hooks/package.json
- yarn.lock
**Summary**
The helper exposes a `value` to getFacetValues too now, which is the same as the name/label, except escaped. We can use this instead of `name` in all relevant widgets.
relies on https://github.com/algolia/algoliasearch-helper-js/pull/889 and https://github.com/algolia/algoliasearch-helper-js/pull/900 to show the escaped value (leading `-` gets transformed into `\-`
**Result**
Facet values that start with `-` are automatically escaped, but you can still refine on a literal value starting with `-`
FX-1135
same as https://github.com/algolia/instantsearch.js/pull/5039
> feat(refinements): use escaped value for refining

- packages/react-instantsearch-core/src/core/__tests__/createInstantSearchManager.derived.js
- packages/react-instantsearch-core/src/core/createInstantSearchManager.js
**Summary**
Currently, search results update the state with the `searching` prop set inconditionnally to `false`, which don't represent the reality of multi-index searches. This PR counts the number of expected search results to set the property to its right value.
See details and sandbox in issue https://github.com/algolia/react-instantsearch/issues/3407.
**Result**
The `searching` prop is set to `true` for all but the last expected request.
> fix(multi-index): correctly set `searching` prop in multi-index result states

- packages/react-instantsearch-core/src/connectors/__tests__/connectHierarchicalMenu.js
- packages/react-instantsearch-core/src/connectors/__tests__/connectMenu.js
- packages/react-instantsearch-core/src/connectors/__tests__/connectRefinementList.js
- packages/react-instantsearch-core/src/connectors/connectHierarchicalMenu.js
- packages/react-instantsearch-core/src/connectors/connectMenu.js
- packages/react-instantsearch-core/src/connectors/connectRefinementList.js
- packages/react-instantsearch-core/src/core/utils.ts
**Summary**
This is a follow-up to #3412, making sure that the escaped value doesn't show up for CurrentRefinements
**Result**
CurrentRefinements does not show `\-value`, but `-value`
> fix(facets): show raw value in currentRefinements

- packages/react-instantsearch-hooks-dom/src/ui/Breadcrumb.tsx
- packages/react-instantsearch-hooks-dom/src/ui/ClearRefinements.tsx
- packages/react-instantsearch-hooks-dom/src/ui/CurrentRefinements.tsx
- packages/react-instantsearch-hooks-dom/src/ui/HierarchicalMenu.tsx
- packages/react-instantsearch-hooks-dom/src/ui/Hits.tsx
- packages/react-instantsearch-hooks-dom/src/ui/InfiniteHits.tsx
- packages/react-instantsearch-hooks-dom/src/ui/Menu.tsx
- packages/react-instantsearch-hooks-dom/src/ui/Pagination.tsx
- packages/react-instantsearch-hooks-dom/src/ui/RangeInput.tsx
- packages/react-instantsearch-hooks-dom/src/ui/RefinementList.tsx
- packages/react-instantsearch-hooks-dom/src/ui/__tests__/Breadcrumb.test.tsx
- packages/react-instantsearch-hooks-dom/src/ui/__tests__/ClearRefinements.test.tsx
- packages/react-instantsearch-hooks-dom/src/ui/__tests__/CurrentRefinements.test.tsx
- packages/react-instantsearch-hooks-dom/src/ui/__tests__/HierarchicalMenu.test.tsx
- packages/react-instantsearch-hooks-dom/src/ui/__tests__/Hits.test.tsx
- packages/react-instantsearch-hooks-dom/src/ui/__tests__/InfiniteHits.test.tsx
- packages/react-instantsearch-hooks-dom/src/ui/__tests__/Menu.test.tsx
- packages/react-instantsearch-hooks-dom/src/ui/__tests__/Pagination.test.tsx
- packages/react-instantsearch-hooks-dom/src/ui/__tests__/RangeInput.test.tsx
- packages/react-instantsearch-hooks-dom/src/ui/__tests__/RefinementList.test.tsx
- packages/react-instantsearch-hooks-dom/src/widgets/CurrentRefinements.tsx
- packages/react-instantsearch-hooks-dom/src/widgets/RefinementList.tsx
- packages/react-instantsearch-hooks-dom/src/widgets/__tests__/ClearRefinements.test.tsx
- packages/react-instantsearch-hooks-dom/src/widgets/__tests__/CurrentRefinements.test.tsx
- packages/react-instantsearch-hooks-dom/src/widgets/__tests__/Hits.test.tsx
- packages/react-instantsearch-hooks-dom/src/widgets/__tests__/InfiniteHits.test.tsx
- packages/react-instantsearch-hooks-dom/src/widgets/__tests__/Pagination.test.tsx
- packages/react-instantsearch-hooks-dom/src/widgets/__tests__/RefinementList.test.tsx
This PR goes through all of our new Hooks DOM UI components to make sure their class names and values are in line with those in InstantSearch.js
There is one case with `<CurrentRefinements>` where 2 class names (`noRefinementRoot` and `listNoRefinement`) don't exist either in IS.js or in the specs. Since they do exist in the current React InstantSearch version, I did not remove them.
I also did not replace the class descriptions with those from IS.js since we already reviewed them, but I made sure they are consistent with each other.
<details>
<summary>Extract for reference</summary>
`root`
| description | location |
| ----------- | -------- |
| Class names to apply to the root element | `BreadcrumbClassNames`, `ClearRefinementsClassNames`, `CurrentRefinementsClassNames`, …
> fix(hooks-dom): make components class names consistent with InstantSearch.js

- .circleci/config.yml
- package.json
- packages/react-instantsearch-core/src/types/algoliasearch.ts
- packages/react-instantsearch-dom-maps/package.json
- packages/react-instantsearch-dom/package.json
- packages/react-instantsearch-hooks-dom/package.json
- packages/react-instantsearch-hooks-server/package.json
- packages/react-instantsearch-native/package.json
- packages/react-instantsearch/package.json
- test/mock/createSearchClient.ts
- yarn.lock
**Summary**
Transitively the peerDependency on algoliasearch is already required through algoliasearch-helper, and it's pretty much required for types too.
This won't add new errors, as the peerDependency is already present.
fixes #3428
**Result**
No errors when installing `yarn add react-instantsearch-dom algoliasearch` using Yarn 3
> fix(packages): correctly mark peer dependency

- packages/react-instantsearch-hooks/src/components/__tests__/InstantSearch.test.tsx
- packages/react-instantsearch-hooks/src/lib/useInstantSearch.ts
This removes the experimental warning in React InstantSearch Hooks, as well as the `suppressExperimentalWarning` prop on `<InstantSearch>`.
- https://github.com/algolia/doc/pull/6911
> feat(hooks): remove experimental warning

- jest.config.js
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/__utils__/all-widgets.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/all-components.test.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/all-widgets.test.tsx
- tsconfig.declaration.json
**Summary**
The reason the types previously were the wrong directory is because `__testutils__/all-widgets.ts` was included, and this imported items from the root, thus changing the output format of the types.
**Result**
Correct type definition files for React InstantSearch hooks web
before|after
---|---
> fix(types): export correct types for react-instantsearch-hooks-web

- .eslintrc.js
- packages/react-instantsearch-hooks/package.json
- packages/react-instantsearch-hooks/src/hooks/__tests__/useConnector.test.tsx
- packages/react-instantsearch-hooks/src/hooks/useConnector.ts
- packages/react-instantsearch-hooks/src/lib/__tests__/dequal.test.ts
- packages/react-instantsearch-hooks/src/lib/dequal.ts
- packages/react-instantsearch-hooks/src/lib/useStableValue.ts
- yarn.lock
This optimizes when we update the React state in `useConnector()` to skip function reference changes in the render state. This lets us and users create unstable function references in `getWidgetRenderState()` (our own `connectSearchBox()` doesn't expose stable functions).
This **brings support for inline functions used in widgets**, like users are used to in RIS v6.
```jsx
const [favorites, setFavorites] = useState([]);
return (
<Hits
hitComponent={Hit}
transformItems={(hits) =>
hits.map((hit) => ({
...hit,
isFavorite: favorites.find((x) => x.objectID === hit.objectID),
}))
}
/>
);
}
```
Prior to this change, **such an app would be prone to trigger an infinite loop**. Now, it triggers only two renders. In the future, we …
> fix(hooks): prevent infinite loops from render state

- packages/react-instantsearch-core/src/connectors/__tests__/connectNumericMenu.js
- packages/react-instantsearch-core/src/connectors/connectNumericMenu.js
**Summary**
This PR addresses an issue encountered by a customer, where an item on a `NumericMenu` having its `start` value set to the maximum value of a facet would wrongly be disabled in the widget.
Fixes [FX-1376](https://algolia.atlassian.net/browse/FX-1376).
**Result**
- The items are now correctly enabled/disabled
- Tests are updated to include these specific cases
> fix(numericmenu): include range values in comparison with minmax bounds

- packages/react-instantsearch-dom-maps/src/index.js
**Summary**
To allow a custom control for "refine on map move" to be made without resorting to importing from the individual files, which is hard/not recommended, we need to expose the GeoSearchContext
**Result**
fixes #3448
GeoSearchContext is exposed
> feat(dom-maps): expose GeoSearchContext

- packages/react-instantsearch-hooks-server/rollup.config.js
- packages/react-instantsearch-hooks-server/src/__tests__/modules-none.test.tsx
- packages/react-instantsearch-hooks-server/src/__tests__/modules-with-extension.test.tsx
- packages/react-instantsearch-hooks-server/src/__tests__/modules-without-extension.test.tsx
- packages/react-instantsearch-hooks-server/src/getServerState.tsx
- tsconfig.json
**Summary**
Import both `react-dom/server.js` (react 16 and 17) and `react-dom/server` (react 18, since they added "exports" in package.json) dynamically to make sure server-side rendering works in all situations
**Result**
fixes #3453
FX-1405
I don't see how this can be tested immediately, but we can add a react 18 next.js example later along the existing react 17 one, which would fail before this PR
We were slightly worried this may hurt TTFB, but in reality that doesn't seem to be the case, as evidenced by a quick benchmark (using https://github.com/mildsunrise/curl-benchmark) done:
```
Before the change:
DNS      TCP        SSL  Request           Content
Code  lookup  connect  handshake     sent    TTFB  download
min:     9.0      0.0        0.0      0.0    52.0       0.0
avg:    14.4 …
```
> feat(hooks-server): support import from React 18

- examples/hooks/App.tsx
- packages/react-instantsearch-hooks-web/src/widgets/Highlight.tsx
- packages/react-instantsearch-hooks-web/src/widgets/Snippet.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/Highlight.test.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/Snippet.test.tsx
**Summary**
instantsearch.js escapes the html and replaces the original tags with <mark> in Hits. This is not desirable in React as it doesn't decode literal html literals.
**Result**
apostrophe, quote, lesser and greater signs show up as authored in the index. 
https://algolia.atlassian.net/browse/CR-1142
> fix(hooks-highlight): make sure highlight and snippet don't show html-escaped content

- examples/hooks/components/QueryRuleCustomData.tsx
- packages/react-instantsearch-core/src/core/createConnector.tsx
- packages/react-instantsearch-core/src/widgets/DynamicWidgets.tsx
- packages/react-instantsearch-core/src/widgets/Index.tsx
- packages/react-instantsearch-core/src/widgets/InstantSearch.tsx
- packages/react-instantsearch-dom/src/components/Hits.tsx
- packages/react-instantsearch-hooks-server/src/getServerState.tsx
- packages/react-instantsearch-hooks-web/src/ui/InternalHighlight.tsx
- packages/react-instantsearch-hooks/src/components/DynamicWidgets.tsx
- packages/react-instantsearch-hooks/src/lib/useForceUpdate.ts
- tsconfig.json
> **Note**
> The CI is expected to fail, only the [**Type checking**](https://app.circleci.com/pipelines/github/algolia/react-instantsearch/2842/workflows/4d48e58b-30e1-438b-8b6d-c3540483d5e5/jobs/55175/parallel-runs/0/steps/0-108) workflow matters.
This updates the types in our codebase to support React 18.
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210
- [JIRA ticket](https://algolia.atlassian.net/browse/FX-1451)
> fix(types): support React 18 types

- packages/react-instantsearch-hooks/src/components/__tests__/InstantSearchSSRProvider.test.tsx
This refactors the tests for `<InstantSearchSSRProvider>` to use our widgets.
This is a preparation of [a test](https://github.com/algolia/react-instantsearch/commit/63ad30fd76ee776939f037cdda0951c2d60aa30b) that shows the bug reported in #3482, to use our actual `<SearchBox>` widget, closer to a real use case.
> test(hooks): use widgets in `<InstantSearchSSRProvider>` tests

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Bug_report_Hooks.md
This adds the React version in the GitHub issue template to better track on what React version the InstantSearch bug appears. (We're seeing more bugs happen on React 18 only.)
> docs(github): add React version in issue template

- packages/react-instantsearch-hooks/src/components/__tests__/InstantSearch.test.tsx
This adds a few tests to make sure that InstantSearch widgets behave as expected in Suspense boundaries.
> test(hooks): add tests within a Suspense boundary

- packages/react-instantsearch-hooks-web/src/widgets/Hits.tsx
- packages/react-instantsearch-hooks-web/src/widgets/HitsPerPage.tsx
- packages/react-instantsearch-hooks-web/src/widgets/InfiniteHits.tsx
**Summary**
Similar to #3499, but i did a search for other places props was used literally in -web
We'd get a typescript error for these if https://github.com/microsoft/TypeScript/issues/39998 was fixed, but that doesn't seem to be on their table yet
**Result**
all connector props are correctly avoided to be passed to the ui component
> fix(hooks-web): don't pass widget props to ui components

- package.json
This tracks the `react-instantsearch-hooks-web` bundle size.
Notice that the UMD export is named `ReactInstantSearchHooksDOM` but I believe we wanted to go for `ReactInstantSearchHooksWeb`, like the package name.
> chore(hooks-web): track bundle size

- examples/hooks-react-native/package.json
- examples/hooks/package.json
- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-dom/package.json
- packages/react-instantsearch-hooks-server/package.json
- packages/react-instantsearch-hooks-web/package.json
- packages/react-instantsearch-hooks/package.json
- yarn.lock
This upgrades the InstantSearch.js to [v4.41.0](https://github.com/algolia/instantsearch.js/releases/tag/v4.41.0) in the Hooks package.
This includes algolia/instantsearch.js#5056 which skips the initial search request to only rely on the one triggered by `addWidgets()`. This eliminates problems in React 18 where effects in `useInstantSearch()` and `useConnector()` get executed one after the other, triggering sometimes 2 network requests.
> feat(hooks): upgrade to InstantSearch.js 4.41.0

- packages/react-instantsearch-hooks/src/hooks/useInstantSearch.ts
- packages/react-instantsearch-hooks/src/lib/useSearchResults.ts
- packages/react-instantsearch-hooks/src/lib/useSearchState.ts
**Summary**
useInstantSearch should be generic, so you can use it with custom widgets in a type-safe way
**Result**
`useInstantSearch<CustomUiState>()` should work as expected, and have all functions have the right type for UiState
> fix(types): allow useInstantSearch to be generic

- packages/react-instantsearch-hooks-web/src/widgets/__tests__/Breadcrumb.test.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/ClearRefinements.test.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/CurrentRefinements.test.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/HierarchicalMenu.test.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/HitsPerPage.test.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/InfiniteHits.test.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/Menu.test.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/Pagination.test.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/PoweredBy.test.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/RangeInput.test.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/RefinementList.test.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/SortBy.test.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/ToggleRefinement.test.tsx
- packages/react-instantsearch-hooks/src/components/__tests__/DynamicWidgets.test.tsx
- test/mock/createSearchClient.ts
**Summary**
PR in support of `feat/react-18` that makes our tests pass with React 18.
Ticket: [FX-1450](https://algolia.atlassian.net/browse/FX-1450)
**TODO**
> **Note**
> CI is not expected to pass as the Strict Mode in React 18 performs more operations which make the relevant tests in our codebase fail. All the other tests should perform correctly.
> fix(tests): react 18 compatibility

- packages/react-instantsearch-hooks-web/src/ui/CurrentRefinements.tsx
When you use multiple `<Index>` widgets with widgets with the same attribute, and then refine both these widgets, the `<CurrentRefinements>` displays a React key warning because the keys are identical.
This adds the index name to the label key to have unique keys.
> fix(hooks-web): fix duplicated key in <CurrentRefinements>

- jest.config.js
- package.json
- packages/react-instantsearch-hooks-server/src/__tests__/getServerState.test.tsx
- packages/react-instantsearch-hooks/src/components/__tests__/Index.test.tsx
- packages/react-instantsearch-hooks/src/components/__tests__/InstantSearchSSRProvider.test.tsx
- packages/react-instantsearch-hooks/src/hooks/useConnector.ts
- packages/react-instantsearch-hooks/src/lib/useIndex.ts
- packages/react-instantsearch-hooks/src/lib/useInstantSearchApi.ts
- packages/react-instantsearch-hooks/src/lib/useWidget.ts
- yarn.lock
This fixes our SSR APIs as reported in #3511.
During the `useSyncExternalStore()` migration in #3489, we omitted some SSR checks by removing the `serverState.initialResults` condition. This was responsible for mounting the widgets during rendering, to then render them on the server. We now also cover the generated HTML with a test.
Note that this solution doesn't work with Strict Mode, as it wasn't prior to the bug. This is just a fix to release early, and then we'll work on Strict Mode support.
Closes #3511
> fix(hooks): mount widgets in SSR to retrieve HTML

- examples/hooks-react-native/package.json
- examples/hooks/package.json
- package.json
- packages/react-instantsearch-core/package.json
- packages/react-instantsearch-dom/package.json
- packages/react-instantsearch-hooks-server/package.json
- packages/react-instantsearch-hooks-server/src/getServerState.tsx
- packages/react-instantsearch-hooks-web/package.json
- packages/react-instantsearch-hooks/package.json
- packages/react-instantsearch-hooks/src/components/InstantSearchServerContext.ts
- packages/react-instantsearch-hooks/src/lib/useInstantSearchApi.ts
- packages/react-instantsearch-hooks/src/lib/useInstantSearchContext.ts
- packages/react-instantsearch-hooks/src/lib/useInstantSearchServerContext.ts
- yarn.lock
**Summary**
This PR updates `algoliasearch-helper` in **React InstantSearch** and `instantsearch.js` in **React InstantSearch Hooks** to allow the `<HierarchicalMenu>` widget to retrieve and display the full list of a refined item's parents values.
I also had to take into account recent changes in InstantSearch JS types, so that's included here.
> fix(HierarchicalMenu): show full hierarchical parent values

- packages/react-instantsearch-hooks-web/src/widgets/SearchBox.tsx
This refactors the `<SearchBox>` component to remove the `useEffect()`.
You can learn more in [**You Might Not Need an Effect**](https://beta.reactjs.org/learn/you-might-not-need-an-effect), notably these two sections:
- [Adjusting some state when a prop changes](https://beta.reactjs.org/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes)
- [Sharing logic between event handlers](https://beta.reactjs.org/learn/you-might-not-need-an-effect#sharing-logic-between-event-handlers)
- #3552
- #3553
> refactor(hooks): remove `useEffect()` from `<SearchBox>`

- packages/react-instantsearch-hooks-web/src/widgets/RefinementList.tsx
This refactors the `<RefinementList>` component to remove the `useEffect()`.
You can learn more in [**You Might Not Need an Effect**](https://beta.reactjs.org/learn/you-might-not-need-an-effect), notably the section [Sharing logic between event handlers](https://beta.reactjs.org/learn/you-might-not-need-an-effect#sharing-logic-between-event-handlers).
- #3551
- #3552
> refactor(hooks): remove `useEffect()` from `<RefinementList>`

- packages/react-instantsearch-hooks/src/hooks/__tests__/useInstantSearch.test.tsx
- packages/react-instantsearch-hooks/src/hooks/useConnector.ts
- packages/react-instantsearch-hooks/src/hooks/useInstantSearch.ts
- packages/react-instantsearch-hooks/src/lib/__tests__/useSearchResults.test.tsx
- packages/react-instantsearch-hooks/src/lib/__tests__/useSearchState.test.tsx
- packages/react-instantsearch-hooks/src/lib/getIndexSearchResults.ts
- packages/react-instantsearch-hooks/src/lib/useSearchResults.ts
- packages/react-instantsearch-hooks/src/lib/useSearchState.ts
This updates the [`useInstantSearch()`](https://www.algolia.com/doc/api-reference/widgets/use-instantsearch/react-hooks/) implementation for the search state and search results APIs (`uiState`, `setUiState()`, `indexUiState`, `setIndexUiState()`, `results`, `scopedResults`).
The **previous implementation relied on adding widgets** to the instance to retrieve the search state and the search results. This added footprint on the instance, and triggered unnecessary renders.
This **new implementation subscribes to the InstantSearch `render` event** to update the React state. Since we rely on this event, the React state will get updated at the same time as all the other widgets' render, resulting in a batch update.
> fix(hooks): provide state and results APIs from "render" event

- packages/react-instantsearch-hooks/src/components/DynamicWidgets.tsx
**Summary**
instead of having the type correctly match which types are not allowed, there was an allow-list that was missing members. This is now fixed by going to a disallow-list of InstantSearch.js props that aren't needed
**Result**
fixes #3563
> fix(hooks): type of DynamicWidgets props

- package.json
- packages/react-instantsearch-hooks/src/components/__tests__/InstantSearch.test.tsx
- packages/react-instantsearch-hooks/src/components/__tests__/InstantSearchSSRProvider.test.tsx
- packages/react-instantsearch-hooks/src/components/__tests__/routing/dispose-start.test.tsx
- packages/react-instantsearch-hooks/src/components/__tests__/routing/external-influence.test.tsx
- packages/react-instantsearch-hooks/src/components/__tests__/routing/modal.test.tsx
- packages/react-instantsearch-hooks/src/components/__tests__/routing/spa-debounced.test.tsx
- packages/react-instantsearch-hooks/src/components/__tests__/routing/spa-replace-state.test.tsx
- packages/react-instantsearch-hooks/src/components/__tests__/routing/spa.test.tsx
- packages/react-instantsearch-hooks/src/hooks/__tests__/useInstantSearch.test.tsx
- packages/react-instantsearch-hooks/src/lib/useInstantSearchApi.ts
This addresses a lot of issues related to the `<InstantSearch>` lifecycle that happened when remounting:
- Closes #3530
- Closes #3550
- Maybe #3537
Prior to this PR, any prop change would create a new instance of InstantSearch.js, in an Effect. Now, we track props changes during rendering, and update them with the underlying InstantSearch.js internals. That's similar to [how it's done in Vue InstantSearch](https://github.com/algolia/vue-instantsearch//blob/71c25d460e1b077b62ca41a59a5c4df7b713ec56/src/util/createInstantSearchComponent.js#L16-L36).
InstantSearch.js doesn't provide a way to override `routing`, so this prop cannot be changed. If we find cases where we need `routing` to be dynamic, we can provide an internal API in InstantSearch.js.
But long term, I think we should have an …
> fix(hooks): use single instance in <InstantSearch>

- examples/hooks/package.json
- yarn.lock
This updates the Parcel dependency in the Hooks example to use the same version as in other examples.
> chore(examples): bump Parcel to 2.6.2

- packages/react-instantsearch-hooks/src/lib/useInstantSearchApi.ts
This adds a comment that explains why we use the InstantSearch constructor, and not the `instantsearch()` function.
> docs(hooks): document why we use the InstantSearch constructor

- packages/react-instantsearch-hooks-web/src/ui/HierarchicalMenu.tsx
- packages/react-instantsearch-hooks-web/src/ui/__tests__/HierarchicalMenu.test.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/HierarchicalMenu.test.tsx
**Summary**
This PR fixes the `label` CSS class (instead of `labelText`) used in the `HierarchicalMenu` widget of React InstantSearch Hooks.
According to the [InstantSearch specs](https://instantsearch-css.netlify.app/widgets/hierarchical-menu/), the correct CSS class is `.ais-HierarchicalMenu-label`.
For reference, here is the [implementation of the CSS class in InstantSearch.js](https://github.com/algolia/instantsearch.js/blob/master/src/widgets/hierarchical-menu/hierarchical-menu.tsx#L335).
**Note:** This fix may break current user implementations that depend on the `labelText` CSS class so we want to make sure the release note mentions it clearly.
**Results**
When a `HierarchicalMenu` item is selected, [the correct style](https://github.com/algolia/instantsearch-specs/blob/master/src/s …
> fix(hooks): use `label` CSS class in <HierarchicalMenu>

- packages/react-instantsearch-hooks-web/src/widgets/SearchBox.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/SearchBox.test.tsx
**Summary**
As mentioned in discussion #3523, the `searchAsYouType` prop is missing from `react-instantsearch-hooks-web`'s `SearchBox` component, while it is present in [the non-hooks version](https://www.algolia.com/doc/api-reference/widgets/search-box/react/#widget-param-searchAsYouType).
**Notes**:
- I think we can do better on the widget/ui components splitting, so we won't have to duplicate default search behaviour for each JSX UI library (Preact or Solid for example)
- I'm not sure whether it's fine or not that we now refine on submit by default even if `searchAsYouType` is true, my guess would be it's okay as we won't trigger a search if query does not change.
**Result**
As the tests show, when `searchAsYouType` is set to `false`, it does not change internal InstantSearch state. …
> feat(hooks): add `searchAsYouType` option to <SearchBox>

- .eslintrc.js
- packages/react-instantsearch-hooks/global.d.ts
- packages/react-instantsearch-hooks/src/components/__tests__/InstantSearch.test.tsx
- packages/react-instantsearch-hooks/src/lib/useInstantSearchApi.ts
- packages/react-instantsearch-hooks/src/lib/useWidget.ts
Starting from [v6.30.2](https://github.com/algolia/react-instantsearch/releases/tag/v6.30.2), when the `<InstantSearch>` component is unmounted, one search request per widget is triggered. The PR https://github.com/algolia/react-instantsearch/pull/3561 introduces this regression.
This issue was originally reported here: https://github.com/algolia/react-instantsearch/issues/3586.
Currently, when the `<InstantSearch>` component is unmounted, a `cleanup` is scheduled using a `setTimeout`.
https://github.com/algolia/react-instantsearch/blob/affcbb58ee5c63345cc9424ad8ab566f3a01c9f9/packages/react-instantsearch-hooks/src/lib/useInstantSearchApi.ts#L156-L162
The widgets also rely on the same strategy when they unmount.
https://github.com/algolia/react-instantsearch/blob/affcbb58ee5c63345cc9424ad8 …
> fix(hooks): prevent widget cleanup on `<InstantSearch>` unmount

- README.md
**Summary**
Fixes the codesandbox link within the readme, currently if you follow the link codesandbox is unable to access the example
**Result**
Click the link to successfully navigate to codesandbox
> docs(readme): update Getting Started sandbox link

- examples/hooks/App.tsx
- packages/react-instantsearch-hooks-web/src/ui/SearchBox.tsx
- packages/react-instantsearch-hooks-web/src/ui/__tests__/SearchBox.test.tsx
- packages/react-instantsearch-hooks-web/src/widgets/SearchBox.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/SearchBox.test.tsx
This PR introduces the `autoFocus` prop on the `<SearchBox>` widget in React InstantSearch Hooks.
This prop exists in all flavors but was missing in React InstantSearch Hooks.
The prop capitalization is different from other flavors (JS, Vue and Angular) because we're relying on React's custom `autoFocus` prop and not the native [`autofocus`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus). This is more natural for React developers who are used to this prop.
Ticket: [FX-1629](https://algolia.atlassian.net/browse/FX-1629)
> feat(SearchBox): introduce `autoFocus` prop

- examples/next/sandbox.config.json
This PR adds a CodeSandbox config file that explicitly sets node version to 12, to comply with some dependencies requirements.
This PR fixes https://github.com/algolia/react-instantsearch/issues/3601.
[**Sandbox →**](https://codesandbox.io/s/github/algolia/react-instantsearch/tree/fix/example-next-codesandbox/examples/next)
> chore: explicitly set node version for codesandbox

- examples/hooks-e-commerce/package.json
- package.json
- packages/react-instantsearch-hooks-server/package.json
- packages/react-instantsearch-hooks-web/package.json
- packages/react-instantsearch-hooks/package.json
- packages/react-instantsearch-hooks/src/connectors/__tests__/useHitsPerPage.test.tsx
- packages/react-instantsearch-hooks/src/connectors/__tests__/useNumericMenu.test.tsx
- packages/react-instantsearch-hooks/src/connectors/__tests__/useSortBy.test.tsx
- yarn.lock
**Summary**
Following the implementation of [FX-740](https://algolia.atlassian.net/browse/FX-740), this breaks some tests for connectors.
Therefore I updated the `instantsearch.js` dependency and fixed the tests so that others don't have to deal with it
**Result**
Updated `instantsearch.js` for RISH
> chore: update `instantsearch.js` dependency and fix connector tests

- packages/react-instantsearch-dom-maps/package.json
- ship.config.js
This was disappeared when we moved to lerna for bumping the packages.
discovered in #2897
> ci(shipjs): update peerDependency on version bump

- packages/react-instantsearch-hooks-web/src/ui/SearchBox.tsx
- packages/react-instantsearch-hooks-web/src/ui/__tests__/SearchBox.test.tsx
**Summary**
[FX-1646](https://algolia.atlassian.net/browse/FX-1646)
Here's a minor bug fix I had in my stash. There's a screenshot in the issue linked above.
**Result**
Added a test to ensure the reset button is hidden when search is stalled.
> fix(rish): hide reset button when search is stalled in `SearchBox`

- packages/react-instantsearch-dom/src/components/SearchBox.js
- packages/react-instantsearch-dom/src/components/__tests__/SearchBox.js
- packages/react-instantsearch-hooks-web/src/ui/SearchBox.tsx
- packages/react-instantsearch-hooks-web/src/ui/__tests__/SearchBox.test.tsx
**Summary**
This change is motivated from a very specific use case:
I have a custom form input component which includes a `SearchBox`, so I my own `<form>` tag is wrapping the `<form>` that's within `SearchBox`. This leads to an unexpected form submission when pressing the <kbd>Enter</kbd> key in the search box text input. 
I've already tried `preventDefault` and `stopPropagation` in the `onSubmit` callback available for `SearchBox` but it seems the way React handles events makes this useless. Getting a `ref` for the form allowed me to stop the submit event by using `addEventListener` on the `ref.current` element.
Since there's already an `inputRef` I think having a `formRef` won't hurt and would help others that may find themselves in a similar form nesting situation.
**Result**
A new …
> feat(SearchBox): expose formRef

- packages/react-instantsearch-hooks-web/src/widgets/SearchBox.tsx
- packages/react-instantsearch-hooks-web/src/widgets/__tests__/SearchBox.test.tsx
**Summary**
Similarly as #802, when reset is triggered and searchAsYouType is false, a search should still happen.
**Result**
fixes #3641
> fix(hooks-web): reset with searchAsYouType=false should search

- packages/react-instantsearch-dom/src/components/HierarchicalMenu.js
- packages/react-instantsearch-dom/src/components/__tests__/HierarchicalMenu.js
- packages/react-instantsearch-dom/src/components/__tests__/__snapshots__/HierarchicalMenu.js.snap
- packages/react-instantsearch-dom/src/widgets/HierarchicalMenu.js
- packages/react-instantsearch-hooks-web/src/ui/HierarchicalMenu.tsx
- packages/react-instantsearch-hooks-web/src/ui/__tests__/HierarchicalMenu.test.tsx
**Summary**
This PR adds a new CSS class modifier for the `<HierarchicalMenu>` widgets in RIS and RISH, following the addition made in the CSS specs. For RISH, it also adds a dedicated key in `classNames`.
| InstantSearch.css class name | Key in `classNames` (RISH only) |
| --- | --- |
| `.ais-HierarchicalMenu-link--selected` | `selectedItemLink` |
[FX-1794](https://algolia.atlassian.net/browse/FX-1794)
> feat(HierarchicalMenu): add css class for link of selected menu item

- examples/next/package.json
- yarn.lock
**Summary**
This PR updates the `next` dependency of the next example to the last version.
**Result**
It should fix the Webpack error we currently have on Codesanbox: https://codesandbox.io/s/github/algolia/react-instantsearch/tree/master/examples/next
> chore(examples): update next dep example

- packages/react-instantsearch-core/src/core/__tests__/createConnector.js
- packages/react-instantsearch-core/src/core/createConnector.tsx
- packages/react-instantsearch-core/src/widgets/InstantSearch.tsx
- packages/react-instantsearch-core/src/widgets/__tests__/InstantSearch.js
**Summary**
This PR makes React InstantSearch compatible with React 18's Strict Mode.
**Result**
Similar to what we did for React InstantSearch Hooks, cleanup logic is now scheduled instead of immediately executed on unmount, which makes them cancelable when React 18's Strict Mode remounts the components immediately.
[**Sandbox →**](https://codesandbox.io/s/react-instantsearch-app-forked-12ivo6?file=/package.json)
> feat(core): support react 18 strict mode

- packages/react-instantsearch-dom-maps/package.json
- ship.config.js
If we'd use `lerna publish` instead of a publish command per package, this may not be needed, but I couldn't find how to make that work correctly with shipjs just yet.
The order is now (note dom-maps is published later):
```
'packages/react-instantsearch-core',
'packages/react-instantsearch-hooks',
'packages/react-instantsearch-dom',
'packages/react-instantsearch-hooks-server',
'packages/react-instantsearch-hooks-web',
'packages/react-instantsearch-native',
'packages/react-instantsearch-dom-maps',
'packages/react-instantsearch'
```
This is equivalent to https://github.com/algolia/ui-components/pull/23
> ci(shipjs): release package in dependent order

- examples/hooks-ssr/.eslintrc.js
- examples/hooks-ssr/src/App.js
**Summary**
The example is ran using node without esm, and webpack also isn't set up for proper esm, so this errors in modern node (14+) if we use esm.
Setting up for proper esm (type module etc) wouldn't be representative for most users, so we'll fall back to cjs
CR-2214
**Result**
using cjs imports in hooks-ssr example
> docs(example-ssr): use cjs imports

- packages/react-instantsearch-hooks-server/src/__tests__/modules-none.test.tsx
- packages/react-instantsearch-hooks-server/src/__tests__/modules-with-extension.test.tsx
- packages/react-instantsearch-hooks-server/src/__tests__/modules-without-extension.test.tsx
- packages/react-instantsearch-hooks-server/src/getServerState.tsx
**Summary**
There are some cases where the combination of trying to make sure renderToString doesn't end up in a browser bundle, being runnable on esm + cjs, react 17 and 18, .js extension etc. blows up.
One of those is pnpm/vercel removing "unused" packages.
**Result**
This PR introduces a new argument `renderToString` to `getServerState` so you can inject the dependency yourself, meaning the import is within your own code and won't be purged.
```js
import { renderToString } from 'react-dom/server';
await getServerState(<App/>, renderToString);
await getServerState(<App/>, import('react-dom/server').then(mod => mod.renderToString));
```
fixes #3633
closes #3618
see vercel/next.js#40067
FX-1869
> feat(getServerState): allow users to inject renderToString

- examples/hooks-next/pages/index.tsx
- examples/hooks-ssr/src/server.js
Followup on #3658, to be merged close to the release
EDIT: actually this can be merged before the release already as previously the unused argument wasn't used
> docs(ssr): pass renderToString to getServerState in examples

- packages/react-instantsearch-hooks/src/lib/useStableValue.ts
There's no tests for this, so make sure that the timings we had are still the same.
specifically used in:
https://github.com/algolia/react-instantsearch/blob/f436d31184f3f75b33a1fdaa19c665e77948df28/packages/react-instantsearch-hooks/src/hooks/useConnector.ts#L26-L29 https://github.com/algolia/react-instantsearch/blob/aa5f9d84ddb6e97d05e6ad1baf2c6caa23891281/packages/react-instantsearch-hooks/src/lib/useIndex.ts#L22
same as https://github.com/algolia/predict/pull/45
> fix(hooks): avoid effect in useStableValue
