packages/react-instantsearch/src/widgets/HitsPerPage.js

Adds a better example on HitsPerPage and adds some documentation around Configure

docs(HitsPerPage): better example and speak about Configure

---

packages/react-instantsearch/src/core/utils.js
packages/react-instantsearch/src/core/utils.test.js

remove empty key wasn't working correctly as it removed key that were not objects.

fix(util): remove empty key was removing non object key

---

.travis.yml
docgen/build.js
package.json

**Summary**
Seeing if the docs are able to build can be done with Netlify now
closes #33
**Result**
Travis will run faster because it doesn't run the docs anymore

chore(Travis): don't build docs

---

packages/react-instantsearch/src/connectors/connectToggle.js
packages/react-instantsearch/src/widgets/Toggle.js
stories/Toggle.stories.js

See: https://github.com/algolia/react-instantsearch/issues/52
I also add a story about it.

docs: defaultChecked doesn't exist anymore

---

package.json
packages/react-instantsearch/examples/autocomplete/package.json
packages/react-instantsearch/examples/geo-search/package.json
packages/react-instantsearch/examples/multi-index/package.json
packages/react-instantsearch/examples/react-native/package.json
packages/react-instantsearch/examples/react-router-v4/package.json
packages/react-instantsearch/examples/react-router/package.json
packages/react-instantsearch/src/connectors/connectHierarchicalMenu.js
packages/react-instantsearch/src/connectors/connectHits.js
packages/react-instantsearch/src/connectors/connectInfiniteHits.js
packages/react-instantsearch/src/connectors/connectMenu.js
packages/react-instantsearch/src/connectors/connectMultiRange.js
packages/react-instantsearch/src/connectors/connectPagination.js
packages/react-instantsearch/src/connectors/connectRange.js
packages/react-instantsearch/src/connectors/connectRefinementList.js
packages/react-instantsearch/src/connectors/connectStats.js
packages/react-instantsearch/src/core/Index.js
packages/react-instantsearch/src/core/utils.test.js
yarn.lock

chore: update eslint version

---

packages/react-instantsearch/src/connectors/connectMenu.js

Changed "tha" to "the" on line 55
(Simple english spelling/typo correction)

Update text content

---

docgen/src/guide/Connectors.md

**Summary**
Adding isRefined as a param in the docs, which was missing

Connectors.md missing isRefined

---

docgen/layouts/common/header.pug
docgen/src/Getting_started.md
docgen/src/guide/<InstantSearch>.md
docgen/src/guide/Autocomplete_menu.md
docgen/src/guide/Conditional_display.md
docgen/src/guide/Connectors.md
docgen/src/guide/Custom_connectors.md
docgen/src/guide/Default_refinements.md
docgen/src/guide/Highlighting_results.md
docgen/src/guide/Install.md
docgen/src/guide/Multi_index.md
docgen/src/guide/Operations.md
docgen/src/guide/React_native.md
docgen/src/guide/Routing.md
docgen/src/guide/Search_parameters.md
docgen/src/guide/Search_state.md
docgen/src/guide/Searching_in_Lists.md
docgen/src/guide/Server-side_rendering.md
docgen/src/guide/Sorting_and_filtering.md
docgen/src/guide/Styling_widgets.md
docgen/src/guide/Virtual_widgets.md
docgen/src/guide/Widgets.md
docgen/src/guide/i18n.md
docgen/src/guide/index.md
docgen/src/videos/index.md

We now have a Learn section that features Guides and Videos.

docs(videos): add getting started

---

packages/react-instantsearch/src/connectors/connectHighlight.js

docs(connectHighlight): fix typo

---

packages/react-instantsearch/src/connectors/connectConfigure.js
packages/react-instantsearch/src/connectors/connectConfigure.test.js
stories/MultiIndex.stories.js
storybook/head.html
storybook/public/react-autosuggest.css
storybook/public/util.css

Improve the MultiIndex example on storybook by using Vestiaire Collective dataset. 
Improved style of the autocomplete. 
Fix a little bug about Configure, MultiIndex and CleanUp on certain condition.

docs(MultiIndex): improve storybook example

---

docgen/src/guide/Conditional_display.md
packages/react-instantsearch/src/core/createConnector.js
packages/react-instantsearch/src/core/createConnector.test.js
packages/react-instantsearch/src/core/createInstantSearchManager.js
packages/react-instantsearch/src/core/createInstantSearchManager.test.js

the search status were not available inside the search state. It means that there's no way to actually display something if this search is currently being performed.

fix(SFFV): search status we're not inside search state

---

packages/react-instantsearch/src/core/createStore.js
packages/react-instantsearch/src/core/createStore.test.js

See https://github.com/algolia/react-instantsearch/issues/137

fix(store): delay call to listener to prevent infinite loops

---

packages/react-instantsearch/examples/react-native/App.js
packages/react-instantsearch/examples/react-native/src/Categories.js
packages/react-instantsearch/examples/react-native/src/Filters.js
packages/react-instantsearch/examples/react-native/src/Price.js
packages/react-instantsearch/examples/react-native/src/Type.js

Following feedback on twitter: 
- dismiss keyboard when navigating on Android
- Hide back button on Android
- Fix `Nan` display on the price page
To try:

docs(RN): fix example

---

packages/react-instantsearch/examples/react-router-v4/package.json

docs(examples): react-router-dom next tag is no more

---

docgen/src/guide/Server-side_rendering.md
packages/react-instantsearch/examples/next-app/package.json
packages/react-instantsearch/examples/server-side-rendering/README.md
packages/react-instantsearch/examples/server-side-rendering/package.json
packages/react-instantsearch/src/core/createInstantSearchServer.js
packages/react-instantsearch/src/core/findResultsState.js

I rewrote the guide as a complete new user to server-side rendering. Let me know what you think @mthuret

docs(server-side): Rework a bit as a complete new user

---

scripts/test.sh
test/regressions/tests.js

**Summary**
Following 1ff96ad6aaa7565d8f49cd209c667ef98dc4d3ca
**Result**
Should have flake less build now.

fix(argos): address flakyness

---

packages/react-instantsearch/examples/next-app/next.config.js
packages/react-instantsearch/examples/next-app/package.json

docs(SSR): fix build of SSR example

---

packages/react-instantsearch/examples/next-app/components/app.js
packages/react-instantsearch/examples/next-app/components/head.js
packages/react-instantsearch/examples/next-app/pages/index.js
packages/react-instantsearch/examples/next-app/static/instantsearch.css

- improve design of the next-app
- introduce a better algo for the URL sync (do not push anymore into Router at each keystroke)
- Link to source code

docs(SSR): improve next.js example

---

packages/react-instantsearch/examples/next-app/pages/index.js

Hello, 
Thank You for quick SSR support for the library! I was trying the example and found that initial state was not parsing properly. So the change fixes it. Rest everything works great!

Initial state will be parsed properly now

---

docgen/src/examples/e-commerce-infinite/App.js
docgen/src/examples/e-commerce/App.js
docgen/src/examples/material-ui/App.js
stories/util.js

We have those warnings due to Ikea picture not being under https.

docs(pictures): use cloudinary to fix Mixed Content issue.

---

packages/react-instantsearch/package.json

**Summary**
This will make it more prominent when searched on places like Yarn -- and consistent with the GitHub description
**Result**
>⚡ Lightning-fast search for React and React Native apps, by Algolia 
is now the description

docs(description): add "by Algolia" to the package.json description

---

packages/react-instantsearch/src/core/createInstantSearchManager.error.test.js
packages/react-instantsearch/src/core/createInstantSearchManager.js

fix(error): reset error if next query is successful

---

packages/react-instantsearch/examples/next-app/components/app.js
packages/react-instantsearch/examples/next-app/pages/index.js

See: https://github.com/algolia/react-instantsearch/issues/177

docs(next-app): fix createURL in url sync

---

docgen/src/Getting_started_React_native.md

docs(react-native): fix broken link

---

scripts/release.sh

The script to update version of react-instantsearch in recipes worked well... but we should also update the theme.

chore(recipes): update algolia theme deps when releasing

---

packages/react-instantsearch/src/core/createInstantSearchServer.js
packages/react-instantsearch/src/core/createInstantSearchServer.test.js

fix(SSR): clean SP before rendering again

---

packages/react-instantsearch/package.json

These are useful metadata, definitely in Yarn

docs(pkg.json): add some keywords

---

packages/react-instantsearch/src/components/PoweredBy.js
packages/react-instantsearch/src/components/__snapshots__/PoweredBy.test.js.snap

fix(PoweredBy): aria-* tags are not camelcased

---

docgen/src/guide/Highlighting_results.md
packages/react-instantsearch/src/widgets/Snippet.js

docs(Snippet): add requirements

---

docgen/src/guide/Operations.md

**Summary**
Just fixing a small typo in the docs.
**Result**
N/A

docs(Operations): fix a typo

---

packages/react-instantsearch/src/components/SortBy.js

Reviewing this code, I saw that this part is not used

Remove unused code

---

packages/react-instantsearch/src/connectors/connectRefinementList.js

See https://github.com/algolia/react-instantsearch/issues/351

docs(RefinementList): fix defaultRefinement propTypes

---

packages/react-instantsearch/src/connectors/connectToggle.js
packages/react-instantsearch/src/widgets/Toggle.js

See https://github.com/algolia/react-instantsearch/issues/292

docs(Toggle): add requirements to cover null values use case

---

docgen/src/guide/Autocomplete_menu.md

broken link of previous page link (Server Side Rendering) in [React InstantSearch | Autocomplete menu](https://community.algolia.com/react-instantsearch/guide/Autocomplete_menu.html)

Fixing broken link

---

packages/react-instantsearch/src/core/createConnector.js

**Summary**
It's always useful to immediatly learn more and learn the solution of some problem that has been warned to you if available. React itself has short links for warnings (fb.me, we could also do that for alg.li, but maybe that's for later)
**Result**
adds two links to the createConnector deprecation

docs(createConnector): add links for more info to deprecation

---

.editorconfig

fixes #415
**Summary**
**Result**

chore(editorconfig): add config

---

scripts/gh-pages.js

To avoid unstyled content, since cloudflare will remove files that are in 404 while migrating to a new style like
**Summary**
**Result**

chore(release): never remove files from gh-pages

---

.travis.yml
packages/react-instantsearch/src/connectors/connectStateResults.js

See: https://discourse.algolia.com/t/react-instantsearch-v4-1-3-is-out-tada/3167/2?u=marielaure.thuret
Code sample has a mistake.

docs(connectStateResults): fix code sample

---

docgen/src/data/communityHeader.json
docgen/src/guide/Server-side_rendering.md

Some SSR links are broken on the new documentation website:
* inside SSR guide
* header

docs(SSR): fix links

---

docgen/assets/js/editThisPage.js
docgen/assets/js/main.js
docgen/src/stylesheets/components/_documentation.sass

Put back the button that disappeared when releasing new website design.

docs(website): add edit this page button

---

packages/react-instantsearch/src/widgets/MenuSelect.js

docs(menuSelect): put html tags in code block

---

docgen/src/guide/Server-side_rendering.md

**Summary**
In the SSR guide, we were not passing the searchState properly
**Result**

docs(SSR): pass {searchState} to fetch results

---

packages/react-instantsearch/examples/geo-search/src/App.js

Whenever you need to adjust state based on previous state, better to use the updater/reducer pattern of setState.

Use state updater pattern

---

packages/react-instantsearch/src/widgets/Snippet.js

**Summary**
imports from the wrong package for custom hits
**Result**
import from connectors, then refactored not to use connectors

docs(snippet): import correctly

---

packages/react-instantsearch/src/widgets/HierarchicalMenu.js

Following https://discourse.algolia.com/t/indexing-attributtes-for-hierarchicalmenu-use/3866 it seems it was not clear enough to have only the categories.
**Summary**
**Result**

docs(hierarchicalMenu): provide more context to requirements

---

packages/react-instantsearch/src/widgets/Highlight.js
packages/react-instantsearch/src/widgets/Snippet.js

doc: add <space> mention for separator

---

packages/react-instantsearch/src/connectors/connectStateResults.js

**Summary**
This seems to be a mistake in the [documentation](https://community.algolia.com/react-instantsearch/connectors/connectStateResults.html).

docs(connectors): fix prop type for connectStateResults

---

docgen/plugins/jsdoc-data.js
packages/react-instantsearch/src/core/InstantSearch.js

doc(InstantSearch): fix parsing

---

docgen/src/Getting_started_React_native.md

See: https://github.com/algolia/react-instantsearch/issues/756

docs(ReactNative): add FlatList warnings

---

stories/RefreshCache.stories.js

**Summary**
Fix typo in refresh cache story

chore(docs): fix typo in refresh cache story

---

packages/react-instantsearch/src/connectors/connectHighlight.js

docs(connectHighlight): add missing backquote for snippet

---

.netlify
netlify.toml

Add a Netlify configuration file for update the `yarn` version. (Not sure about the format)
cc @vvo

chore: Netlify configuration

---

packages/react-instantsearch/src/connectors/connectRange.js

docs: add missing providedProps for connectRange 

---

packages/react-instantsearch/src/connectors/connectToggle.js
packages/react-instantsearch/src/widgets/Toggle.js

**Summary**
Close partially #891.
Also remove the part on the `off` option, since we don't support this option.

docs(connectToggle): currentRefinement description

---

docgen/src/guide/React_native.md
packages/react-instantsearch/examples/query-suggestions-rn/App.js
packages/react-instantsearch/examples/query-suggestions-rn/Readme.md
packages/react-instantsearch/examples/query-suggestions-rn/app.json

* Add Algolia official guide link. 
* Close keyboard when scrolling. 
* Mention QS on our React Native guide

docs(qs): add algolia guide link

---

packages/react-instantsearch/examples/query-suggestions-rn/App.js

docs(qs): add filter in category

---

README.md

docs(readme): add missing instantsearch

---

docgen/layouts/common/header.pug
docgen/src/stylesheets/components/_deprecation-banner.sass

Update the banner text & color to match the release.
**Before**
**After**

docs: update banner

---

packages/react-instantsearch/src/core/Index.js
packages/react-instantsearch/src/core/InstantSearch.js
packages/react-instantsearch/src/widgets/Breadcrumb.js
packages/react-instantsearch/src/widgets/ClearRefinements.js
packages/react-instantsearch/src/widgets/Configure.js
packages/react-instantsearch/src/widgets/CurrentRefinements.js
packages/react-instantsearch/src/widgets/HierarchicalMenu.js
packages/react-instantsearch/src/widgets/Highlight.js
packages/react-instantsearch/src/widgets/Hits.js
packages/react-instantsearch/src/widgets/HitsPerPage.js
packages/react-instantsearch/src/widgets/InfiniteHits.js
packages/react-instantsearch/src/widgets/Menu.js
packages/react-instantsearch/src/widgets/MenuSelect.js
packages/react-instantsearch/src/widgets/NumericMenu.js
packages/react-instantsearch/src/widgets/Pagination.js
packages/react-instantsearch/src/widgets/Panel.js
packages/react-instantsearch/src/widgets/PoweredBy.js
packages/react-instantsearch/src/widgets/RangeInput.js
packages/react-instantsearch/src/widgets/RatingMenu.js
packages/react-instantsearch/src/widgets/ScrollTo.js
packages/react-instantsearch/src/widgets/SearchBox.js
packages/react-instantsearch/src/widgets/Snippet.js
packages/react-instantsearch/src/widgets/SortBy.js
packages/react-instantsearch/src/widgets/Stats.js
packages/react-instantsearch/src/widgets/ToggleRefinement.js

**Summary**
This PR fix some issues related to the example in the widgets:
- consistent name across the examples
- correct indentation
- correct rendering (always display something)

docs: update widgets example

---

packages/react-instantsearch/src/connectors/connectHighlight.js
packages/react-instantsearch/src/connectors/connectHits.js
packages/react-instantsearch/src/connectors/connectStateResults.js

**Summary**
This PR fix some issues related to the example in the widgets:
- consistent name across the examples
- correct indentation
- correct usage

docs: update connectors example

---

docgen/src/guide/Conditional_display.md

docs(Conditional): fix snippet for <AllResults />

---

docgen/layouts/connector.pug
docgen/layouts/widget.pug

Close #1059 
**Before**
**After**

docs: move requirements section on top

---

CHANGELOG.md

fix(CHANGELOG): update migration guide v5 links

---

docgen/src/guide/Custom_backend.md

This is the same content as algolia/instantsearch.js#2943 with React code samples in "Using the search client with InstantSearch".
[:link: **Link to the guide**](https://deploy-preview-1290--react-instantsearch.netlify.com/react-instantsearch/guide/custom_backend)

docs(guide): Add Custom Backend guide

---

scripts/release.sh

**Summary**
Install `react-instantsearch-dom` rather than `react-instantsearch`.

chore(release): update correct top level dependencies

---

packages/react-instantsearch-dom/src/widgets/MenuSelect.js

docs(MenuSelect): add limit option

---

packages/react-instantsearch-core/src/connectors/connectSearchBox.js

**Summary**
docs were wrongly copied from `connectCurrentRefinements`
**Result**
correct docs & no dots at the end

docs(connectSB): correct props docs

---

docgen/src/guide/Migration_guide_package_import.md
docgen/src/stylesheets/components/_documentation.sass

**Summary**
Add a migration guide for the new packages.
> [Guide preview](https://deploy-preview-1343--react-instantsearch.netlify.com/react-instantsearch/guide/migration_guide_package_import)

doc: migration import

---

stories/Highlight.stories.js

**Summary**
The story is failing because we don't have access to the index anymore. I dropped it for now to avoid issue with E2E. We should find a proper solution to datasets with missing features. In that case highlighted an array attribute.

chore: drop story for multi highlight for now

---

docgen/src/widgets/GeoSearch.md

**Summary**
- add words for the forwarded options on `GeoSearch`
- update `Redo` description

docs: GeoSearch

---

docgen/layouts/common/header.pug

**Summary**
This PR update the banner to point to the package import migration.

docs: update banner to package imports

---

README.md

**Summary**
This PR update the install to match the new package name. It also update the import for the client to use the `lite` version.
See the [README](https://github.com/algolia/react-instantsearch/blob/590a0a8962833a25cde6b74b78cc6f98eccace19/README.md).

docs(README): update install & imports

---

packages/react-instantsearch-dom/src/widgets/RangeSlider.js
stories/3rdPartyIntegrations.stories.js
stories/RangeSlider.stories.js

**Summary**
This PR adds a warning about the Rheostat usage inside the docs & Storybook.

docs: add Rheostat warning about version

---

docgen/src/Getting_started_React_native.md

Flag --save now implicit with npm.

docs: Remove --save flag

---

docgen/layouts/index.pug
docgen/src/examples/Demos.md

Remove both e-commerce & e-commerce infinite-hits

docs(demo): remove ecommerce demo

---

docgen/src/data/communityHeader.json

Same as https://github.com/algolia/vue-instantsearch/pull/506
**Summary**
**Result**

docs(https): fix mixed content

---

docgen/src/Getting_started.md

This was inconsistent with the rest of the guide
**Summary**
There was an error with the name of the package. 
**Result**

docs(getting started): update package name in introduction

---

docgen/src/Getting_started_React_native.md
docgen/src/examples/Demos.md
docgen/src/guide/Custom_connectors.md
docgen/src/guide/Highlighting_results.md
docgen/src/guide/Install.md
docgen/src/guide/React_native.md
docgen/src/guide/Search_parameters.md
docgen/src/guide/index.md

related to #1563 (not sure if there might be other references to it)
**Summary**
**Result**

docs: remove react-instantsearch occurrences

---

docgen/middlewares.js

docs: lookup for the configure widget

---

packages/react-instantsearch-core/src/connectors/connectHierarchicalMenu.js
packages/react-instantsearch-dom/src/widgets/HierarchicalMenu.js

- `string[]` → `string`
- update description

docs(HierarchicalMenu): fix `rootPath` type

---

docgen/layouts/common/header.pug

**Summary**
Changes the messaging to use "has" instead of "got" to clarify what has happened with React InstantSearch. Previous messaging implies an addition, instead of a replacement. (E.g. new widgets)

docs: update copy in header for new packages

---

docgen/layouts/common/header.pug

docs(banner): link to doc website

---

packages/react-instantsearch-core/src/connectors/connectConfigure.js
packages/react-instantsearch-core/src/connectors/connectScrollTo.js
packages/react-instantsearch-core/src/core/createInstantSearchManager.js
packages/react-instantsearch-core/src/core/indexUtils.js
packages/react-instantsearch-dom/src/core/createInstantSearchServer.js

**Summary**
Follow up to https://github.com/algolia/react-instantsearch/pull/1840#discussion_r245028444

feat(indexId): rename hasMultipleIndex -> hasMultipleIndices [PART-7]

---

packages/react-instantsearch-core/src/connectors/connectConfigure.js
packages/react-instantsearch-core/src/connectors/connectGeoSearch.js
packages/react-instantsearch-core/src/connectors/connectHierarchicalMenu.js
packages/react-instantsearch-core/src/connectors/connectMenu.js
packages/react-instantsearch-core/src/connectors/connectNumericMenu.js
packages/react-instantsearch-core/src/connectors/connectRange.js
packages/react-instantsearch-core/src/connectors/connectRefinementList.js
packages/react-instantsearch-core/src/connectors/connectScrollTo.js
packages/react-instantsearch-core/src/connectors/connectSearchBox.js
packages/react-instantsearch-core/src/connectors/connectToggleRefinement.js
packages/react-instantsearch-core/src/core/createInstantSearchManager.js
packages/react-instantsearch-core/src/core/indexUtils.js
packages/react-instantsearch-dom/src/core/createInstantSearchServer.js

**Summary**
Follow up to https://github.com/algolia/react-instantsearch/pull/1835#discussion_r244946397

feat(indexId): rename getIndex -> getIndexId [PART-6]

---

examples/server-side-rendering/package.json
examples/server-side-rendering/src/server.js
examples/server-side-rendering/yarn.lock

**Summary**
The PR adds a development environment to the SSR example.

chore(ssr): add development environment

---

packages/react-instantsearch-dom-maps/src/Control.js
packages/react-instantsearch-dom-maps/src/GoogleMaps.js
packages/react-instantsearch-dom-maps/src/__tests__/Control.js
packages/react-instantsearch-dom-maps/src/__tests__/GoogleMaps.js

**Summary**
This PR updates the `Control` implementation to leverage `withGoogleMaps` HOC.

feat(DOMMaps): use withGoogleMaps for Control [PART-5]

---

packages/react-instantsearch-dom-maps/src/Control.js
packages/react-instantsearch-dom-maps/src/GoogleMaps.js
packages/react-instantsearch-dom-maps/src/Redo.js
packages/react-instantsearch-dom-maps/src/__tests__/Control.js
packages/react-instantsearch-dom-maps/src/__tests__/GoogleMaps.js
packages/react-instantsearch-dom-maps/src/__tests__/Redo.js

**Summary**
This PR updates the `Redo` implementation to leverage `withGoogleMaps` HOC.

feat(DOMMaps): use withGoogleMaps for Redo [PART-4]

---

packages/react-instantsearch-dom-maps/src/Control.js
packages/react-instantsearch-dom-maps/src/CustomMarker.js
packages/react-instantsearch-dom-maps/src/GoogleMaps.js
packages/react-instantsearch-dom-maps/src/Marker.js
packages/react-instantsearch-dom-maps/src/Redo.js
packages/react-instantsearch-dom-maps/src/__tests__/Control.js
packages/react-instantsearch-dom-maps/src/__tests__/CustomMarker.js
packages/react-instantsearch-dom-maps/src/__tests__/GoogleMaps.js
packages/react-instantsearch-dom-maps/src/__tests__/Marker.js
packages/react-instantsearch-dom-maps/src/__tests__/Redo.js
packages/react-instantsearch-dom-maps/src/__tests__/__snapshots__/CustomMarker.js.snap

**Summary**
This PR updates the `CustomMarker` implementation to leverage `withGoogleMaps` HOC.

feat(DOMMaps): use withGoogleMaps for CustomMarker [PART-2]

---

examples/react-router-v3/package.json
renovate.json

https://github.com/renovatebot/renovate/issues/3235

chore(renovate): support examples

---

examples/next/package.json
examples/next/pages/index.js
examples/next/tests/__snapshots__/index.test.js.snap
examples/next/tests/index.test.js
examples/next/yarn.lock

This migrates away the Next.js example from deprecated React lifecycles.

fix(compat): upgrade Next.js example lifecycles

---

packages/react-instantsearch-dom/src/components/HierarchicalMenu.js
packages/react-instantsearch-dom/src/components/Menu.js
packages/react-instantsearch-dom/src/components/RefinementList.js

refactor(lodash): pick

---

packages/react-instantsearch-dom/src/components/Pagination.js
packages/react-instantsearch-dom/src/core/__tests__/utils.js
packages/react-instantsearch-dom/src/core/utils.ts

IFW-739
implementation & tests taken verbatim from InstantSearch.js

refactor(lodash): range

---

packages/react-instantsearch-core/src/connectors/connectNumericMenu.js
packages/react-instantsearch-core/src/connectors/connectToggleRefinement.js
packages/react-instantsearch-core/src/core/__tests__/utils.js
packages/react-instantsearch-core/src/core/utils.ts
packages/react-instantsearch-dom/src/components/MenuSelect.js
packages/react-instantsearch-dom/src/components/RatingMenu.js
packages/react-instantsearch-dom/src/core/__tests__/utils.js
packages/react-instantsearch-dom/src/core/utils.ts
tslint.json

Chosen to duplicate the funciton in core & dom, because we have no good way to share functionality otherwise
IFW-740

refactor(lodash): replace find

---

babel.config.js
package.json
packages/react-instantsearch-core/package.json
packages/react-instantsearch-core/src/connectors/connectInfiniteHits.js
packages/react-instantsearch-dom-maps/package.json
packages/react-instantsearch-dom/package.json
yarn.lock

- lodash from packages
- babel-plugin-lodash from root
- swap out isEqual from connectInfiniteHits
IFW-778
closes #2468
**Summary**
**Result**

chore(lodash): remove dependencies

---

website/examples/e-commerce/App.css

This adds style to app.css to wrap words.
Propagated from https://github.com/algolia/instantsearch.js/pull/3913

chore(examples): add app style for word wrap in e-commerce demo

---

packages/react-instantsearch-core/src/connectors/__tests__/connectConfigureRelatedItems.ts
packages/react-instantsearch-core/src/connectors/connectConfigureRelatedItems.ts

See algolia/instantsearch.js#4264.

fix(configureRelatedItems): use `facetFilters` to exclude `objectID`

---

packages/react-instantsearch-dom-maps/src/Connector.js

same as https://github.com/algolia/instantsearch.js/pull/4267

chore(dom-maps): add major version note on spelling

---

examples/react-router/package.json
examples/react-router/src/App.js
examples/react-router/src/App.test.js
examples/react-router/yarn.lock

This updates the React Router example to React hooks to be more conformed with [our documentation](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/react/).
Closes #2935

docs(examples): update React Router example to hooks

---

examples/autocomplete/package.json
examples/autocomplete/yarn.lock
examples/default-theme/package.json
examples/e-commerce/package.json
examples/geo-search/package.json
examples/geo-search/yarn.lock
examples/media/package.json
examples/multi-index/package.json
examples/multi-index/yarn.lock
examples/next/package.json
examples/next/yarn.lock
examples/react-router-v3/package.json
examples/react-router-v3/yarn.lock
examples/react-router/package.json
examples/react-router/yarn.lock
examples/server-side-rendering/package.json
examples/server-side-rendering/yarn.lock
examples/tourism/package.json
yarn.lock

**Summary**
This PR updates algoliasearch to `4.8.2`

chore(deps): update algoliasearch to 4.8.2

---

packages/react-instantsearch-dom/src/components/Stats.tsx
packages/react-instantsearch-dom/src/components/__tests__/Stats.tsx

**Summary**
Align Smart Sorted Stats message with InstantSearch.js

fix(stats): align Smart Sorted Stats message with InstantSearch.js 

---

examples/autocomplete/package.json
examples/autocomplete/yarn.lock
examples/default-theme/package.json
examples/e-commerce/package.json
examples/geo-search/package.json
examples/geo-search/yarn.lock
examples/media/package.json
examples/multi-index/package.json
examples/multi-index/yarn.lock
examples/next/package.json
examples/next/yarn.lock
examples/react-native-query-suggestions/package.json
examples/react-native-query-suggestions/yarn.lock
examples/react-native/package.json
examples/react-native/yarn.lock
examples/react-router-v3/package.json
examples/react-router-v3/yarn.lock
examples/react-router/package.json
examples/react-router/yarn.lock
examples/server-side-rendering/package.json
examples/server-side-rendering/yarn.lock
examples/tourism/package.json
yarn.lock

**Summary**
Update react-instantsearch examples to the latest version

examples(deps): update react-instantsearch to the latest version

---

packages/react-instantsearch/package.json

**Summary**
The root package `react-instantsearch` now has the correct value for the `module` property and includes the `files` property.
* related: https://github.com/vitejs/vite/issues/1488
**Result**
This package gets imported without error in vite.
```js
import { createConnector } from 'react-instantsearch';
```
↑ That code triggered the following error:
```
> node_modules/vite/dist/node/chunks/dep-e9a16784.js:32563:14: error: [plugin: vite:dep-scan] Failed to resolve entry for package "react-instantsearch". The package may have incorrect main/module/exports specified in its package.json.
32563 │         throw new Error(`Failed to resolve entry for package "${id}". ` +
╵               ^
at resolvePackageEntry (/Users/eunjaelee/workspace/custom-widget-boilerplate-react/node_modules/vite …
```

chore: update `module` and `files` properties in the root package

---

packages/react-instantsearch-dom/src/components/Hits.tsx
packages/react-instantsearch-dom/src/components/InfiniteHits.js

**Summary**
hitComponent accepts all react elements, things like memo are actually objects, not functions.
**Result**
No console errors for memo components
fixes #3086

fix(props): accept objects for hitComponent

---

package.json
packages/react-instantsearch-core/src/index.ts
packages/react-instantsearch-dom/src/index.js
packages/react-instantsearch-dom/src/widgets/DynamicWidgets.js
packages/react-instantsearch-dom/src/widgets/__tests__/DynamicWidgets.test.tsx
packages/react-instantsearch-native/src/index.ts
packages/react-instantsearch/connectors.js
packages/react-instantsearch/dom.js
packages/react-instantsearch/native.js
stories/DynamicWidgets.stories.js
yarn.lock

This widget is fully available now, and thus no longer experimental.
DX-2420

feat(DynamicWidgets): release as stable

---

examples/hooks/App.tsx
examples/hooks/components/Panel.tsx
examples/hooks/components/index.ts

**Summary**
This isn't the full panel (doesn't communicate to hide or collapse), but does allow for more spacing between widgets. A more complete panel will require implementing a usePanel that we can do later, as the InstantSearch.js panel is only a widget, not a connector
**Result**
adds a minimal panel to the hooks example
FX-606

docs(hooks): add Panel to example

---

examples/hooks/App.tsx
examples/hooks/components/HierarchicalMenu.tsx
examples/hooks/components/index.ts
examples/hooks/isSpecialClick.ts
packages/react-instantsearch-hooks/README.md
packages/react-instantsearch-hooks/src/__tests__/useHierarchicalMenu.test.tsx
packages/react-instantsearch-hooks/src/index.ts
packages/react-instantsearch-hooks/src/useHierarchicalMenu.ts

**Summary**
adds useHierarchicalMenu
**Result**
FX-441

feat(hooks): add useHierarchicalMenu

---

examples/hooks/App.tsx
examples/hooks/components/Menu.tsx
examples/hooks/components/index.ts
examples/hooks/isSpecialClick.ts
package.json
packages/react-instantsearch-hooks/README.md
packages/react-instantsearch-hooks/src/__tests__/useMenu.test.tsx
packages/react-instantsearch-hooks/src/index.ts
packages/react-instantsearch-hooks/src/useMenu.ts

**Summary**
implements useMenu
**Result**
Menu has been added, only main difference with React InstantSearch (v6) is that it doesn't have searchable
FX-442

feat(hooks): add useMenu

---

examples/hooks/App.css
examples/hooks/App.tsx
examples/hooks/components/RangeInput.tsx
examples/hooks/components/index.ts
package.json
packages/react-instantsearch-hooks/README.md
packages/react-instantsearch-hooks/src/__tests__/useRange.test.tsx
packages/react-instantsearch-hooks/src/index.ts
packages/react-instantsearch-hooks/src/useRange.ts

**Summary**
implement useRange
**Result**
example implemented RangeInput with approximately the same code as existing React InstantSearch, with the value/start transformations done in InstantSearch as well: https://github.com/algolia/instantsearch.js/blob/dcbbd8804b4b6471d24820b42826b57388974c27/src/widgets/range-input/range-input.tsx#L144-L154
FX-443

feat(hooks): add useRange

---

examples/hooks/App.tsx
examples/hooks/components/ToggleRefinement.tsx
examples/hooks/components/index.ts
package.json
packages/react-instantsearch-hooks/src/__tests__/useToggleRefinement.test.tsx
packages/react-instantsearch-hooks/src/index.ts
packages/react-instantsearch-hooks/src/useToggleRefinement.ts

**Summary**
adds the useToggleRefinement hook and its demo in the example application
**Result**
useToggleRefinement is added (but not documented, that will be done directly in the documentation)

feat(hooks): introduce useToggleRefinement

---

examples/hooks/App.css
examples/hooks/App.tsx
examples/hooks/components/ClearRefinements.tsx
examples/hooks/components/index.ts
packages/react-instantsearch-hooks/src/__tests__/useClearRefinements.test.tsx
packages/react-instantsearch-hooks/src/index.ts
packages/react-instantsearch-hooks/src/useClearRefinements.ts

**Summary**
adds the clearRefinements hook, as well as using it in the example.
**Result**
FX-737
#3252

feat(hooks): implement useClearRefinements

---

packages/react-instantsearch-hooks-server/README.md

**Summary**
This updates the README of React InstantSearch Hooks Server as we're about to release the official documentation.

docs(hooks-server): update README

---

examples/autocomplete/package.json
examples/next/package.json
examples/next/pages/index.js
examples/react-native-query-suggestions/App.js
examples/react-native-query-suggestions/package.json
examples/react-native/package.json
examples/react-router-v3/package.json
examples/react-router-v3/src/App.js
examples/react-router/package.json
yarn.lock

**Summary**
We don't need to depend explicitly on lodash in examples, as the expected methods already have alternatives that can be deduplicated
**Result**
no explicit dependency on lodash
closes #3215

chore(examples): remove lodash

---

packages/react-instantsearch-hooks-server/package.json
packages/react-instantsearch-hooks/package.json

This updates the homepage of the Hooks package to the new Algolia documentation.

chore(hooks): update packages' homepage

---

examples/hooks/package.json
yarn.lock

This updates the Parcel version of the example, which works with M1.

docs(examples): update Parcel version

---

package.json
yarn.lock

**Summary**
This PR updates `instantsearch-e2e-tests` to its latest version.
**Result**
Pipelines should have less issues with flaky tests.

chore: update e2e tests

---

.eslintrc.js
examples/hooks/App.tsx
examples/hooks/package.json
packages/react-instantsearch-hooks-dom/README.md
packages/react-instantsearch-hooks-dom/global.d.ts
packages/react-instantsearch-hooks-dom/package.json
packages/react-instantsearch-hooks-dom/rollup.config.js
packages/react-instantsearch-hooks-dom/src/index.ts
packages/react-instantsearch-hooks-dom/tsconfig.declaration.json
ship.config.js

**Summary**
Introduces the `react-instantsearch-hooks-dom` package
**Result**
A new package, which only re-exports the API of React InstantSearch hooks

feat(hooks-dom): introduce Hooks DOM package

---

examples/hooks-react-native/package.json
examples/hooks/package.json
packages/react-instantsearch-hooks-server/package.json
packages/react-instantsearch-hooks/package.json
packages/react-instantsearch-hooks/src/connectors/useHits.ts
packages/react-instantsearch-hooks/src/connectors/useInfiniteHits.ts
yarn.lock

**Summary**
make useHits and useInfiniteHits generic
**Result**
This requires https://github.com/algolia/instantsearch.js/pull/5019 and enables better generics for the Hits component (https://github.com/algolia/react-instantsearch/pull/3363)

feat(hooks): allow useHits and useInfiniteHit to be generic

---

examples/hooks-react-native/package.json
examples/hooks/package.json
packages/react-instantsearch-core/package.json
packages/react-instantsearch-dom/package.json
packages/react-instantsearch-hooks-dom/package.json
packages/react-instantsearch-hooks-dom/src/ui/InfiniteHits.tsx
packages/react-instantsearch-hooks-dom/src/ui/__tests__/InfiniteHits.test.tsx
packages/react-instantsearch-hooks-server/package.json
packages/react-instantsearch-hooks/package.json
packages/react-instantsearch-hooks/src/hooks/__tests__/useConnector.test.tsx
packages/react-instantsearch-hooks/src/lib/createSearchResults.ts
test/mock/createAPIResponse.ts
yarn.lock

based on https://github.com/algolia/instantsearch.js/pull/5023
fixes the tests for #3366

fix(infiniteHits): mark results as artificial

---

packages/react-instantsearch-hooks-web/README.md
packages/react-instantsearch-hooks/README.md
ship.config.js

**Summary**
- adds -web package in shipjs config (account already has access)
- copy readme from -hooks (links to the getting started guide that doesn't yet use the components though)
**Result**
-web can be published!

feat(hooks): expose DOM components

---

packages/react-instantsearch-hooks-web/src/widgets/SearchBox.tsx

**Summary**
The prop "queryHook" is not a dom property, so shouldn't be passed to the ui component
**Result**
fixes #3498

fix(SearchBox-hooks): correctly pass widget props

---

examples/hooks-react-native/package.json
examples/hooks/package.json
package.json
packages/react-instantsearch-core/package.json
packages/react-instantsearch-dom/package.json
packages/react-instantsearch-dom/src/widgets/__tests__/InstantSearch.tsx
packages/react-instantsearch-hooks-server/package.json
packages/react-instantsearch-hooks-server/src/__tests__/__snapshots__/getServerState.test.tsx.snap
packages/react-instantsearch-hooks-web/package.json
packages/react-instantsearch-hooks/package.json
yarn.lock

**Summary**
- updates instantsearch.js
- sort the search parameters in the request to improve cache hit rate with unstable widgets
- support client.search for sffv
- also includes a fix with the infiniteHitsCache import message
**Result**
updated instantsearch.js and helper in both React InstantSearch hooks and React InstantSearch dom

feat(core): sort parameters, support client.search for sffv

---

packages/react-instantsearch-hooks/src/components/__tests__/InstantSearch.test.tsx

This adds a test for using an unstable `routing` prop on `<InstantSearch>` to make sure that the state is recovered.
Since this test passes, it means that we can simplify the [routing APIs docs](https://www.algolia.com/doc/api-reference/widgets/history-router/react-hooks/#widget-param-getlocation) to remove the `useMemo()`.

test(hooks): test rerenders with unstable routing

---

.circleci/config.yml
jest.config.js
package.json
yarn.lock

**Summary**
store unit test results on circleci
**Result**
failing tests are easier to see

ci: store unit test results

---

examples/hooks-e-commerce/package.json
examples/hooks-react-native/package.json
examples/hooks/package.json
packages/react-instantsearch-hooks-server/package.json
packages/react-instantsearch-hooks-web/package.json
packages/react-instantsearch-hooks/package.json
yarn.lock

**Summary**
updates the InstantSearch dependency, which includes:
- better error messages
- no warnings when ratingMenu is used on the initial render
- fixing a type issue in geo search
**Result**
fixes #3534

fix(instantsearch): update dependency

---

packages/react-instantsearch-native/package.json

**Summary**
No code changes are needed, it works out of the box
**Result**
no warnings when React InstantSearch native + react native + react 18 are installed

fix(react-native): mark as compatible with react 18

---

examples/hooks-e-commerce/package.json
examples/hooks-react-native/package.json
examples/hooks/package.json
packages/react-instantsearch-core/package.json
packages/react-instantsearch-dom/package.json
packages/react-instantsearch-hooks-server/package.json
packages/react-instantsearch-hooks-server/src/getServerState.tsx
packages/react-instantsearch-hooks-web/package.json
packages/react-instantsearch-hooks/package.json
yarn.lock

**Summary**
updates the InstantSearch dependency
**Result**
- fixes related on onStateChange
- fixes related to hierarchical menu count
- closes https://github.com/algolia/react-instantsearch/issues/3623
- closes https://github.com/algolia/react-instantsearch/pull/3624

feat(dependencies): update instantsearch and helper

---

packages/react-instantsearch-hooks-web/README.md
packages/react-instantsearch-hooks/README.md

**Summary**
Adds a two-way clarification in the readme of React InstantSearch hooks and React InstantSearch hooks web to explain what each package is used for.
**Result**
fixes https://github.com/algolia/react-instantsearch/discussions/3610

docs(readme): add note for usage on -hooks and -hooks-web
